apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: some-name
  finalizers:
    - percona.com/delete-psmdb-pods-in-order
    - percona.com/delete-psmdb-pvc
spec:
  image:
  imagePullPolicy: Always
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  vpa:
    enabled: true
    updateMode: "Off"
    controlledValues: RequestsOnly
    minAllowed:
      cpu: 100m
      memory: 128Mi
    maxAllowed:
      cpu: "2"
      memory: 2Gi
    stabilizationWindow: 30s
  backup:
    enabled: false
  sharding:
    enabled: true
    mongos:
      size: 2
      affinity:
        antiAffinityTopologyKey: none
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 100M
    configsvrReplSet:
      size: 3
      affinity:
        antiAffinityTopologyKey: none
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 100M
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 1Gi
  replsets:
  - name: rs0
    size: 3
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 100M
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    nonvoting:
      enabled: true
      size: 1
      affinity:
        antiAffinityTopologyKey: none
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 100M
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 1Gi
    hidden:
      enabled: true
      size: 1
      affinity:
        antiAffinityTopologyKey: none
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 100M
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 1Gi
  secrets:
    users: some-users
