#!/bin/bash

set -o errexit

compare() {
	local database="$1"
	local command="$2"
	local uri="$3"
	local target="$4"

	if [[ $IMAGE_MONGOD =~ 5\.0 ]] && [ -f ${test_dir}/compare/$target-50.json ]; then
		target=$target-50
	fi

	run_mongo "use ${database}\n ${command}" "$uri" "mongodb" \
		| egrep -v 'I NETWORK|W NETWORK|F NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match|Error saving history file:' \
		| $sed -re 's/ObjectId\("[0-9a-f]+"\)//; s/-[0-9]+.svc/-xxxesvc/' \
		| sed '/"userId"/d' \
			>$tmp_dir/${target}

    diff ${test_dir}/compare/${target}.json $tmp_dir/${target}
}

get_user_cmd() {
	local user="$1"

	cmd="(function() {
	var user = db.getUser(${user});
	var roles = user.roles;
	roles.sort((a, b) => {
		if (a.role < b.role) return -1;
		if (a.role > b.role) return 1;
		return 0;
	});
	user.roles = roles;
	printjson(user);
	})();"

	echo "$cmd"
}


get_role_cmd() {
	local role="$1"

	cmd="(function() {
	var role = db.getRole(${role}, {showPrivileges: true, showAuthenticationRestrictions: true});
	var roles = role.roles;
	roles.sort((a, b) => {
		if (a.role < b.role) return -1;
		if (a.role > b.role) return 1;
		return 0;
	});
	role.roles = roles;
	printjson(role);
	})();"

	echo "$cmd"
}

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
set_debug

psmdb="some-name"
cluster="some-name-rs0"

create_infra $namespace

desc 'create secrets and start client'
kubectl_bin apply -f $conf_dir/secrets.yml
kubectl_bin apply -f $test_dir/conf/app-user-secrets.yml
apply_client $conf_dir/client.yml

mongoUri="userAdmin:userAdmin123456@$cluster.$namespace"

desc "create first PSMDB cluster $cluster"
apply_cluster $test_dir/conf/$cluster.yml

desc 'Check if all 3 Pods started'
wait_for_running $cluster 3

desc 'check user created on cluster creation'

userOne="user-one"
userOnePass=$(getSecretData "user-one" "userOnePassKey")
compare 'admin' "$(get_user_cmd \"user-one\")" "$mongoUri" "user-one"
check_mongo_auth "$userOne:$userOnePass@$cluster-0.$cluster.$namespace"

generatedUserSecret="$psmdb-custom-user-secret"
generatedPass=$(kubectl_bin get secret $generatedUserSecret -o jsonpath="{.data.user-gen}" | base64 -d)
compare 'admin' "$(get_user_cmd \"user-gen\")" "$mongoUri" "user-gen"
check_mongo_auth "user-gen:$generatedPass@$cluster-0.$cluster.$namespace"

# Only check if $external.user-external user exists, as the password is not known
# since we don't have a external provider set in this test
compare '$external' "$(get_user_cmd \"user-external\")" "$mongoUri" "user-external"

desc 'delete initial users from CR and create a new one'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-two",
				"db":"admin",
				"passwordSecretRef": {
					"name": "user-two",
					"key": "userTwoPassKey"
				},
				"roles": [
					{"db":"admin","name":"userAdminAnyDatabase"},
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3

compare 'admin' "$(get_user_cmd \"user-two\")" "$mongoUri" "user-two"

userTwo="user-two"
userTwoPass=$(getSecretData "user-two" "userTwoPassKey")

# Both users should be in the DB, the operator should not delete the user removed from the CR
check_mongo_auth "$userTwo:$userTwoPass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$userOne:$userOnePass@$cluster-0.$cluster.$namespace"

desc 'check password change'
userTwoNewPass="new-user-two-password"
patch_secret "user-two" "userTwoPassKey" "$(echo -n "$userTwoNewPass" | base64)"
sleep 20

check_mongo_auth "$userTwo:$userTwoNewPass@$cluster-0.$cluster.$namespace"

desc 'check user roles update from CR'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-two",
				"db":"admin",
				"passwordSecretRef": {
					"name": "user-two",
					"key": "userTwoPassKey"
				},
				"roles": [
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3
compare 'admin' "$(get_user_cmd \"user-two\")" "$mongoUri" "user-two-update-roles"

desc 'check user roles update from DB'

run_mongo \
	'use admin\n db.updateUser("user-two", { roles : [{ role : "userAdminAnyDatabase", db: "admin"}]})' \
	"$mongoUri"
sleep 15
compare 'admin' "$(get_user_cmd \"user-two\")" "$mongoUri" "user-two-update-roles"

desc 'check user recreated after deleted from DB'
run_mongo \
	'use admin\n db.dropUser("user-two")' \
	"$mongoUri"
sleep 15
compare 'admin' "$(get_user_cmd \"user-two\")" "$mongoUri" "user-two-update-roles"

desc 'check new user created after updated user name via CR'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-three",
				"db":"admin",
				"passwordSecretRef": {
					"name": "user-two",
					"key": "userTwoPassKey"
				},
				"roles": [
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3

compare 'admin' "$(get_user_cmd \"user-three\")" "$mongoUri" "user-three-admin-db"
compare 'admin' "$(get_user_cmd \"user-two\")" "$mongoUri" "user-two-update-roles"

# user-three and user-two should be in the DB
check_mongo_auth "$userTwo:$userTwoNewPass@$cluster-0.$cluster.$namespace"
check_mongo_auth "user-three:$userTwoNewPass@$cluster-0.$cluster.$namespace"

desc 'check new user created after updated user db via CR'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-three",
				"db":"newDb",
				"passwordSecretRef": {
					"name": "user-two",
					"key": "userTwoPassKey"
				},
				"roles": [
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3
compare 'newDb' "$(get_user_cmd \"user-three\")" "$mongoUri" "user-three-newDb-db"
compare 'admin' "$(get_user_cmd \"user-three\")" "$mongoUri" "user-three-admin-db"

desc 'check new user created with default db and secret password key'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-four",
				"passwordSecretRef": {
					"name": "user-two"
				},
				"roles": [
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3
compare 'admin' "$(get_user_cmd \"user-four\")" "$mongoUri" "user-four"

# ======================== Roles ========================

desc 'check user role on cluster initialization'
compare 'admin' "$(get_role_cmd \"role-one\")" "$mongoUri" "role-one"

desc 'check role recreated after deleted from DB'
run_mongo \
	'use admin\n db.dropRole("role-one")' \
	"$mongoUri"
sleep 15
compare 'admin' "$(get_role_cmd \"role-one\")" "$mongoUri" "role-one"

desc 'delete initial role from CR and create a new one'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"roles":[
			{
				"role": "role-two",
				"db": "admin",
				"privileges": [
					{
						"resource": {
							"db": "config",
							"collection": ""
						},
						"actions": [
							"find"
						]
					}
				],
				"roles": [
					{
						"role": "read",
						"db": "admin"
					}
				]
			}
		]
	}}'
wait_for_running $cluster 3
compare 'admin' "$(get_role_cmd \"role-one\")" "$mongoUri" "role-one"
compare 'admin' "$(get_role_cmd \"role-two\")" "$mongoUri" "role-two"

desc 'check role update from CR'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"roles":[
			{
				"role": "role-two",
				"db": "admin",
				"privileges": [
					{
						"resource": {
							"db": "config",
							"collection": ""
						},
						"actions": [
							"find"
						]
					}
				]
			}
		]
	}}'
wait_for_running $cluster 3
compare 'admin' "$(get_role_cmd \"role-two\")" "$mongoUri" "role-two-updated"

desc 'check role update from DB'
run_mongo \
	'use admin\n db.updateRole( "role-two",{privileges:[{resource: {db:"config", collection:"" }, actions: ["find", "update"]}]})' \
	"$mongoUri"
sleep 15
compare 'admin' "$(get_role_cmd \"role-two\")" "$mongoUri" "role-two-updated"

desc 'check new role created after updated role name via CR'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"roles":[
			{
				"role": "role-three",
				"db": "admin",
				"privileges": [
					{
						"resource": {
							"db": "config",
							"collection": ""
						},
						"actions": [
							"find"
						]
					}
				]
			}
		]
	}}'
wait_for_running $cluster 3
compare 'admin' "$(get_role_cmd \"role-three\")" "$mongoUri" "role-three"

desc 'check creating multiple roles and the users in a single CR apply'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {
			"roles": [
				{
				"role": "role-four",
				"db": "testAdmin1",
				"privileges": [
					{
					"resource": {
						"db": "testAdmin1",
						"collection": ""
					},
					"actions": [
						"find",
						"listIndexes",
						"listCollections"
					]
					},
					{
					"resource": {
						"db": "testAdmin1",
						"collection": "system.profile"
					},
					"actions": [
						"dbStats",
						"collStats",
						"indexStats"
					]
					},
					{
					"resource": {
						"db": "testAdmin1",
						"collection": "system.version"
					},
					"actions": [
						"find"
					]
					}
				]
				},
				{
				"role": "role-five",
				"db": "testAdmin2",
				"privileges": [
					{
					"resource": {
						"db": "testAdmin2",
						"collection": ""
					},
					"actions": [
						"find",
						"listIndexes",
						"listCollections"
					]
					},
					{
					"resource": {
						"db": "testAdmin2",
						"collection": "system.profile"
					},
					"actions": [
						"dbStats",
						"collStats",
						"indexStats"
					]
					},
					{
					"resource": {
						"db": "testAdmin2",
						"collection": "system.version"
					},
					"actions": [
						"find"
					]
					}
				]
				}
			],
			"users": [
				{
				"name": "user-five",
				"db": "testAdmin",
				"passwordSecretRef": {
					"name": "user-one",
					"key": "userOnePassKey"
				},
				"roles": [
					{
						"name": "role-four",
						"db": "testAdmin1"
					},
					{
						"name": "role-five",
						"db": "testAdmin2"
					}
				]
				},
				{
				"name": "user-six",
				"db": "testAdmin",
				"passwordSecretRef": {
					"name": "user-one",
					"key": "userOnePassKey"
				},
				"roles": [
					{
					"name": "role-five",
					"db": "testAdmin2"
					}
				]
				}
			]
	}}'
wait_for_running $cluster 3
compare 'testAdmin1' "$(get_role_cmd \"role-four\")" "$mongoUri" "role-four"
compare 'testAdmin2' "$(get_role_cmd \"role-five\")" "$mongoUri" "role-five"
compare 'testAdmin' "$(get_user_cmd \"user-five\")" "$mongoUri" "user-five"
compare 'testAdmin' "$(get_user_cmd \"user-six\")" "$mongoUri" "user-six"

destroy $namespace

desc 'test passed'
