apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmctl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cmctl
  template:
    metadata:
      labels:
        name: cmctl
    spec:
      serviceAccountName: cmctl
      containers:
        - name: cmctl
          image: curlimages/curl
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - |
            curl -fsSL -o /tmp/cmctl.tar.gz https://github.com/cert-manager/cert-manager/releases/latest/download/cmctl-linux-amd64.tar.gz \
            && tar -C /tmp -xzf /tmp/cmctl.tar.gz \
            && sleep 100500
      restartPolicy: Always
