apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: version-service-exact
  finalizers:
    - delete-psmdb-pvc
spec:
  image:
  initImage: #initImage
  imagePullPolicy: Always
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: http://version-service:11000
    apply: 4.2.7-7
    schedule: "0 2 * * *"
  mongod:
    net:
      hostPort: 0
      port: 27017
    operationProfiling:
      mode: slowOp
      rateLimit: 1
      slowOpThresholdMs: 100
    security:
      enableEncryption: true
      redactClientLogData: false
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        collectionConfig:
          blockCompressor: snappy
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        indexConfig:
          prefixCompression: true
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 0.5G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  secrets:
    key: some-key
    users: some-users
