apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  labels:
    app.kubernetes.io/component: nonVoting
    app.kubernetes.io/instance: nonvoting
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: nonvoting-rs0-nv
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: nonvoting
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: nonVoting
      app.kubernetes.io/instance: nonvoting
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: nonvoting-rs0
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: nonVoting
        app.kubernetes.io/instance: nonvoting
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: nonVoting
                  app.kubernetes.io/instance: nonvoting
                  app.kubernetes.io/managed-by: percona-server-mongodb-operator
                  app.kubernetes.io/name: percona-server-mongodb
                  app.kubernetes.io/part-of: percona-server-mongodb
                  app.kubernetes.io/replset: rs0
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=rs0
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --sslMode=preferSSL
            - --clusterAuthMode=x509
            - --slowms=0
            - --profile=1
            - --enableEncryption
            - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
            - --wiredTigerCacheSizeGB=0.25
            - --wiredTigerIndexPrefixCompression=true
          command:
            - /data/db/ps-entry.sh
          env:
            - name: SERVICE_NAME
              value: nonvoting
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLSET
              value: rs0
          envFrom:
            - secretRef:
                name: internal-nonvoting-users
                optional: false
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /data/db/mongodb-healthcheck
                - k8s
                - liveness
                - --ssl
                - --sslInsecure
                - --sslCAFile
                - /etc/mongodb-ssl/ca.crt
                - --sslPEMKeyFile
                - /tmp/tls.pem
                - --startupDelaySeconds
                - "7200"
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: mongod-nv
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          readinessProbe:
            failureThreshold: 8
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 300m
              memory: 500M
            requests:
              cpu: 200m
              memory: 300M
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /etc/mongodb-secrets
              name: nonvoting-mongodb-keyfile
              readOnly: true
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /etc/mongodb-ssl-internal
              name: ssl-internal
              readOnly: true
            - mountPath: /etc/mongodb-encryption
              name: nonvoting-mongodb-encryption-key
              readOnly: true
            - mountPath: /etc/users-secret
              name: users-secret-file
          workingDir: /data/db
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /init-entrypoint.sh
          imagePullPolicy: Always
          name: mongo-init
          resources:
            limits:
              cpu: 300m
              memory: 500M
            requests:
              cpu: 200m
              memory: 300M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nonvoting-mongodb-keyfile
          secret:
            defaultMode: 288
            optional: false
            secretName: nonvoting-mongodb-keyfile
        - name: nonvoting-mongodb-encryption-key
          secret:
            defaultMode: 288
            optional: false
            secretName: nonvoting-mongodb-encryption-key
        - name: ssl
          secret:
            defaultMode: 288
            optional: false
            secretName: nonvoting-ssl
        - name: ssl-internal
          secret:
            defaultMode: 288
            optional: true
            secretName: nonvoting-ssl-internal
        - name: users-secret-file
          secret:
            defaultMode: 420
            secretName: internal-nonvoting-users
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: mongod-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      status:
        phase: Pending
