#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

CLUSTER='upgrade'
CLUSTER_SIZE=3
API_TO_UPDATE=${API}
IMAGE_TO_UPDATE=${IMAGE}
IMAGE_PMM_TO_UPDATE=${IMAGE_PMM}
IMAGE_MONGOD_TO_UPDATE=${IMAGE_MONGOD}
IMAGE_BACKUP_TO_UPDATE=${IMAGE_BACKUP}
OPERATOR_NAME='percona-server-mongodb-operator'

MONGO_VER=$(echo -n "${IMAGE_MONGOD}" | $sed -r 's/.*([0-9].[0-9])$/\1/')
API='psmdb.percona.com/v1-1-0'
IMAGE='percona/percona-server-mongodb-operator:1.1.0'
IMAGE_PMM='percona/percona-server-mongodb-operator:1.1.0-pmm'
IMAGE_MONGOD="percona/percona-server-mongodb-operator:1.1.0-mongod$MONGO_VER"
IMAGE_BACKUP='percona/percona-server-mongodb-operator:1.1.0-backup'

if [[ "${MONGO_VER}" == "4.2" ]]; then
    IMAGE_MONGOD="percona/percona-server-mongodb-operator:1.1.0-mongod4.0"
fi

compare_generation() {
    generation=$1
    resource=${2:-statefulset}
    name=${3}
    if [[ ${generation} != $(kubectl_bin get "${resource}" "${name}" -o jsonpath='{.metadata.generation}') ]]; then
        echo "Resource ${name} has not been updated"
        exit 1
    fi
}

wait_cluster_consistency() {
    cluster_name=$1
    cluster_size=$2
    until [[ "$(kubectl_bin get psmdb "${cluster_name}" -o jsonpath='{.status.state}')" == "ready" \
             && "$(kubectl_bin get psmdb "${cluster_name}" -o jsonpath='{.status.replsets.rs0.ready}')" == "${cluster_size}" ]]; do
        echo 'waiting for cluster readyness'
        sleep 20
    done
}

main() {
	create_namespace $namespace
    deploy_operator

    deploy_helm $namespace
    deploy_minio

    kubectl_bin apply -f "${conf_dir}/client.yml" \
                  -f "${conf_dir}/secrets.yml" \
                  -f "${conf_dir}/minio-secret.yml"

    spinup_psmdb "${CLUSTER}"-rs0 "$test_dir/conf/${CLUSTER}-rs0.yml" "${CLUSTER_SIZE}"

    compare_generation 1 statefulset "${CLUSTER}-rs0"

    kubectl_bin patch deployment "${OPERATOR_NAME}" \
        -p'{"spec":{"template":{"spec":{"containers":[{"name":"'"${OPERATOR_NAME}"'","image":"'"${IMAGE_TO_UPDATE}"'"}]}}}}'
    kubectl_bin rollout status deployment/"${OPERATOR_NAME}"

    until [[ $(kubectl_bin get pods --selector=name="${OPERATOR_NAME}" \
                                -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[0].image' \
                                | grep -v 'NAME' | wc -l | awk '{print $1}') -eq 1 ]]; do
        sleep 5
    done

    if [[ "${IMAGE_TO_UPDATE}" == $(kubectl_bin get pod --selector=name="${OPERATOR_NAME}" -o jsonpath='{.items[*].spec.containers[?(@.name == "'"${OPERATOR_NAME}"'")].image}') \
          && "${IMAGE_MONGOD}" == $(kubectl_bin get psmdb "${CLUSTER}" -o jsonpath='{.spec.image}') ]]; then
        : Operator image has been updated correctly
    else
        echo 'Operator image has not been updated'
        exit 1
    fi
    
    compare_generation 1 statefulset "${CLUSTER}-rs0"

    sleep 10
    wait_for_running "${CLUSTER}-rs0" "${CLUSTER_SIZE}"

    kubectl_bin patch psmdb "${CLUSTER}" --type=merge --patch '{
        "metadata": {"annotations":{ "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"'"$API_TO_UPDATE"'\"}" }},
        "spec": {
            "image": "'"$IMAGE_MONGOD_TO_UPDATE"'",
            "pmm": { "image": "'"$IMAGE_PMM_TO_UPDATE"'" },
            "backup": { "image": "'"$IMAGE_BACKUP_TO_UPDATE"'" }
        }}'

    sleep 10
    compare_generation 2 statefulset "${CLUSTER}-rs0"
    compare_generation 2 psmdb "${CLUSTER}"

    if [[ "${IMAGE_TO_UPDATE}" == $(kubectl_bin get pod --selector=name="${OPERATOR_NAME}" -o jsonpath='{.items[*].spec.containers[?(@.name == "'"${OPERATOR_NAME}"'")].image}') \
          && "${IMAGE_MONGOD_TO_UPDATE}" == $(kubectl_bin get psmdb "${CLUSTER}" -o jsonpath='{.spec.image}') ]]; then
        : MongoDB image has been updated correctly
    else
        echo 'MongoDB image has not been updated'
        exit 1
    fi
    
    sleep 10

    wait_cluster_consistency "${CLUSTER}" "${CLUSTER_SIZE}"
    sleep 10
    wait_cluster_consistency "${CLUSTER}" "${CLUSTER_SIZE}"
    sleep 10 
    wait_cluster_consistency "${CLUSTER}" "${CLUSTER_SIZE}"

    wait_for_running "${CLUSTER}-rs0" "${CLUSTER_SIZE}"

    simple_data_check "${CLUSTER}-rs0" "${CLUSTER_SIZE}"
    destroy $namespace
}

main
