#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

CLUSTER='upgrade-rs0'
CLUSTER_SIZE=3
IMAGE_TO_UPDATE=${IMAGE}
IMAGE_MONGOD_TO_UPDATE=${IMAGE_MONGOD}
IMAGE_BACKUP_TO_UPDATE=${IMAGE_BACKUP}
OPERATOR_NAME='percona-server-mongodb-operator'

IMAGE='percona/percona-server-mongodb-operator:1.0.0'
IMAGE_MONGOD='percona/percona-server-mongodb-operator:1.0.0-mongod4.0.9'
IMAGE_BACKUP='percona/percona-server-mongodb-operator:1.0.0-backup'

main() {
	create_namespace $namespace
    deploy_operator

    kubectl apply -f "${conf_dir}/client.yml" \
                  -f "${conf_dir}/secrets.yml"

    spinup_psmdb "${CLUSTER}" "$test_dir/conf/${CLUSTER}.yml" "${CLUSTER_SIZE}"

    kubectl patch deployment "${OPERATOR_NAME}" \
        -p'{"spec":{"template":{"spec":{"containers":[{"name":"'"${OPERATOR_NAME}"'","image":"'"${IMAGE_TO_UPDATE}"'"}]}}}}'
    kubectl rollout status deployment/"${OPERATOR_NAME}"

    sleep 10
    wait_for_running "${CLUSTER}" "${CLUSTER_SIZE}"

    # destroy $namespace
}

main