apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - percona.com/delete-psmdb-pvc
  name: some-name
spec:
  crVersion: 1.17.0
  image:
  imagePullPolicy: Always
  backup:
    enabled: true
    image:
    storages:
      minio:
        type: s3
        s3:
          credentialsSecret: minio-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: http://minio-service:9000/
          insecureSkipTLSVerify: false
  replsets:
  - name: rs0
    size: 3
    expose:
      enabled: false
      exposeType: ClusterIP
    replsetOverrides:
      some-name-rs0-0:
        host: external-rs0-0.NAMESPACE.svc:27017
        tags:
          test-key: test-value-0
      some-name-rs0-1:
        host: external-rs0-1.NAMESPACE.svc:27017
        tags:
          test-key: test-value-1
      some-name-rs0-2:
        host: external-rs0-2.NAMESPACE.svc:27017
        tags:
          test-key: test-value-2
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi
  secrets:
    users: some-users
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: none
      expose:
        enabled: false
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: false
    mongos:
      affinity:
        antiAffinityTopologyKey: none
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 3
  updateStrategy: SmartUpdate
