apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBRestore
metadata:
  name:
spec:
  clusterName:
  pitr:
    pitrType: latest
  backupSource:
    type:
    destination: s3://DESTINATION
    s3:
      credentialsSecret: s3-secret
      bucket: operator-testing
      prefix: some-name-source
      endpointUrl: http://s3-storage-all-in-one:8333/
      region: us-east-1
      insecureSkipTLSVerify: false

