apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBRestore
metadata:
  name:
spec:
  clusterName: some-name
  backupName:
  pitr:
    pitrType:
    date:
  backupSource:
    type: physical
    destination: s3://DESTINATION
    s3:
      credentialsSecret: s3-secret
      bucket: BUCKET-NAME
      endpointUrl: http://s3-storage-all-in-one:8333/
      region: us-east-1
      insecureSkipTLSVerify: false

