apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBRestore
metadata:
  name:
spec:
  clusterName: some-name
  backupName:
  pitr:
    pitrType:
    date:
  backupSource:
    type: physical
    destination: s3://DESTINATION
    s3:
      credentialsSecret: minio-secret
      bucket: BUCKET-NAME
      endpointUrl: http://minio-service:9000/
      region: us-east-1
      insecureSkipTLSVerify: false

