#!/bin/bash

set -o errexit

test_dir=$(realpath "$(dirname "$0")")
. "${test_dir}/../functions"
set_debug

newpass="test-password"
newpassencrypted=$(echo -n "$newpass" | base64)
tag_value=$'h8V"k3N\'$(r7B)\nx2M'

create_infra "$namespace"

deploy_s3_storage

desc 'create secrets and start client'
kubectl_bin apply -f "${conf_dir}/client.yml" \
	-f "${test_dir}/conf/secrets.yml" \
	-f "${conf_dir}/s3-secret.yml"

init_user=$(getUserData "some-users" "MONGODB_USER_ADMIN_USER")
init_password=$(getUserData "some-users" "MONGODB_USER_ADMIN_PASSWORD")

cluster="some-name-rs0"
desc "create first PSMDB cluster $cluster"
apply_cluster "$test_dir/conf/$cluster.yml"
desc 'Check if all 3 Pods started'
wait_for_running $cluster 3

mongo_shell=$(kubectl_bin exec "$cluster-0" -c mongod -- sh -c \
	'if command -v mongosh >/dev/null; then echo mongosh; else echo mongo; fi')

desc 'authenticate with the escaped user name and password'
check_mongo_auth "$init_user:$init_password@$cluster-0.$cluster.$namespace"

desc 'check the replica set tag survived rs.initiate'
actual_tag=$(kubectl_bin exec "$cluster-0" -c mongod -- \
	"$mongo_shell" --quiet --host localhost --authenticationDatabase admin \
	--username clusterAdmin --password clusterAdmin123456 \
	--eval 'print(rs.conf().members[0].tags.special)')
[[ $actual_tag == "$tag_value" ]]

backup_name="backup-local-s3"

desc 'change MONGODB_DATABASE_ADMIN_PASSWORD'
patch_secret "some-users" "MONGODB_DATABASE_ADMIN_PASSWORD" "$newpassencrypted"
sleep 25

psmdb="some-name"
wait_cluster_consistency $psmdb
sleep 15

user=$(getUserData "some-users" "MONGODB_DATABASE_ADMIN_USER")
check_mongo_auth "$user:$newpass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-2.$cluster.$namespace"

desc 'change MONGODB_BACKUP_PASSWORD'
patch_secret "some-users" "MONGODB_BACKUP_PASSWORD" "$newpassencrypted"
sleep 25
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_BACKUP_USER")
check_mongo_auth "$user:$newpass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-2.$cluster.$namespace"

desc 'change MONGODB_BACKUP_USER'
newnameencrypted=$(echo -n "backup2" | base64)
patch_secret "some-users" "MONGODB_BACKUP_USER" "$newnameencrypted"
sleep 25

wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_BACKUP_USER")
check_mongo_auth "$user:$newpass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-2.$cluster.$namespace"

desc 'run backup'
run_backup local-s3
wait_backup "$backup_name"

desc 'change MONGODB_USER_ADMIN_PASSWORD'
patch_secret "some-users" "MONGODB_USER_ADMIN_PASSWORD" "$newpassencrypted"
sleep 25
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_USER_ADMIN_USER")
check_mongo_auth "$user:$newpass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-2.$cluster.$namespace"

desc 'change MONGODB_USER_ADMIN_USER'
newnameencrypted=$(echo -n "userAdmin2" | base64)
patch_secret "some-users" "MONGODB_USER_ADMIN_USER" "$newnameencrypted"
sleep 25
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_USER_ADMIN_USER")
check_mongo_auth "$user:$newpass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-2.$cluster.$namespace"

desc 'change MONGODB_CLUSTER_ADMIN_PASSWORD'
patch_secret "some-users" "MONGODB_CLUSTER_ADMIN_PASSWORD" "$newpassencrypted"
sleep 25
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_CLUSTER_ADMIN_USER")
check_mongo_auth "$user:$newpass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-2.$cluster.$namespace"

desc 'change MONGODB_CLUSTER_MONITOR_PASSWORD'
patch_secret "some-users" "MONGODB_CLUSTER_MONITOR_PASSWORD" "$newpassencrypted"
sleep 25
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_CLUSTER_MONITOR_USER")
check_mongo_auth "$user:$newpass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$newpass@$cluster-2.$cluster.$namespace"

desc 'remove users secret'
kubectl_bin delete secret some-users
sleep 35
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_USER_ADMIN_USER")
pass=$(getUserData "some-users" "MONGODB_USER_ADMIN_PASSWORD")
check_mongo_auth "$user:$pass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$pass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$pass@$cluster-2.$cluster.$namespace"

desc 'update all users'
kubectl_bin apply -f "${conf_dir}/secrets.yml"
sleep 35
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_USER_ADMIN_USER")
pass=$(getUserData "some-users" "MONGODB_USER_ADMIN_PASSWORD")
check_mongo_auth "$user:$pass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$pass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$pass@$cluster-2.$cluster.$namespace"

newmonitorusername="newmonitorusername"
desc 'update monitor user username'
patch_secret "some-users" "MONGODB_CLUSTER_MONITOR_USER" "$(echo -n "$newmonitorusername" | base64)"
sleep 35
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_CLUSTER_MONITOR_USER")
pass=$(getUserData "some-users" "MONGODB_CLUSTER_MONITOR_PASSWORD")
check_mongo_auth "$user:$pass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$pass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$pass@$cluster-2.$cluster.$namespace"

desc 'secret without userAdmin'
kubectl_bin apply -f "${test_dir}/conf/secrets-2.yml"
sleep 25
wait_cluster_consistency $psmdb
sleep 15
user=$(getUserData "some-users" "MONGODB_USER_ADMIN_USER")
pass=$(getUserData "some-users" "MONGODB_USER_ADMIN_PASSWORD")
check_mongo_auth "$user:$pass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$user:$pass@$cluster-1.$cluster.$namespace"
check_mongo_auth "$user:$pass@$cluster-2.$cluster.$namespace"

destroy "$namespace"

desc 'test passed'
