apiVersion: v1
kind: Service
metadata:
  name: another-name-rs0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: another-name
spec:
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app.kubernetes.io/instance: another-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  sessionAffinity: None
  type: ClusterIP
