apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: big-data-secrets
data:
  MONGODB_BACKUP_PASSWORD: NkZEbUJ3SW81a1E0QkhlODU3Tw==
  MONGODB_BACKUP_USER: YmFja3Vw
  MONGODB_CLUSTER_ADMIN_PASSWORD: ZWtRVGVpMmQxdVNIMVVLMkYz
  MONGODB_CLUSTER_ADMIN_USER: Y2x1c3RlckFkbWlu
  MONGODB_CLUSTER_MONITOR_PASSWORD: WWt6WlZMclZycTlKY0s3c3ROTw==
  MONGODB_CLUSTER_MONITOR_USER: Y2x1c3Rlck1vbml0b3I=
  MONGODB_DATABASE_ADMIN_PASSWORD: VWtvOFdSUXVFYVJtc29QVkV1Rw==
  MONGODB_DATABASE_ADMIN_USER: ZGF0YWJhc2VBZG1pbg==
  MONGODB_USER_ADMIN_PASSWORD: MkN1UjBCZTNRQkp5YUI1bHpx
  MONGODB_USER_ADMIN_USER: dXNlckFkbWlu
