apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: external-service
    app.kubernetes.io/instance: cluster-ip
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: cluster-ip-rs0-0
  ownerReferences:
  - apiVersion: psmdb.percona.com/v1alpha1
    controller: true
    kind: PerconaServerMongoDB
    name: cluster-ip
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: cluster-ip-rs0-0
  sessionAffinity: None
  type: ClusterIP
