apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  labels:
    app.kubernetes.io/component: mongod
    app.kubernetes.io/instance: node-port
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: node-port-rs0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: node-port
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongod
      app.kubernetes.io/instance: node-port
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: node-port-rs0
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: mongod
        app.kubernetes.io/instance: node-port
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      containers:
        - args:
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=rs0
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --clusterAuthMode=x509
            - --enableEncryption
            - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
            - --wiredTigerIndexPrefixCompression=true
            - --config=/etc/mongodb-config/mongod.conf
          command:
            - /opt/percona/ps-entry.sh
          env:
            - name: SERVICE_NAME
              value: node-port
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLSET
              value: rs0
          envFrom:
            - secretRef:
                name: internal-node-port-users
                optional: false
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /opt/percona/mongodb-healthcheck
                - k8s
                - liveness
                - --ssl
                - --sslInsecure
                - --sslCAFile
                - /etc/mongodb-ssl/ca.crt
                - --sslPEMKeyFile
                - /tmp/tls.pem
                - --startupDelaySeconds
                - "7200"
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: mongod
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          readinessProbe:
            failureThreshold: 8
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 2
          resources: {}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /etc/mongodb-secrets
              name: node-port-mongodb-keyfile
              readOnly: true
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /etc/mongodb-ssl-internal
              name: ssl-internal
              readOnly: true
            - mountPath: /etc/mongodb-config
              name: config
            - mountPath: /opt/percona
              name: bin
            - mountPath: /etc/mongodb-encryption
              name: node-port-mongodb-encryption-key
              readOnly: true
            - mountPath: /etc/users-secret
              name: users-secret-file
          workingDir: /data/db
        - args:
            - pbm-agent-entrypoint
          command:
            - /opt/percona/pbm-entry.sh
          env:
            - name: PBM_AGENT_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGODB_BACKUP_USER
                  name: internal-node-port-users
                  optional: false
            - name: PBM_AGENT_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_BACKUP_PASSWORD
                  name: internal-node-port-users
                  optional: false
            - name: PBM_MONGODB_REPLSET
              value: rs0
            - name: PBM_MONGODB_PORT
              value: "27017"
            - name: PBM_AGENT_SIDECAR
              value: "true"
            - name: PBM_AGENT_SIDECAR_SLEEP
              value: "5"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PBM_MONGODB_URI
              value: mongodb://$(PBM_AGENT_MONGODB_USERNAME):$(PBM_AGENT_MONGODB_PASSWORD)@$(POD_NAME)
          imagePullPolicy: Always
          name: backup-agent
          resources: {}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /opt/percona
              name: bin
              readOnly: true
            - mountPath: /data/db
              name: mongod-data
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /init-entrypoint.sh
          imagePullPolicy: Always
          name: mongo-init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: node-port-mongodb-keyfile
          secret:
            defaultMode: 288
            optional: false
            secretName: node-port-mongodb-keyfile
        - emptyDir: {}
          name: bin
        - configMap:
            defaultMode: 420
            name: node-port-rs0-mongod
            optional: true
          name: config
        - name: node-port-mongodb-encryption-key
          secret:
            defaultMode: 288
            optional: false
            secretName: node-port-mongodb-encryption-key
        - name: ssl
          secret:
            defaultMode: 288
            optional: false
            secretName: node-port-ssl
        - name: ssl-internal
          secret:
            defaultMode: 288
            optional: true
            secretName: node-port-ssl-internal
        - name: users-secret-file
          secret:
            defaultMode: 420
            secretName: internal-node-port-users
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: mongod-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status:
        phase: Pending
