#!/bin/bash

set -o errexit

test_dir=$(realpath "$(dirname "$0")")
. "${test_dir}/../functions"
set_debug

create_infra "${namespace}"

desc 'Deploy cert-manager for proper certificate generation'
deploy_cert_manager

desc 'Create self-signed issuer'
kubectl_bin apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: ${namespace}
spec:
  selfSigned: {}
EOF

desc 'Generate certificate for MinIO via cert-manager'

kubectl_bin apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: ${namespace}
spec:
  secretName: minio-tls-temp
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: minio-service
  dnsNames:
  - minio-service
  - minio-service.${namespace}
  - minio-service.${namespace}.svc
  - minio-service.${namespace}.svc.cluster.local
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

kubectl_bin wait --for=condition=Ready certificate/minio-cert \
  -n ${namespace} --timeout=120s

kubectl_bin get secret minio-tls-temp -n ${namespace} \
  -o jsonpath='{.data.tls\.crt}' | base64 -d > /tmp/minio-cert.pem

kubectl_bin get secret minio-tls-temp -n ${namespace} \
  -o jsonpath='{.data.tls\.key}' | base64 -d > /tmp/minio-key.pem

kubectl_bin create secret generic minio-tls -n ${namespace} \
  --from-file=public.crt=/tmp/minio-cert.pem \
  --from-file=private.key=/tmp/minio-key.pem

kubectl_bin create secret generic minio-ca-bundle -n ${namespace} \
  --from-file=ca.crt=/tmp/minio-cert.pem

desc 'Deploy MinIO with TLS'
deploy_minio minio-tls
apply_s3_storage_secrets

###############################################################################
# Deploy cluster with single CA bundle
###############################################################################

cluster="some-name"

kubectl_bin apply -f "${test_dir}/conf/secrets.yml"
kubectl_bin apply -f "${conf_dir}/client_with_tls.yml"
apply_cluster "${test_dir}/conf/${cluster}-single-ca.yml"

wait_for_running ${cluster}-rs0 3
wait_cluster_consistency ${cluster}

###############################################################################
# Verify CA bundle infrastructure
###############################################################################

desc 'Verify CA bundle infrastructure'

kubectl_bin exec ${cluster}-rs0-0 -n ${namespace} -c backup-agent -- \
  test -f /etc/s3/certs/ca-bundle.crt

kubectl_bin exec ${cluster}-rs0-0 -n ${namespace} -c backup-agent -- \
  env | grep SSL_CERT_FILE

cert_count=$(kubectl_bin exec ${cluster}-rs0-0 -n ${namespace} -c backup-agent -- \
  grep -c "BEGIN CERTIFICATE" /etc/s3/certs/ca-bundle.crt)

[ "$cert_count" = "1" ]

desc 'Compare StatefulSet'
compare_kubectl "statefulset/${cluster}-rs0"

###############################################################################
# Backup & restore
###############################################################################

wait_for_pbm_operations ${cluster}

run_mongo_tls \
  'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
  "userAdmin:userAdmin123456@${cluster}-rs0.${namespace}"

run_mongo_tls \
  'db.getSiblingDB("myApp").test.insert({ x: 100500 })' \
  "myApp:myPass@${cluster}-rs0.${namespace}"

backup_name_single="backup-minio"
run_backup minio ${backup_name_single} 'logical'
wait_backup "${backup_name_single}"

check_backup_in_storage ${backup_name_single} minio rs0 myApp.test.gz https

run_mongo_tls \
  'db.getSiblingDB("myApp").test.drop()' \
  "myApp:myPass@${cluster}-rs0.${namespace}"

run_restore ${backup_name_single}
wait_restore "${backup_name_single}" "${cluster}"

compare_mongo_cmd "find" "myApp:myPass@${cluster}-rs0.${namespace}" "" "" "myApp" "test" "" "true"

rm -f /tmp/minio-cert.pem /tmp/minio-key.pem

destroy "${namespace}"

desc 'test passed'
