#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
set_debug

run_backup() {
	local name=$1
	local idx=$2
	local type=$3

	desc "run backup $name-$idx"
	cat $test_dir/conf/$name.yml \
		| $sed -e "s/name:/name: $name-$idx/" \
		| $sed -e "s/type:/type: $type/" \
		| kubectl_bin apply -f -

	wait_backup "$name-$idx"

	sleep 5
}

main() {
	create_infra $namespace
	deploy_minio

	desc 'create secrets and start client'
	kubectl_bin apply \
		-f "$conf_dir/secrets.yml" \
		-f "$conf_dir/client.yml" \
		-f $conf_dir/minio-secret.yml

	cluster="some-name"
	desc "create first PSMDB cluster $cluster"
	apply_cluster $test_dir/conf/$cluster-rs0.yml

	desc 'check if all 3 Pods started'
	wait_for_running $cluster-rs0 3
	wait_for_running $cluster-cfg 3 "false"
	sleep 10

	desc "write data"

	write_initial_data
	write_document

	desc "wait for pbm agents to start"

	wait_backup_agent $cluster-rs0-0
	wait_backup_agent $cluster-rs0-1
	wait_backup_agent $cluster-rs0-2
	wait_backup_agent $cluster-rs1-0
	wait_backup_agent $cluster-rs1-1
	wait_backup_agent $cluster-rs1-2
	wait_backup_agent $cluster-rs2-0
	wait_backup_agent $cluster-rs2-1
	wait_backup_agent $cluster-rs2-2

	log "Sleeping for 360 seconds to avoid PBM-1265"
	sleep 360

	backup_name_minio="backup-minio"
	run_backup $backup_name_minio 2 physical

	write_document "-2nd" '130'

	last_write=$(date +%s)
	last_chunk=$(get_latest_oplog_chunk_ts $cluster)

	log "last write: ${last_write}"
	log "last chunk: ${last_chunk}"

	retries=0
	until [[ ${last_chunk} -gt ${last_write} ]]; do
		if [[ $retries -gt 30 ]]; then
			echo "Last oplog chunk ($(format_date ${last_chunk})) is not greater than last write ($(format_date ${last_write}))"
			exit 1
		fi
		last_chunk=$(get_latest_oplog_chunk_ts $cluster)
		retries=$((retries + 1))
		log "Waiting for last oplog chunk ($(format_date ${last_chunk})) to be greater than last write ($(format_date ${last_write}))"
		sleep 10
	done

	sleep 10

	check_recovery $backup_name_minio-2 date "${last_chunk}" "-2nd" "$cluster"

	run_backup $backup_name_minio 3 physical
	compare_latest_restorable_time "${cluster}-rs0" "${backup_name_minio}-3"

	check_recovery $backup_name_minio-3 latest "" "-3rd" "$cluster"

	destroy $namespace
	desc 'test passed'
}

main
