#!/bin/bash

set -o errexit

test_dir=$(realpath "$(dirname "$0")")
. "${test_dir}/../functions"
set_debug

if [ -n "$SKIP_BACKUPS_TO_AWS_GCP_AZURE" ]; then
	desc 'Skip tests related to GCP Cloud Storage'
	exit 0
fi

create_infra "${namespace}"

apply_s3_storage_secrets

desc 'Testing on not sharded cluster'

echo "Creating PSMDB cluster"
cluster="some-name"
kubectl_bin apply -f "${test_dir}/conf/secrets.yml"
apply_cluster "${test_dir}/conf/${cluster}.yml"
kubectl_bin apply -f "${conf_dir}/client_with_tls.yml"

echo 'Check if all pods started'
wait_for_running ${cluster}-rs0 3
wait_cluster_consistency ${cluster}

sleep 60 # give time for resync to start

wait_for_pbm_operations ${cluster}

echo 'Writing test data'
run_mongo \
	'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
	"userAdmin:userAdmin123456@${cluster}-rs0.${namespace}"
sleep 1
run_mongo \
	'use myApp\n db.test.insert({ x: 100500 })' \
	"myApp:myPass@${cluster}-rs0.${namespace}"
sleep 5
compare_mongo_cmd "find" "myApp:myPass@${cluster}-rs0-0.${cluster}-rs0.${namespace}"
compare_mongo_cmd "find" "myApp:myPass@${cluster}-rs0-1.${cluster}-rs0.${namespace}"
compare_mongo_cmd "find" "myApp:myPass@${cluster}-rs0-2.${cluster}-rs0.${namespace}"

echo 'Running GCP backups'
backup_name_gcp="backup-gcp-cs"

run_backup gcp-cs ${backup_name_gcp} 'physical'
wait_backup "${backup_name_gcp}"
check_backup_in_storage ${backup_name_gcp} gcs rs0

echo 'Drop collection'
run_mongo 'use myApp\n db.test.drop()' "myApp:myPass@${cluster}-rs0.${namespace}"
echo 'check backup and restore -- gcp-cs'
run_restore ${backup_name_gcp}
run_recovery_check ${backup_name_gcp}

destroy "$namespace"

desc 'test passed'
