apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: hostpath
spec:
  image:
  replsets:
  - name: rs0
    configuration: |
      security:
        enableEncryption: true
    volumeSpec:
      hostPath:
        path: /run/data-dir
        type: Directory
    size: 3
  secrets:
    users: some-users
