apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: smart-update
spec:
  image:
  imagePullPolicy: Always
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: Disabled
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 0.5G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 2
    configuration: |
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
    arbiter:
      enabled: true
      size: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.3G
        requests:
          cpu: 100m
          memory: 0.1G
      affinity:
        antiAffinityTopologyKey: none
  secrets:
    users: some-users
