#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
cluster="monitoring-rs0"

deploy_cert_manager
create_namespace $namespace
deploy_helm $namespace
deploy_operator

desc 'install PMM Server'
platform=kubernetes
if [ "$OPENSHIFT" == 1 ]; then
    platform=openshift
fi
helm del --purge monitoring || :
retry 10 60 helm install --name monitoring --set platform=$platform https://percona-charts.storage.googleapis.com/pmm-server-2.3.0.tgz

desc 'create PSMDB cluster'
kubectl_bin apply \
    -f $conf_dir/secrets.yml \
    -f $conf_dir/client.yml \
    -f $test_dir/conf/secrets.yml

apply_cluster $test_dir/conf/$cluster.yml
desc 'check if all 3 Pods started'
wait_for_running $cluster 3

# wait for prometheus
sleep 90

desc 'check if pmm-client container enabled'
compare_kubectl statefulset/$cluster
compare_kubectl service/$cluster

desc 'check mongod metrics'
get_metric_values node_boot_time_seconds $cluster-1 admin:admin
get_metric_values mongodb_connections $cluster-1 admin:admin

#desc 'check mongos metrics'
#get_metric_values node_boot_time ${cluster%%-rs0}-mongos-0
#get_metric_values mongodb_mongos_connections ${cluster%%-rs0}-mongos-0

# wait for QAN
sleep 90

desc 'check QAN data'
get_qan20_values $cluster-0 admin:admin

helm delete --purge monitoring
destroy $namespace
