apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: no-requests
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  backup:
    enabled: false
#    storages:
#    tasks:
  replsets:
  - name: rs0
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
    configuration: |
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
  secrets:
    users: some-users
    ssl: some-name-ssl
