#!/bin/bash

set -o errexit

compare() {
	local database="$1"
	local command="$2"
	local uri="$3"
	local target="$4"

	run_mongo "use ${database}\n ${command}" "$uri" "mongodb" \
		| egrep -v 'I NETWORK|W NETWORK|F NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match|Error saving history file:' \
		| $sed -re 's/ObjectId\("[0-9a-f]+"\)//; s/-[0-9]+.svc/-xxxesvc/' \
		| sed '/"userId"/d' \
			>$tmp_dir/${target}

	diff ${test_dir}/compare/${target}.json $tmp_dir/${target}
}

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
set_debug

psmdb="some-name"
cluster="some-name-rs0"

create_infra $namespace

desc 'create secrets and start client'
kubectl_bin apply -f "${conf_dir}/client.yml" \
	-f "${conf_dir}/secrets.yml" \
	-f "${conf_dir}/minio-secret.yml"


desc "create first PSMDB cluster $cluster"
apply_cluster $test_dir/conf/$cluster.yml

desc 'Check if all 3 Pods started'
wait_for_running $cluster 3

desc 'check user created on cluster creation'
kubectl_bin apply -f "${test_dir}/conf/app-user-secrets.yml"
sleep 15

userOne="user-one"
userOnePass=$(getSecretData "user-one" "userOnePassKey")
compare 'admin' 'db.getUser("user-one")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-one"
check_mongo_auth "$userOne:$userOnePass@$cluster-0.$cluster.$namespace"

desc 'delete initial user from CR and create a new one'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-two",
				"db":"admin",
				"passwordSecretRef": {
					"name": "user-two",
					"key": "userTwoPassKey"
				},
				"roles": [
					{"db":"admin","name":"userAdminAnyDatabase"}, 
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3

compare 'admin' 'db.getUser("user-two")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-two"

userTwo="user-two"
userTwoPass=$(getSecretData "user-two" "userTwoPassKey")

# Both users should be in the DB, the operator should not delete the user removed from the CR
check_mongo_auth "$userTwo:$userTwoPass@$cluster-0.$cluster.$namespace"
check_mongo_auth "$userOne:$userOnePass@$cluster-0.$cluster.$namespace"

desc 'check password change'
userTwoNewPass="new-user-two-password"
patch_secret "user-two" "userTwoPassKey" "$(echo -n "$userTwoNewPass" | base64)"
sleep 20

check_mongo_auth "$userTwo:$userTwoNewPass@$cluster-0.$cluster.$namespace"

desc 'check user roles update from CR'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-two",
				"db":"admin",
				"passwordSecretRef": {
					"name": "user-two",
					"key": "userTwoPassKey"
				},
				"roles": [
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3
compare 'admin' 'db.getUser("user-two")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-two-update-roles"

desc 'check user roles update from DB'

run_mongo \
	'use admin\n db.updateUser("user-two", { roles : [{ role : "userAdminAnyDatabase", db: "admin"}]})' \
	"userAdmin:userAdmin123456@$cluster.$namespace"
sleep 15
compare 'admin' 'db.getUser("user-two")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-two-update-roles"

desc 'check user recreated after deleted from DB'
run_mongo \
	'use admin\n db.dropUser("user-two")' \
	"userAdmin:userAdmin123456@$cluster.$namespace"
sleep 15
compare 'admin' 'db.getUser("user-two")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-two-update-roles"

desc 'check new user created after updated user name via CR'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-three",
				"db":"admin",
				"passwordSecretRef": {
					"name": "user-two",
					"key": "userTwoPassKey"
				},
				"roles": [
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3

compare 'admin' 'db.getUser("user-three")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-three-admin-db"
compare 'admin' 'db.getUser("user-two")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-two-update-roles"

# user-three and user-two should be in the DB
check_mongo_auth "$userTwo:$userTwoNewPass@$cluster-0.$cluster.$namespace"
check_mongo_auth "user-three:$userTwoNewPass@$cluster-0.$cluster.$namespace"

desc 'check new user created after updated user db via CR'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"users":[
			{
				"name":"user-three",
				"db":"newDb",
				"passwordSecretRef": {
					"name": "user-two",
					"key": "userTwoPassKey"
				},
				"roles": [
					{"db":"admin","name":"clusterAdmin"}
				]
			}
		]}
	}'
wait_for_running $cluster 3
compare 'newDb' 'db.getUser("user-three")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-three-newDb-db"
compare 'admin' 'db.getUser("user-three")' "userAdmin:userAdmin123456@$cluster.$namespace" "user-three-admin-db"

# ======================== Roles ========================

desc 'check user role on cluster initialization'
compare 'admin' 'db.getRole("role-one", {showPrivileges: true, showAuthenticationRestrictions: true})' "userAdmin:userAdmin123456@$cluster.$namespace" "role-one"

desc 'check role recreated after deleted from DB'
run_mongo \
	'use admin\n db.dropRole("role-one")' \
	"userAdmin:userAdmin123456@$cluster.$namespace"

compare 'admin' 'db.getRole("role-one", {showPrivileges: true, showAuthenticationRestrictions: true})' "userAdmin:userAdmin123456@$cluster.$namespace" "role-one"

desc 'check user role updated from DB'

desc 'delete initial user from CR and create a new one'
kubectl_bin patch psmdb ${psmdb} --type=merge --patch '{
		"spec": {"roles":[
			{
			"role": "role-one",
			"db": "admin",
			"privileges": [
				{
					"resource": {
						"db": "config",
						"collection": ""
					},
					"actions": [
						"find",
					]
				}
			],
			"roles": [
				{
					"role": "read",
					"db": "admin"
				}
			]
			}
		]}
	}'
wait_for_running $cluster 3

compare 'admin' 'db.getRole("role-one", {showPrivileges: true, showAuthenticationRestrictions: true})' "userAdmin:userAdmin123456@$cluster.$namespace" "role-one"
compare 'admin' 'db.getRole("role-two", {showPrivileges: true, showAuthenticationRestrictions: true})' "userAdmin:userAdmin123456@$cluster.$namespace" "role-two"

desc 'check role update from CR'

desc 'check role update from DB'

desc 'check new role created after updated role name via CR'

desc 'check new role created after updated role DB via CR'

desc 'check user with user created role'

destroy $namespace

desc 'test passed'
