#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

if [ $GKE -ne 1 ]; then
	echo "Skip the test. We run it for GKE only"
	exit 0
fi

wait_service_export() {
	retry=0
	sleep 7 # wait for two reconcile loops ;)  3 sec x 2 times + 1 sec = 7 seconds
	echo -n 'waiting for cluster readyness'
	until [[ $(kubectl_bin get serviceexport --all-namespaces | grep -v 'NAME' | wc -l) == 9 ]]; do
		let retry+=1
		if [ $retry -ge 32 ]; then
			echo max retry count $retry reached. Something went wrong with operator or kubernetes cluster. We can not export services.
			exit 1
		fi
		echo -n .
		sleep 10
	done
}

wait_service_import() {
	retry=0
	sleep 7 # wait for two reconcile loops ;)  3 sec x 2 times + 1 sec = 7 seconds
	echo -n 'waiting for cluster readyness'
	until [[ $(kubectl_bin get serviceimport --all-namespaces | grep -v 'NAME' | wc -l) == 9 ]]; do
		let retry+=1
		if [ $retry -ge 32 ]; then
			echo max retry count $retry reached. Something went wrong with operator or kubernetes cluster. We can not import services.
			exit 1
		fi
		echo -n .
		sleep 10
	done
}

desc "add settings to k8s cluster"
k8s_cluster_name=$(kubectl -n default run --quiet curl --rm --restart=Never -it --image=appropriate/curl -- -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/cluster-name)
k8s_cluster_zone='us-central1-a'
gcloud container hub memberships register $k8s_cluster_name --gke-cluster $k8s_cluster_zone/$k8s_cluster_name --enable-workload-identity

create_infra "$namespace"
desc 'create first PSMDB cluster'
cluster="some-name"

kubectl_bin apply \
	-f "$conf_dir/secrets.yml" \
	-f "$conf_dir/client.yml"

apply_s3_storage_secrets
if version_gt "1.19" && [ $EKS -ne 1 ]; then
	cat "$conf_dir/container-rc.yaml" | $sed 's/docker/runc/g' | kubectl_bin apply -f -
else
	kubectl_bin apply -f "$conf_dir/container-rc.yaml"
fi

apply_cluster "$test_dir/conf/$cluster.yml"
desc 'check if all 3 Pods started'
wait_for_running $cluster-rs0 3
wait_for_running $cluster-cfg 3 "false"
wait_for_running $cluster-mongos 3
wait_cluster_consistency "${cluster}" 3

desc "check if exportService and importService objects exist in cluster"
# Uncommnet after https://jira.percona.com/browse/K8SPSMDB-867
#wait_service_export
#wait_service_import
desc "delete memberships"
gcloud container fleet memberships delete $k8s_cluster_name --quiet

destroy $namespace
desc 'test passed'