#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

create_namespace $namespace
deploy_operator
deploy_helm $namespace

kubectl_bin apply -f $conf_dir/secrets.yml -f $conf_dir/client.yml -f $conf_dir/minio-secret.yml
cluster="liveness"

desc 'create first PSMDB cluster'
if [[ "${OPENSHIFT}" == 1 ]]; then
    spinup_psmdb ${cluster}-rs0 $test_dir/conf/${cluster}-rs0-oc.yml
else
    spinup_psmdb ${cluster}-rs0 $test_dir/conf/${cluster}-rs0.yml
fi
compare_kubectl "statefulset/${cluster}-rs0"

desc 'change liveness config'
postfix="-changed"
if [[ "${OPENSHIFT}" == 1 ]]; then
    apply_cluster $test_dir/conf/${cluster}-rs0$postfix-oc.yml
else
    apply_cluster $test_dir/conf/${cluster}-rs0$postfix.yml
fi
sleep 20
wait_for_running "${cluster}-rs0" "3"
compare_kubectl "statefulset/${cluster}-rs0" $postfix
destroy $namespace
