apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: percona-server-mongodb
    percona-server-mongodb_cr: arbiter-clusterip
    replset: rs0
  name: arbiter-clusterip-rs0-arbiter
  ownerReferences:
  - apiVersion: psmdb.percona.com/v1alpha1
    controller: true
    kind: PerconaServerMongoDB
    name: arbiter-clusterip
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: percona-server-mongodb
      percona-server-mongodb_cr: arbiter-clusterip
      replset: rs0
  serviceName: arbiter-clusterip-rs0
  template:
    metadata:
      labels:
        app: percona-server-mongodb
        percona-server-mongodb_cr: arbiter-clusterip
        replset: rs0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: percona-server-mongodb
                  percona-server-mongodb_cr: arbiter-clusterip
                  replset: rs0
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --bind_ip_all
        - --auth
        - --dbpath=/data/db
        - --port=27017
        - --replSet=rs0
        - --storageEngine=wiredTiger
        - --slowms=100
        - --profile=1
        - --rateLimit=1
        - --wiredTigerCacheSizeGB=0.25
        - --wiredTigerCollectionBlockCompressor=snappy
        - --wiredTigerJournalCompressor=snappy
        - --wiredTigerIndexPrefixCompression=true
        - --setParameter
        - ttlMonitorSleepSecs=60
        - --setParameter
        - wiredTigerConcurrentReadTransactions=128
        - --setParameter
        - wiredTigerConcurrentWriteTransactions=128
        env:
        - name: SERVICE_NAME
          value: arbiter-clusterip
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_REPLSET
          value: rs0
        envFrom:
        - secretRef:
            name: some-users
            optional: false
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mongodb-healthcheck
            - k8s
            - liveness
          failureThreshold: 12
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mongod-arbiter
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          failureThreshold: 8
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          tcpSocket:
            port: 27017
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongod-data
        - mountPath: /etc/mongodb-secrets
          name: some-name-intrnl-mongodb-key
          readOnly: true
        workingDir: /data/db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: some-name-intrnl-mongodb-key
        secret:
          defaultMode: 48
          optional: false
          secretName: some-name-intrnl-mongodb-key
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: mongod-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status:
      phase: Pending
