apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app.kubernetes.io/component: mongod
    app.kubernetes.io/instance: arbiter
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: arbiter-rs0-arbiter
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: arbiter
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: arbiter
      app.kubernetes.io/instance: arbiter
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: arbiter-rs0
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: arbiter
        app.kubernetes.io/instance: arbiter
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: arbiter
                  app.kubernetes.io/managed-by: percona-server-mongodb-operator
                  app.kubernetes.io/name: percona-server-mongodb
                  app.kubernetes.io/part-of: percona-server-mongodb
                  app.kubernetes.io/replset: rs0
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=rs0
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --sslMode=preferSSL
            - --clusterAuthMode=x509
            - --slowms=0
            - --profile=1
            - --enableEncryption
            - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
            - --wiredTigerIndexPrefixCompression=true
          command:
            - /data/db/ps-entry.sh
          env:
            - name: SERVICE_NAME
              value: arbiter
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLSET
              value: rs0
          envFrom:
            - secretRef:
                name: internal-arbiter-users
                optional: false
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - mongodb-healthcheck
                - k8s
                - liveness
                - --startupDelaySeconds
                - "7200"
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: mongod-arbiter
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          readinessProbe:
            failureThreshold: 8
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 2
          resources: {}
          securityContext:
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /etc/mongodb-secrets
              name: arbiter-mongodb-keyfile
              readOnly: true
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /etc/mongodb-ssl-internal
              name: ssl-internal
              readOnly: true
            - mountPath: /etc/mongodb-encryption
              name: arbiter-mongodb-encryption-key
              readOnly: true
          workingDir: /data/db
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /init-entrypoint.sh
          imagePullPolicy: Always
          name: mongo-init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: arbiter-mongodb-keyfile
          secret:
            defaultMode: 288
            optional: false
            secretName: arbiter-mongodb-keyfile
        - name: arbiter-mongodb-encryption-key
          secret:
            defaultMode: 288
            optional: false
            secretName: arbiter-mongodb-encryption-key
        - name: ssl
          secret:
            defaultMode: 288
            optional: false
            secretName: arbiter-ssl
        - name: ssl-internal
          secret:
            defaultMode: 288
            optional: true
            secretName: arbiter-ssl-internal
        - emptyDir: {}
          name: mongod-data
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
