apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  labels:
    app.kubernetes.io/component: arbiter
    app.kubernetes.io/instance: smart-update
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: smart-update-rs0-arbiter
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: smart-update
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: arbiter
      app.kubernetes.io/instance: smart-update
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: smart-update-rs0
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: arbiter
        app.kubernetes.io/instance: smart-update
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      containers:
        - args:
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=rs0
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --clusterAuthMode=x509
            - --slowms=100
            - --profile=1
            - --rateLimit=1
            - --enableEncryption
            - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
            - --wiredTigerCacheSizeGB=0.25
            - --wiredTigerCollectionBlockCompressor=snappy
            - --wiredTigerJournalCompressor=snappy
            - --wiredTigerIndexPrefixCompression=true
            - --setParameter
            - ttlMonitorSleepSecs=60
            - --setParameter
            - wiredTigerConcurrentReadTransactions=128
            - --setParameter
            - wiredTigerConcurrentWriteTransactions=128
          command:
            - /data/db/ps-entry.sh
          env:
            - name: SERVICE_NAME
              value: smart-update
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLSET
              value: rs0
          envFrom:
            - secretRef:
                name: internal-smart-update-users
                optional: false
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /data/db/mongodb-healthcheck
                - k8s
                - liveness
                - --ssl
                - --sslInsecure
                - --sslCAFile
                - /etc/mongodb-ssl/ca.crt
                - --sslPEMKeyFile
                - /tmp/tls.pem
                - --startupDelaySeconds
                - "7200"
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: mongod-arbiter
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          readinessProbe:
            failureThreshold: 8
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 300m
              memory: 300M
            requests:
              cpu: 100m
              memory: 100M
          securityContext:
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /etc/mongodb-secrets
              name: smart-update-mongodb-keyfile
              readOnly: true
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /etc/mongodb-ssl-internal
              name: ssl-internal
              readOnly: true
            - mountPath: /etc/mongodb-encryption
              name: smart-update-mongodb-encryption-key
              readOnly: true
            - mountPath: /etc/users-secret
              name: users-secret-file
          workingDir: /data/db
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /init-entrypoint.sh
          imagePullPolicy: Always
          name: mongo-init
          resources:
            limits:
              cpu: 300m
              memory: 300M
            requests:
              cpu: 100m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: smart-update-mongodb-keyfile
          secret:
            defaultMode: 288
            optional: false
            secretName: smart-update-mongodb-keyfile
        - name: smart-update-mongodb-encryption-key
          secret:
            defaultMode: 288
            optional: false
            secretName: smart-update-mongodb-encryption-key
        - name: ssl
          secret:
            defaultMode: 288
            optional: false
            secretName: smart-update-ssl
        - name: ssl-internal
          secret:
            defaultMode: 288
            optional: true
            secretName: smart-update-ssl-internal
        - name: users-secret-file
          secret:
            defaultMode: 420
            secretName: internal-smart-update-users
        - emptyDir: {}
          name: mongod-data
  updateStrategy:
    type: OnDelete
