apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: one-pod
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  allowUnsafeConfigurations: true
  secrets:
    users: some-users
  pmm:
    enabled: false
    image: -pmm
    serverHost: monitoring-service
  replsets:
  - name: rs0
    size: 1
    configuration: |
      systemLog:
        verbosity: 1
      security:
        redactClientLogData: false
        enableEncryption: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          collectionConfig:
            blockCompressor: snappy
          indexConfig:
            prefixCompression: true
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    expose:
      enabled: false
      exposeType: LoadBalancer
    arbiter:
      enabled: false
      size: 1
      affinity:
       antiAffinityTopologyKey: "kubernetes.io/hostname"
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
      requests:
        cpu: "300m"
        memory: "0.5G"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi
  backup:
    enabled: true
    image: perconalab/percona-server-mongodb-operator:9.9.9-backup
    storages:
      minio:
        type: s3
        s3:
          bucket: operator-testing
          credentialsSecret: minio-secret
          region: us-east-1
          endpointUrl: http://minio-service:9000/
          insecureSkipTLSVerify: false
