apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - percona.com/delete-psmdb-pvc
  name: some-name
spec:
  image:
  imagePullPolicy: Always
  updateStrategy: SmartUpdate
  unsafeFlags:
    backupIfUnhealthy: true
  backup:
    enabled: true
    image: perconalab/percona-server-mongodb-operator:1.1.0-backup
    storages:
      minio:
        type: s3
        s3:
          credentialsSecret: minio-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: http://minio-service:9000/
          insecureSkipTLSVerify: false
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi
    expose:
      enabled: false
      type: ClusterIP
    size: 3
    configuration: |
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
  secrets:
    users: some-users
