apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    some-random-annotation: "true"
  generation: 1
  name: some-name-ssl
spec:
  commonName: some-name
  dnsNames:
    - localhost
    - some-name-rs0
    - some-name-rs0.tls-issue-cert-manager-3840
    - some-name-rs0.tls-issue-cert-manager-3840.svc.cluster.local
    - '*.some-name-rs0'
    - '*.some-name-rs0.tls-issue-cert-manager-3840'
    - '*.some-name-rs0.tls-issue-cert-manager-3840.svc.cluster.local'
    - some-name-rs0.tls-issue-cert-manager-3840.svc.clusterset.local
    - '*.some-name-rs0.tls-issue-cert-manager-3840.svc.clusterset.local'
    - '*.tls-issue-cert-manager-3840.svc.clusterset.local'
    - some-name-mongos
    - some-name-mongos.tls-issue-cert-manager-3840
    - some-name-mongos.tls-issue-cert-manager-3840.svc.cluster.local
    - '*.some-name-mongos'
    - '*.some-name-mongos.tls-issue-cert-manager-3840'
    - '*.some-name-mongos.tls-issue-cert-manager-3840.svc.cluster.local'
    - some-name-cfg
    - some-name-cfg.tls-issue-cert-manager-3840
    - some-name-cfg.tls-issue-cert-manager-3840.svc.cluster.local
    - '*.some-name-cfg'
    - '*.some-name-cfg.tls-issue-cert-manager-3840'
    - '*.some-name-cfg.tls-issue-cert-manager-3840.svc.cluster.local'
    - some-name-mongos.tls-issue-cert-manager-3840.svc.clusterset.local
    - '*.some-name-mongos.tls-issue-cert-manager-3840.svc.clusterset.local'
    - some-name-cfg.tls-issue-cert-manager-3840.svc.clusterset.local
    - '*.some-name-cfg.tls-issue-cert-manager-3840.svc.clusterset.local'
  duration: 2160h0m0s
  issuerRef:
    kind: Issuer
    name: some-name-psmdb-issuer
  secretName: some-name-ssl
  subject:
    organizations:
      - CUSTOM
