apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    some-random-annotation: "true"
  generation: 1
  name: some-name-ssl
spec:
  commonName: some-name
  dnsNames:
    - localhost
    - some-name-rs0
    - some-name-rs0.NAME_SPACE
    - some-name-rs0.NAME_SPACE.svc.cluster.local
    - '*.some-name-rs0'
    - '*.some-name-rs0.NAME_SPACE'
    - '*.some-name-rs0.NAME_SPACE.svc.cluster.local'
    - some-name-rs0.NAME_SPACE.svc.clusterset.local
    - '*.some-name-rs0.NAME_SPACE.svc.clusterset.local'
    - '*.NAME_SPACE.svc.clusterset.local'
    - some-name-mongos
    - some-name-mongos.NAME_SPACE
    - some-name-mongos.NAME_SPACE.svc.cluster.local
    - '*.some-name-mongos'
    - '*.some-name-mongos.NAME_SPACE'
    - '*.some-name-mongos.NAME_SPACE.svc.cluster.local'
    - some-name-cfg
    - some-name-cfg.NAME_SPACE
    - some-name-cfg.NAME_SPACE.svc.cluster.local
    - '*.some-name-cfg'
    - '*.some-name-cfg.NAME_SPACE'
    - '*.some-name-cfg.NAME_SPACE.svc.cluster.local'
    - some-name-mongos.NAME_SPACE.svc.clusterset.local
    - '*.some-name-mongos.NAME_SPACE.svc.clusterset.local'
    - some-name-cfg.NAME_SPACE.svc.clusterset.local
    - '*.some-name-cfg.NAME_SPACE.svc.clusterset.local'
  duration: 2160h0m0s
  issuerRef:
    kind: Issuer
    name: some-name-psmdb-issuer
  secretName: some-name-ssl
  subject:
    organizations:
      - CUSTOM
