apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations: {}
  generation: 1
  name: some-name-psmdb-issuer
  labels:
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
  ownerReferences:
    - blockOwnerDeletion: true
      controller: true
      kind: PerconaServerMongoDB
      name: some-name
spec:
  ca:
    secretName: some-name-ca-cert
