apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    some-random-annotation: "true"
  generation: 1
  labels:
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
  name: some-name-psmdb-issuer
spec:
  ca:
    secretName: some-name-ca-cert
