apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations: {}
  generation: 1
  name: some-name-psmdb-issuer
  ownerReferences:
    - blockOwnerDeletion: true
      controller: true
      kind: PerconaServerMongoDB
      name: some-name
spec:
  ca:
    secretName: some-name-ca-cert
