apiVersion: batch/v1
kind: CronJob
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: backup-schedule
    app.kubernetes.io/instance: sec-context
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: general
  name: sec-context-backup-each-hour
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: sec-context
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup-schedule
        app.kubernetes.io/instance: sec-context
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: general
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: backup-schedule
            app.kubernetes.io/instance: sec-context
            app.kubernetes.io/managed-by: percona-server-mongodb-operator
            app.kubernetes.io/name: percona-server-mongodb
            app.kubernetes.io/part-of: percona-server-mongodb
            app.kubernetes.io/replset: general
        spec:
          containers:
            - args:
                - -c
                - "curl \\\n\t\t\t-vvv \\\n\t\t\t-X POST \\\n\t\t\t--cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt \\\n\t\t\t-H \"Content-Type: application/json\" \\\n\t\t\t-H \"Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)\" \\\n\t\t\t--data \"{\\\"kind\\\":\\\"PerconaServerMongoDBBackup\\\",\\\"apiVersion\\\":\\\"psmdb.percona.com/v1\\\",\\\"metadata\\\":{\\\"generateName\\\":\\\"cron-${clusterName:0:16}-$(date -u '+%Y%m%d%H%M%S')-\\\",\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"ancestor\\\":\\\"sec-context-backup-each-hour\\\",\\\"cluster\\\":\\\"${clusterName}\\\",\\\"type\\\":\\\"cron\\\"},\\\"finalizers\\\":[\\\"delete-backup\\\"]},\\\"spec\\\":{\\\"clusterName\\\":\\\"${clusterName}\\\",\\\"storageName\\\":\\\"minio\\\",\\\"compressionType\\\":\\\"gzip\\\"},\\\"status\\\":{}}\" \\\n\t\t\thttps://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/apis/psmdb.percona.com/v1/namespaces/${NAMESPACE}/perconaservermongodbbackups"
              command:
                - sh
              env:
                - name: clusterName
                  value: sec-context
              imagePullPolicy: IfNotPresent
              name: backup
              resources: {}
              securityContext:
                privileged: false
                runAsNonRoot: true
                runAsUser: 1001
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 1001
            supplementalGroups:
              - 1001
              - 1002
              - 1003
          serviceAccount: percona-server-mongodb-operator
          serviceAccountName: percona-server-mongodb-operator
          terminationGracePeriodSeconds: 30
  schedule: 0 */1 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
