apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBRestore
metadata:
  name:
spec:
  clusterName: some-name
  storageName:
  backupSource:
    type: physical
    destination: s3://BACKUP-NAME
    minio:
      credentialsSecret: s3-secret
      region: us-east-1
      bucket: operator-testing
      endpointUrl: s3-storage-all-in-one:8333
      insecureSkipTLSVerify: false
      secure: false
