// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// VersionOperatorVersion OperatorVersion represents operator version.
//
// swagger:model versionOperatorVersion
type VersionOperatorVersion struct {

	// matrix
	Matrix *VersionVersionMatrix `json:"matrix,omitempty"`

	// operator
	Operator string `json:"operator,omitempty"`

	// product
	Product string `json:"product,omitempty"`
}

// Validate validates this version operator version
func (m *VersionOperatorVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMatrix(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VersionOperatorVersion) validateMatrix(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Matrix) { // not required
		return nil
	}

	if m.Matrix != nil {
		if err := m.Matrix.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("matrix")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("matrix")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this version operator version based on the context it is used
func (m *VersionOperatorVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMatrix(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VersionOperatorVersion) contextValidateMatrix(ctx context.Context, formats strfmt.Registry) error {

	if m.Matrix != nil {

		if typeutils.IsZero(m.Matrix) { // not required
			return nil
		}

		if err := m.Matrix.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("matrix")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("matrix")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VersionOperatorVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionOperatorVersion) UnmarshalBinary(b []byte) error {
	var res VersionOperatorVersion
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
