// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// VersionGetReleaseNotesResponse version get release notes response
//
// swagger:model versionGetReleaseNotesResponse
type VersionGetReleaseNotesResponse struct {

	// The product name.
	Product string `json:"product,omitempty"`

	// release_notes is the release note for this version.
	ReleaseNote string `json:"releaseNote,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this version get release notes response
func (m *VersionGetReleaseNotesResponse) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this version get release notes response based on context it is used
func (m *VersionGetReleaseNotesResponse) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VersionGetReleaseNotesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionGetReleaseNotesResponse) UnmarshalBinary(b []byte) error {
	var res VersionGetReleaseNotesResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
