---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: percona-server-mongodb-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - psmdb.percona.com
  resources:
  - mongodbdatabases
  - mongodbusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - psmdb.percona.com
  resources:
  - mongodbdatabases/finalizers
  - mongodbusers/finalizers
  verbs:
  - update
- apiGroups:
  - psmdb.percona.com
  resources:
  - mongodbdatabases/status
  - mongodbusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - psmdb.percona.com
  resources:
  - perconaservermongodbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - psmdb.percona.com
  resources:
  - perconaservermongodbs/status
  verbs:
  - get
