#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath "$(dirname "$0")")
. "${test_dir}/../functions"

function get_lastCommitedOpTime() {
    local cluster_name=$1
    local namespace=$2
    local isSharded=$3

    if [[ ${isSharded} == true ]]; then
        echo $(run_mongos 'db.isMaster().lastCommittedOpTime' "clusterAdmin:clusterAdmin123456@${cluster_name}-rs0-0.${cluster_name}-rs0.${namespace}" "mongodb" "" "--quiet" | egrep -v 'I NETWORK|W NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match')
        return
    else
        echo $(run_mongo 'db.isMaster().lastCommittedOpTime' "clusterAdmin:clusterAdmin123456@${cluster_name}-rs0-0.${cluster_name}-rs0.${namespace}" "mongodb" "" "--quiet" | egrep -v 'I NETWORK|W NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match')
        return
    fi
}

function main() {
    create_namespace $namespace
    deploy_operator

    kubectl_bin apply -f $conf_dir/secrets.yml -f $conf_dir/client.yml
    cluster="some-name"
    CLUSTER_SIZE=3

    desc 'create first PSMDB cluster'
    spinup_psmdb ${cluster}-rs0 $conf_dir/${cluster}-rs0.yml
    compare_kubectl "statefulset/${cluster}-rs0"
    simple_data_check "${cluster}-rs0" ${CLUSTER_SIZE}

    desc 'initiate migration from replicaset to sharded cluster'
    kubectl_bin patch psmdb/${cluster} --type json -p='[{"op":"add","path":"/spec/sharding","value":{"configsvrReplSet":{"size":'${CLUSTER_SIZE}',"volumeSpec":{"persistentVolumeClaim":{"resources":{"requests":{"storage":"3Gi"}}}}},"enabled":true,"mongos":{"size":1}}}]'
    sleep 10
    wait_for_running "${cluster}-rs0" "${CLUSTER_SIZE}" "false"
    wait_for_running "${cluster}-cfg" "${CLUSTER_SIZE}" "false"
    wait_cluster_consistency "${cluster}" "${CLUSTER_SIZE}"
    # Migration to shards wipes out rs users. Let's recreate them
    run_mongos 'db.createUser({user: "myApp", pwd: "myPass", roles: [{ db: "myApp", role: "readWrite" }]})' \
                "userAdmin:userAdmin123456@${cluster}-mongos.${namespace}"

    simple_data_check "${cluster}" "${CLUSTER_SIZE}" 1 "-mongos"

    lastCommitedOpTime=$(get_lastCommitedOpTime ${cluster} ${namespace} "true")
    if [[ -z "${lastCommitedOpTime}" ]]; then
        echo "Sharded cluster does not work properly"
        exit 1
    fi

    desc 'Get back from sharded cluster to replicaset'
    kubectl_bin patch psmdb/${cluster} --type json -p='[{"op":"remove","path":"/spec/sharding"}]'
    sleep 10
    wait_for_running "${cluster}-rs0" "${CLUSTER_SIZE}" "true"

    simple_data_check "${cluster}-rs0" "${CLUSTER_SIZE}"

    lastCommitedOpTime=$(get_lastCommitedOpTime ${cluster} ${namespace})
    if [[ ! -z "${lastCommitedOpTime}" ]]; then
        echo "Replicaset cluster does not work properly"
        exit 1
    fi

    desc 'cleanup'
    kubectl_bin delete -f "${src_dir}/deploy/crd.yaml" || :
    kubectl_bin delete -f "${src_dir}/deploy/rbac.yaml" || :
    kubectl_bin delete pvc --all
    destroy "${namespace}"
}

main
