blank_issues_enabled: true
contact_links:
  - name: Ask a question about Percona Operator for MongoDB or get support
    url: https://forums.percona.com/c/mongodb/percona-kubernetes-operator-for-mongodb/29
    about: Ask a question or request support for using Percona Operator for MongoDB
  - name: Report vulnerability or security concern
    url: https://www.percona.com/security
    about: For any security issues or concerns
