#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

run_recovery_check() {
	local cluster=$1
	local backup1=$2

	desc 'write data after backup'
	run_mongo 'use myApp\n db.test.insert({ x: 100501 })' "myApp:myPass@${cluster}.${namespace}"

	desc 'recover backup'
	compare_mongo_cmd "find" "myApp:myPass@$cluster.$namespace" "-2nd" ".svc.cluster.local" "myApp" "test"
	run_restore "${backup1}"
	wait_restore "${backup1}" "${cluster/-rs0/}"
	compare_mongo_cmd "find" "myApp:myPass@$cluster.$namespace" "" ".svc.cluster.local" "myApp" "test"

	kubectl_bin delete -f "$test_dir/conf/${backup1}.yml"
	wait_for_running "${cluster}" 1
	wait_cluster_consistency "${cluster/-rs0/}"
}

main() {
	create_infra $namespace

	cluster="one-pod-rs0"

	kubectl_bin apply -f "${conf_dir}/client.yml" \
		-f "${conf_dir}/secrets.yml" \
		-f "${conf_dir}/minio-secret.yml"

	deploy_minio

	spinup_psmdb "$cluster" "$test_dir/conf/$cluster.yml" "1"
	compare_kubectl service/$cluster
	compare_kubectl "pvc/mongod-data-one-pod-rs0-0"

	run_mongo \
		'db.serverCmdLineOpts()' \
		"clusterAdmin:clusterAdmin123456@$cluster.$namespace" \
		| egrep -v 'I NETWORK|W NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match|bye' \
		| $sed -re 's/((Timestamp|BinData|NumberLong)\((.+?\)))/{}/g' \
		| jq '.parsed.systemLog' \
			>$tmp_dir/parsed_systemLog.json
	diff $test_dir/compare/serverCmdLineOpts_parsed_systemLog.json $tmp_dir/parsed_systemLog.json

	kubectl_bin apply -f "$test_dir/conf/mongod-secret.yml"
	sleep 50
	compare_kubectl "statefulset/$cluster" "-secret"

	run_mongo \
		'db.serverCmdLineOpts()' \
		"clusterAdmin:clusterAdmin123456@$cluster.$namespace" \
		| egrep -v 'I NETWORK|W NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match|bye' \
		| $sed -re 's/((Timestamp|BinData|NumberLong)\((.+?\)))/{}/g' \
		| jq '.parsed.systemLog' \
			>$tmp_dir/parsed_systemLog_secret.json
	diff $test_dir/compare/serverCmdLineOpts_parsed_systemLog_secret.json $tmp_dir/parsed_systemLog_secret.json

	kubectl_bin apply -f "$test_dir/conf/mongod-secret-2.yml"
	sleep 50

	run_mongo \
		'db.serverCmdLineOpts()' \
		"clusterAdmin:clusterAdmin123456@$cluster.$namespace" \
		| egrep -v 'I NETWORK|W NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match|bye' \
		| $sed -re 's/((Timestamp|BinData|NumberLong)\((.+?\)))/{}/g' \
		| jq '.parsed.systemLog' \
			>$tmp_dir/parsed_systemLog_secret-2.json
	diff $test_dir/compare/serverCmdLineOpts_parsed_systemLog_secret-2.json $tmp_dir/parsed_systemLog_secret-2.json

	run_backup "minio"
	wait_backup "backup-minio"
	run_recovery_check "$cluster" "backup-minio"

	destroy $namespace
}

main
