apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: monitoring-pmm3
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: monitoring-pmm3-rs0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: monitoring-pmm3
spec:
  ports:
    - name: mongodb
      port: 27019
      protocol: TCP
      targetPort: 27019
  selector:
    app.kubernetes.io/instance: monitoring-pmm3
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  sessionAffinity: None
  type: ClusterIP
