apiVersion: v1
kind: Service
metadata:
  annotations:
    test: monitoring-pmm3
  labels:
    app.kubernetes.io/component: mongos
    app.kubernetes.io/instance: monitoring-pmm3
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    test: monitoring-pmm3
  name: monitoring-pmm3-mongos
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: monitoring-pmm3
spec:
  ports:
    - name: mongos
      port: 27019
      protocol: TCP
      targetPort: 27019
  selector:
    app.kubernetes.io/component: mongos
    app.kubernetes.io/instance: monitoring-pmm3
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
  sessionAffinity: None
  type: ClusterIP
