#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath "$(dirname "$0")")
. "${test_dir}/../functions"

create_infra "$namespace"
cluster="some-name"

apply_cluster "$test_dir/conf/$cluster.yml"
desc 'check if all 3 Pods started'
wait_for_running "$cluster-rs0" 3

check_service() {
	replset_name=$1

	local expose_path
	local svc_name
	case $replset_name in

		"rs0")
			expose_path="/spec/replsets/0/expose"
			svc_name="$cluster-rs0-0"
			;;

		"cfg")
			expose_path="/spec/sharding/configsvrReplSet/expose"
			svc_name="$cluster-cfg-0"
			;;

		"mongos")
			expose_path="/spec/sharding/mongos/expose"
			svc_name="$cluster-mongos-0"
			;;

		*)
			desc 'unknown check_service argument'
			exit 1
			;;
	esac

	desc "add labels and annotation manually to service $svc_name"
	# `notIgnoredLabel` and `notIgnoredAnnotation` should be deleted
	kubectl_bin patch "service/$svc_name" --type=json --patch '[
        {
            "op": "add", 
            "path": "/metadata/labels", 
            "value": {
                "notIgnoredLabel": "true",
                "ignoredLabel": "true"
            }
        },
        {
            "op": "add", 
            "path": "/metadata/annotations", 
            "value": {
                "notIgnoredAnnotation": "true",
                "ignoredAnnotation": "true"
            }
        }]'

	sleep 5 # waiting for reconcile
	desc "check if annotations/labels are not deleted from service $svc_name"
	compare_kubectl "service/$svc_name" "-manual"

	desc "adding ignoreAnnotations and ignoreLabels"
	kubectl_bin patch psmdb "$cluster" --type=json --patch '[
        {
            "op": "add",
            "path": "/spec/ignoreAnnotations",
            "value": ["ignoredAnnotation"]
        },
        {
            "op": "add",
            "path": "/spec/ignoreLabels",
            "value": ["ignoredLabel"]
        }
    ]'
	sleep 5
	desc "check if annotations/labels are not deleted from service $svc_name"
	compare_kubectl "service/$svc_name" "-manual"

	desc "adding serviceLabels and serviceAnnotations to $expose_path"
	kubectl_bin patch psmdb ${cluster} --type=json --patch '[
        {
            "op": "replace", 
            "path": "'$expose_path'/serviceLabels", 
			"value": {
				"crLabel": "true",
			}
        },
        {
            "op": "replace", 
            "path": "'$expose_path'/serviceAnnotations", 
			"value": {
				"crAnnotation": "true",
			}
        }]'
	sleep 5
	desc "check if not ignored labels and annotations are deleted from service $svc_name"
	compare_kubectl "service/$svc_name" "-crmeta"

	desc "removing serviceLabels and serviceAnnotations from $expose_path"
	kubectl_bin patch psmdb ${cluster} --type=json --patch '[
        {
            "op": "remove", 
            "path": "'$expose_path'/serviceLabels"
        },
        {
            "op": "remove", 
            "path": "'$expose_path'/serviceAnnotations"
        }]'
	sleep 5
	desc "check if labels and annotations are not deleted from service $svc_name"
	compare_kubectl "service/$svc_name" "-crmeta"

	desc "adding other serviceLabels and serviceAnnotations to $expose_path"
	kubectl_bin patch psmdb ${cluster} --type=json --patch '[
        {
            "op": "replace", 
            "path": "'$expose_path'/serviceLabels", 
			"value": {
				"otherCrLabel": "true",
				"secondCrLabel": "true",
			}
        },
		{
            "op": "replace", 
            "path": "'$expose_path'/serviceAnnotations", 
			"value": {
				"otherCrAnnotation": "true",
				"secondCrAnnotation": "true",
			}
		}]'
	sleep 5
	desc "check if not previous service labels and annotations is deleted from $svc_name"
	compare_kubectl "service/$svc_name" "-two-service-labels-annotations"

	desc "adding removing one serviceLabels from $expose_path"
	kubectl_bin patch psmdb ${cluster} --type=json --patch '[
        {
            "op": "replace", 
            "path": "'$expose_path'/serviceLabels", 
			"value": {
				"otherCrLabel": "true",
			}
        },
        {
            "op": "replace", 
            "path": "'$expose_path'/serviceAnnotations", 
			"value": {
				"otherCrAnnotation": "true",
			}
        }]'
	sleep 5
	desc "check if removed service label is deleted from $svc_name"
	compare_kubectl "service/$svc_name" "-one-service-label-annotation"

	desc "removing ignoreLabels and ignoreAnnotations"
	# When `serviceLabels` and `serviceAnnotations` are not set, old metadata should stay
	kubectl_bin patch psmdb ${cluster} --type=json --patch '[
        {
            "op": "remove", 
            "path": "/spec/ignoreAnnotations",
        },
        {
            "op": "remove", 
            "path": "/spec/ignoreLabels",
        }]'

	sleep 5 # waiting for reconcile
	desc "check if ignored labels and annotations are deleted from $svc_name"
	compare_kubectl "service/$svc_name" "-no-ignored-meta"
}

check_service "rs0"
check_service "cfg"
check_service "mongos"

destroy "$namespace"
