#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath "$(dirname "$0")")
. "${test_dir}/../functions"

create_infra "$namespace"
cluster="some-name"

apply_cluster "$test_dir/conf/$cluster.yml"
desc 'check if all 3 Pods started'
wait_for_running "$cluster-rs0" 3

desc 'add labels and annotation manually'
# `notIgnoredLabel` and `notIgnoredAnnotation` should be deleted
kubectl_bin patch "service/$cluster-rs0-0" --type=json --patch '[
    {
        "op": "add", 
        "path": "/metadata/labels", 
        "value": {
            "notIgnoredLabel": "true",
            "ignoredLabel": "true"
        }
    },
    {
        "op": "add", 
        "path": "/metadata/annotations", 
        "value": {
            "notIgnoredAnnotation": "true",
            "ignoredAnnotation": "true"
        }
    }]'

sleep 5 # waiting for reconcile
desc 'check if not ignored annotations/labels are deleted from service'
compare_kubectl "service/$cluster-rs0-0"

desc 'removing ignoreLabels'
# `ignoredLabel` should be deleted
kubectl_bin patch psmdb ${cluster} --type=json --patch '[
    {
        "op": "remove", 
        "path": "/spec/ignoreLabels",
    }]'

sleep 5 # waiting for reconcile
compare_kubectl "service/$cluster-rs0-0" "-no-ignored-labels"

desc 'removing serviceLabels and ignoreAnnotations'
# When `serviceLabels` and `serviceAnnotations` are not set, old metadata should stay
kubectl_bin patch psmdb ${cluster} --type=json --patch '[
    {
        "op": "remove", 
        "path": "/spec/replsets/0/expose/serviceLabels", 
    },
    {
        "op": "remove", 
        "path": "/spec/ignoreAnnotations",
    }]'

sleep 5 # waiting for reconcile
compare_kubectl "service/$cluster-rs0-0" "-no-ignored-labels"

desc 'adding serviceAnnotation'
# Old metadata should be deleted
kubectl_bin patch psmdb ${cluster} --type=json --patch '[
    {
        "op": "add", 
        "path": "/spec/replsets/0/expose/serviceAnnotations", 
        "value": {
            "crAnnotation": "true",
        }
    }]'

sleep 5 # waiting for reconcile
compare_kubectl "service/$cluster-rs0-0" "-cr-annotation"

destroy "$namespace"
