#!/bin/sh

#DEBHELPER#
chown mongod:mongod /etc/pbm-storage.conf
cat << EOF
** Join Percona Squad! **

Participate in monthly SWAG raffles, get early access to new product features,
invite-only ”ask me anything” sessions with database performance experts.

Interested? Fill in the form at https://squad.percona.com/mongodb

EOF

exit 0
