apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: unsafe-psa
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  enableVolumeExpansion: true
  unsafeFlags:
    replsetSize: true
  secrets:
    users: some-users
  pmm:
    enabled: false
  replsets:
  - name: rs0
    size: 2
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    expose:
      enabled: false
    arbiter:
      enabled: true
      size: 1
      affinity:
       antiAffinityTopologyKey: "kubernetes.io/hostname"
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
      requests:
        cpu: "300m"
        memory: "0.5G"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
  backup:
    enabled: true
    image: perconalab/percona-server-mongodb-operator:9.9.9-backup
    storages:
      minio:
        type: s3
        s3:
          bucket: operator-testing
          credentialsSecret: minio-secret
          region: us-east-1
          endpointUrl: http://minio-service:9000/
          insecureSkipTLSVerify: false
