apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always

  roles:
  - role: role-one
    db: admin
    privileges:
      - resource:
          cluster: true
        actions:
          - addShard
      - resource:
          db: config
          collection: ''
        actions:
          - find
          - update
          - insert
          - remove
    roles:
      - role: read
        db: admin
    authenticationRestrictions:
      - clientSource:
          - 127.0.0.1
        serverAddress:
          - 127.0.0.1

  users:
  - name: user-one
    db: admin
    passwordSecretRef: 
      name: user-one
      key: userOnePassKey
    roles:
      - name: clusterAdmin
        db: admin
      - name: userAdminAnyDatabase
        db: admin
  - name: user-gen
    db: admin
    roles:
      - name: clusterAdmin
        db: admin
      - name: userAdminAnyDatabase
        db: admin
  - name: user-external
    db: $external
    roles:
      - name: clusterAdmin
        db: admin
      - name: userAdminAnyDatabase
        db: admin

  backup:
    enabled: false
    image: perconalab/percona-server-mongodb-operator:1.1.0-backup
    storages:
      aws-s3:
        type: s3
        s3:
          credentialsSecret: aws-s3-secret
          region: us-east-1
          bucket: operator-testing
          prefix: psmdb-demand-backup-sharded
          insecureSkipTLSVerify: false
      minio:
        type: s3
        s3:
          credentialsSecret: minio-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: http://minio-service:9000/
          insecureSkipTLSVerify: false
      gcp-cs:
        type: s3
        s3:
          credentialsSecret: gcp-cs-secret
          region: us-east-1
          bucket: operator-testing
          prefix: psmdb-demand-backup-sharded
          endpointUrl: https://storage.googleapis.com
          insecureSkipTLSVerify: false
      azure-blob:
        type: azure
        azure:
          container: operator-testing
          prefix: psmdb-demand-backup-sharded
          credentialsSecret: azure-secret

    tasks:
    - name: weekly
      enabled: true
      schedule: "0 0 * * 0"
      compressionType: gzip
      storageName: aws-s3
    runtimeClassName: container-rc
  sharding:
    enabled: true

    configsvrReplSet:
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
      expose:
        enabled: false
        exposeType: ClusterIP
      sidecars:
      - image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo echo $(date -u) 'test' >> /dev/null; sleep 5;done"]
        name: cfg-sidecar-1
      runtimeClassName: container-rc

    mongos:
      size: 3
      configuration: |
        replication:
          localPingThresholdMs: 15
      expose:
        exposeType: ClusterIP
      sidecars:
      - image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo echo $(date -u) 'test' >> /dev/null; sleep 5;done"]
        name: mongos-sidecar-1
      runtimeClassName: container-rc
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    expose:
      enabled: false
      exposeType: ClusterIP
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    runtimeClassName: container-rc
    size: 3
    configuration: |
      net:
        port: 27017
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
    sidecars:
    - image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo echo $(date -u) 'test' >> /dev/null; sleep 5;done"]
      name: rs-sidecar-1
  secrets:
    users: some-users
