apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: arbiter-clusterip
spec:
  #platform: openshift
  image:
  replsets:
  - name: rs0
    configuration: |
      security:
        enableEncryption: true
    affinity:
      antiAffinityTopologyKey: none
    arbiter:
      enabled: true
      size: 1
    expose:
      enabled: true
      exposeType: ClusterIP
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 2
  secrets:
    users: some-users
