// Code generated by go-swagger; DO NOT EDIT.

package version_service

import (
	"context"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new version service API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new version service API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new version service API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for version service API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// VersionServiceApply specific version.
	VersionServiceApply(params *VersionServiceApplyParams, opts ...ClientOption) (*VersionServiceApplyOK, error)

	// VersionServiceApplyContext specific version.
	VersionServiceApplyContext(ctx context.Context, params *VersionServiceApplyParams, opts ...ClientOption) (*VersionServiceApplyOK, error)

	// VersionServiceGetReleaseNotes gets the release notes for a product version.
	VersionServiceGetReleaseNotes(params *VersionServiceGetReleaseNotesParams, opts ...ClientOption) (*VersionServiceGetReleaseNotesOK, error)

	// VersionServiceGetReleaseNotesContext gets the release notes for a product version.
	VersionServiceGetReleaseNotesContext(ctx context.Context, params *VersionServiceGetReleaseNotesParams, opts ...ClientOption) (*VersionServiceGetReleaseNotesOK, error)

	// VersionServiceMetadata metadata for a product.
	VersionServiceMetadata(params *VersionServiceMetadataParams, opts ...ClientOption) (*VersionServiceMetadataOK, error)

	// VersionServiceMetadataContext metadata for a product.
	VersionServiceMetadataContext(ctx context.Context, params *VersionServiceMetadataParams, opts ...ClientOption) (*VersionServiceMetadataOK, error)

	// VersionServiceMetadataV2 v2 metadata for a product.
	VersionServiceMetadataV2(params *VersionServiceMetadataV2Params, opts ...ClientOption) (*VersionServiceMetadataV2OK, error)

	// VersionServiceMetadataV2Context v2 metadata for a product.
	VersionServiceMetadataV2Context(ctx context.Context, params *VersionServiceMetadataV2Params, opts ...ClientOption) (*VersionServiceMetadataV2OK, error)

	// VersionServiceOperator product versions for specific operator version.
	VersionServiceOperator(params *VersionServiceOperatorParams, opts ...ClientOption) (*VersionServiceOperatorOK, error)

	// VersionServiceOperatorContext product versions for specific operator version.
	VersionServiceOperatorContext(ctx context.Context, params *VersionServiceOperatorParams, opts ...ClientOption) (*VersionServiceOperatorOK, error)

	// VersionServiceProduct product versions for all operator version.
	VersionServiceProduct(params *VersionServiceProductParams, opts ...ClientOption) (*VersionServiceProductOK, error)

	// VersionServiceProductContext product versions for all operator version.
	VersionServiceProductContext(ctx context.Context, params *VersionServiceProductParams, opts ...ClientOption) (*VersionServiceProductOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// VersionServiceApply specifics version.
//
// Return specific product version.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.VersionServiceApplyContext] instead.
func (a *Client) VersionServiceApply(params *VersionServiceApplyParams, opts ...ClientOption) (*VersionServiceApplyOK, error) {
	var ctx context.Context
	if params != nil && params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.VersionServiceApplyContext(ctx, params, opts...)
}

// VersionServiceApplyContext specifics version.
//
// Return specific product version.
//
// Do not use the deprecated [VersionServiceApplyParams.Context] with this method: it would be ignored.
func (a *Client) VersionServiceApplyContext(ctx context.Context, params *VersionServiceApplyParams, opts ...ClientOption) (*VersionServiceApplyOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewVersionServiceApplyParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "VersionService_Apply",
		Method:             "GET",
		PathPattern:        "/versions/v1/{product}/{operatorVersion}/{apply}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &VersionServiceApplyReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*VersionServiceApplyOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*VersionServiceApplyDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// VersionServiceGetReleaseNotes gets the release notes for a product version.
//
// Return release notes for a product version.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.VersionServiceGetReleaseNotesContext] instead.
func (a *Client) VersionServiceGetReleaseNotes(params *VersionServiceGetReleaseNotesParams, opts ...ClientOption) (*VersionServiceGetReleaseNotesOK, error) {
	var ctx context.Context
	if params != nil && params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.VersionServiceGetReleaseNotesContext(ctx, params, opts...)
}

// VersionServiceGetReleaseNotesContext gets the release notes for a product version.
//
// Return release notes for a product version.
//
// Do not use the deprecated [VersionServiceGetReleaseNotesParams.Context] with this method: it would be ignored.
func (a *Client) VersionServiceGetReleaseNotesContext(ctx context.Context, params *VersionServiceGetReleaseNotesParams, opts ...ClientOption) (*VersionServiceGetReleaseNotesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewVersionServiceGetReleaseNotesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "VersionService_GetReleaseNotes",
		Method:             "GET",
		PathPattern:        "/release-notes/v1/{product}/{version}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &VersionServiceGetReleaseNotesReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*VersionServiceGetReleaseNotesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*VersionServiceGetReleaseNotesDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// VersionServiceMetadata metadata for a product.
//
// Return metadata information for a product.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.VersionServiceMetadataContext] instead.
func (a *Client) VersionServiceMetadata(params *VersionServiceMetadataParams, opts ...ClientOption) (*VersionServiceMetadataOK, error) {
	var ctx context.Context
	if params != nil && params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.VersionServiceMetadataContext(ctx, params, opts...)
}

// VersionServiceMetadataContext metadata for a product.
//
// Return metadata information for a product.
//
// Do not use the deprecated [VersionServiceMetadataParams.Context] with this method: it would be ignored.
func (a *Client) VersionServiceMetadataContext(ctx context.Context, params *VersionServiceMetadataParams, opts ...ClientOption) (*VersionServiceMetadataOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewVersionServiceMetadataParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "VersionService_Metadata",
		Method:             "GET",
		PathPattern:        "/metadata/v1/{product}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &VersionServiceMetadataReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*VersionServiceMetadataOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*VersionServiceMetadataDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// VersionServiceMetadataV2 v2s metadata for a product.
//
// Return metadata information with additional image information for a product.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.VersionServiceMetadataV2Context] instead.
func (a *Client) VersionServiceMetadataV2(params *VersionServiceMetadataV2Params, opts ...ClientOption) (*VersionServiceMetadataV2OK, error) {
	var ctx context.Context
	if params != nil && params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.VersionServiceMetadataV2Context(ctx, params, opts...)
}

// VersionServiceMetadataV2Context v2s metadata for a product.
//
// Return metadata information with additional image information for a product.
//
// Do not use the deprecated [VersionServiceMetadataV2Params.Context] with this method: it would be ignored.
func (a *Client) VersionServiceMetadataV2Context(ctx context.Context, params *VersionServiceMetadataV2Params, opts ...ClientOption) (*VersionServiceMetadataV2OK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewVersionServiceMetadataV2Params()
	}

	op := &runtime.ClientOperation{
		ID:                 "VersionService_MetadataV2",
		Method:             "GET",
		PathPattern:        "/metadata/v2/{product}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &VersionServiceMetadataV2Reader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*VersionServiceMetadataV2OK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*VersionServiceMetadataV2Default)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// VersionServiceOperator products versions for specific operator version.
//
// Return product versions for specific operator.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.VersionServiceOperatorContext] instead.
func (a *Client) VersionServiceOperator(params *VersionServiceOperatorParams, opts ...ClientOption) (*VersionServiceOperatorOK, error) {
	var ctx context.Context
	if params != nil && params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.VersionServiceOperatorContext(ctx, params, opts...)
}

// VersionServiceOperatorContext products versions for specific operator version.
//
// Return product versions for specific operator.
//
// Do not use the deprecated [VersionServiceOperatorParams.Context] with this method: it would be ignored.
func (a *Client) VersionServiceOperatorContext(ctx context.Context, params *VersionServiceOperatorParams, opts ...ClientOption) (*VersionServiceOperatorOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewVersionServiceOperatorParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "VersionService_Operator",
		Method:             "GET",
		PathPattern:        "/versions/v1/{product}/{operatorVersion}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &VersionServiceOperatorReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*VersionServiceOperatorOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*VersionServiceOperatorDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// VersionServiceProduct products versions for all operator version.
//
// Return product versions for all operator.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.VersionServiceProductContext] instead.
func (a *Client) VersionServiceProduct(params *VersionServiceProductParams, opts ...ClientOption) (*VersionServiceProductOK, error) {
	var ctx context.Context
	if params != nil && params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.VersionServiceProductContext(ctx, params, opts...)
}

// VersionServiceProductContext products versions for all operator version.
//
// Return product versions for all operator.
//
// Do not use the deprecated [VersionServiceProductParams.Context] with this method: it would be ignored.
func (a *Client) VersionServiceProductContext(ctx context.Context, params *VersionServiceProductParams, opts ...ClientOption) (*VersionServiceProductOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewVersionServiceProductParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "VersionService_Product",
		Method:             "GET",
		PathPattern:        "/versions/v1/{product}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &VersionServiceProductReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*VersionServiceProductOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*VersionServiceProductDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [VersionServiceParams].
	ctx context.Context
}
