// Code generated by go-swagger; DO NOT EDIT.

package version_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVersionServiceMetadataParams creates a new VersionServiceMetadataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVersionServiceMetadataParams() *VersionServiceMetadataParams {
	return NewVersionServiceMetadataParamsWithTimeout(cr.DefaultTimeout)
}

// NewVersionServiceMetadataParamsWithTimeout creates a new VersionServiceMetadataParams object
// with the ability to set a timeout on a request.
func NewVersionServiceMetadataParamsWithTimeout(timeout time.Duration) *VersionServiceMetadataParams {
	return &VersionServiceMetadataParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewVersionServiceMetadataParamsWithContext creates a new VersionServiceMetadataParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [VersionServiceMetadataParams].
func NewVersionServiceMetadataParamsWithContext(ctx context.Context) *VersionServiceMetadataParams {
	return &VersionServiceMetadataParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewVersionServiceMetadataParamsWithHTTPClient creates a new VersionServiceMetadataParams object
// with the ability to set a custom HTTPClient for a request.
func NewVersionServiceMetadataParamsWithHTTPClient(client *http.Client) *VersionServiceMetadataParams {
	return &VersionServiceMetadataParams{
		HTTPClient: client,
	}
}

/*
VersionServiceMetadataParams contains all the parameters to send to the API endpoint

	for the version service metadata operation.

	Typically these are written to a http.Request.
*/
type VersionServiceMetadataParams struct {

	// Product.
	Product string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the version service metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VersionServiceMetadataParams) WithDefaults() *VersionServiceMetadataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the version service metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VersionServiceMetadataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the version service metadata params.
func (o *VersionServiceMetadataParams) WithTimeout(timeout time.Duration) *VersionServiceMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the version service metadata params.
func (o *VersionServiceMetadataParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the version service metadata params.
//
// Deprecated: use the operation call with context to pass the context instead of [VersionServiceMetadataParams].
func (o *VersionServiceMetadataParams) WithContext(ctx context.Context) *VersionServiceMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the version service metadata params.
//
// Deprecated: use the operation call with context to pass the context instead of [VersionServiceMetadataParams].
func (o *VersionServiceMetadataParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the version service metadata params.
func (o *VersionServiceMetadataParams) WithHTTPClient(client *http.Client) *VersionServiceMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the version service metadata params.
func (o *VersionServiceMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProduct adds the product to the version service metadata params.
func (o *VersionServiceMetadataParams) WithProduct(product string) *VersionServiceMetadataParams {
	o.SetProduct(product)
	return o
}

// SetProduct adds the product to the version service metadata params.
func (o *VersionServiceMetadataParams) SetProduct(product string) {
	o.Product = product
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *VersionServiceMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param product
	if err := r.SetPathParam("product", o.Product); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
