// Code generated by go-swagger; DO NOT EDIT.

package version_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewVersionServiceApplyParams creates a new VersionServiceApplyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVersionServiceApplyParams() *VersionServiceApplyParams {
	return NewVersionServiceApplyParamsWithTimeout(cr.DefaultTimeout)
}

// NewVersionServiceApplyParamsWithTimeout creates a new VersionServiceApplyParams object
// with the ability to set a timeout on a request.
func NewVersionServiceApplyParamsWithTimeout(timeout time.Duration) *VersionServiceApplyParams {
	return &VersionServiceApplyParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewVersionServiceApplyParamsWithContext creates a new VersionServiceApplyParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [VersionServiceApplyParams].
func NewVersionServiceApplyParamsWithContext(ctx context.Context) *VersionServiceApplyParams {
	return &VersionServiceApplyParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewVersionServiceApplyParamsWithHTTPClient creates a new VersionServiceApplyParams object
// with the ability to set a custom HTTPClient for a request.
func NewVersionServiceApplyParamsWithHTTPClient(client *http.Client) *VersionServiceApplyParams {
	return &VersionServiceApplyParams{
		HTTPClient: client,
	}
}

/*
VersionServiceApplyParams contains all the parameters to send to the API endpoint

	for the version service apply operation.

	Typically these are written to a http.Request.
*/
type VersionServiceApplyParams struct {

	// AlibabaBackupEnabled.
	AlibabaBackupEnabled *bool

	// Apply.
	Apply string

	// ArbiterEnabled.
	ArbiterEnabled *bool

	// BackupVersion.
	BackupVersion *string

	// BackupsEnabled.
	BackupsEnabled *bool

	// ClusterSize.
	//
	// Format: int32
	ClusterSize *int32

	// ClusterSyncEnabled.
	ClusterSyncEnabled *bool

	// ClusterWideEnabled.
	ClusterWideEnabled *bool

	// CustomResourceUID.
	CustomResourceUID *string

	// DatabaseVersion.
	DatabaseVersion *string

	// Distribution.
	//
	// PostgreSQL distribution running in the cluster. Empty string means unknown (e.g. no running pods yet).
	Distribution *string

	// EncryptionEnabled.
	EncryptionEnabled *bool

	// Extensions.
	Extensions *string

	// HaproxyVersion.
	HaproxyVersion *string

	// HashicorpVaultEnabled.
	HashicorpVaultEnabled *bool

	// HelmDeployCr.
	HelmDeployCr *bool

	// HelmDeployOperator.
	HelmDeployOperator *bool

	// KubeVersion.
	KubeVersion *string

	// LogCollectorVersion.
	LogCollectorVersion *string

	// McsEnabled.
	McsEnabled *bool

	// MongoTLSMode.
	//
	// MongoDB TLS mode configured in the cluster. Empty string means unknown.
	MongoTLSMode *string

	// MongosSize.
	//
	// Format: int32
	MongosSize *int32

	// NamespaceUID.
	NamespaceUID *string

	// NonVotingEnabled.
	NonVotingEnabled *bool

	// OciBackupEnabled.
	OciBackupEnabled *bool

	// OperatorVersion.
	OperatorVersion string

	// PhysicalBackupScheduled.
	PhysicalBackupScheduled *bool

	// PitrEnabled.
	PitrEnabled *bool

	// Platform.
	Platform *string

	// PmmEnabled.
	PmmEnabled *bool

	// PmmVersion.
	PmmVersion *string

	// Product.
	Product string

	// ProxysqlVersion.
	ProxysqlVersion *string

	// RoleManagementEnabled.
	RoleManagementEnabled *bool

	// ShardingEnabled.
	ShardingEnabled *bool

	// SidecarsUsed.
	SidecarsUsed *bool

	// UserManagementEnabled.
	UserManagementEnabled *bool

	// VectorSearchEnabled.
	VectorSearchEnabled *bool

	// VolumeExpansionEnabled.
	VolumeExpansionEnabled *bool

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the version service apply params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VersionServiceApplyParams) WithDefaults() *VersionServiceApplyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the version service apply params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VersionServiceApplyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the version service apply params.
func (o *VersionServiceApplyParams) WithTimeout(timeout time.Duration) *VersionServiceApplyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the version service apply params.
func (o *VersionServiceApplyParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the version service apply params.
//
// Deprecated: use the operation call with context to pass the context instead of [VersionServiceApplyParams].
func (o *VersionServiceApplyParams) WithContext(ctx context.Context) *VersionServiceApplyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the version service apply params.
//
// Deprecated: use the operation call with context to pass the context instead of [VersionServiceApplyParams].
func (o *VersionServiceApplyParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the version service apply params.
func (o *VersionServiceApplyParams) WithHTTPClient(client *http.Client) *VersionServiceApplyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the version service apply params.
func (o *VersionServiceApplyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlibabaBackupEnabled adds the alibabaBackupEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithAlibabaBackupEnabled(alibabaBackupEnabled *bool) *VersionServiceApplyParams {
	o.SetAlibabaBackupEnabled(alibabaBackupEnabled)
	return o
}

// SetAlibabaBackupEnabled adds the alibabaBackupEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetAlibabaBackupEnabled(alibabaBackupEnabled *bool) {
	o.AlibabaBackupEnabled = alibabaBackupEnabled
}

// WithApply adds the apply to the version service apply params.
func (o *VersionServiceApplyParams) WithApply(apply string) *VersionServiceApplyParams {
	o.SetApply(apply)
	return o
}

// SetApply adds the apply to the version service apply params.
func (o *VersionServiceApplyParams) SetApply(apply string) {
	o.Apply = apply
}

// WithArbiterEnabled adds the arbiterEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithArbiterEnabled(arbiterEnabled *bool) *VersionServiceApplyParams {
	o.SetArbiterEnabled(arbiterEnabled)
	return o
}

// SetArbiterEnabled adds the arbiterEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetArbiterEnabled(arbiterEnabled *bool) {
	o.ArbiterEnabled = arbiterEnabled
}

// WithBackupVersion adds the backupVersion to the version service apply params.
func (o *VersionServiceApplyParams) WithBackupVersion(backupVersion *string) *VersionServiceApplyParams {
	o.SetBackupVersion(backupVersion)
	return o
}

// SetBackupVersion adds the backupVersion to the version service apply params.
func (o *VersionServiceApplyParams) SetBackupVersion(backupVersion *string) {
	o.BackupVersion = backupVersion
}

// WithBackupsEnabled adds the backupsEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithBackupsEnabled(backupsEnabled *bool) *VersionServiceApplyParams {
	o.SetBackupsEnabled(backupsEnabled)
	return o
}

// SetBackupsEnabled adds the backupsEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetBackupsEnabled(backupsEnabled *bool) {
	o.BackupsEnabled = backupsEnabled
}

// WithClusterSize adds the clusterSize to the version service apply params.
func (o *VersionServiceApplyParams) WithClusterSize(clusterSize *int32) *VersionServiceApplyParams {
	o.SetClusterSize(clusterSize)
	return o
}

// SetClusterSize adds the clusterSize to the version service apply params.
func (o *VersionServiceApplyParams) SetClusterSize(clusterSize *int32) {
	o.ClusterSize = clusterSize
}

// WithClusterSyncEnabled adds the clusterSyncEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithClusterSyncEnabled(clusterSyncEnabled *bool) *VersionServiceApplyParams {
	o.SetClusterSyncEnabled(clusterSyncEnabled)
	return o
}

// SetClusterSyncEnabled adds the clusterSyncEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetClusterSyncEnabled(clusterSyncEnabled *bool) {
	o.ClusterSyncEnabled = clusterSyncEnabled
}

// WithClusterWideEnabled adds the clusterWideEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithClusterWideEnabled(clusterWideEnabled *bool) *VersionServiceApplyParams {
	o.SetClusterWideEnabled(clusterWideEnabled)
	return o
}

// SetClusterWideEnabled adds the clusterWideEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetClusterWideEnabled(clusterWideEnabled *bool) {
	o.ClusterWideEnabled = clusterWideEnabled
}

// WithCustomResourceUID adds the customResourceUID to the version service apply params.
func (o *VersionServiceApplyParams) WithCustomResourceUID(customResourceUID *string) *VersionServiceApplyParams {
	o.SetCustomResourceUID(customResourceUID)
	return o
}

// SetCustomResourceUID adds the customResourceUid to the version service apply params.
func (o *VersionServiceApplyParams) SetCustomResourceUID(customResourceUID *string) {
	o.CustomResourceUID = customResourceUID
}

// WithDatabaseVersion adds the databaseVersion to the version service apply params.
func (o *VersionServiceApplyParams) WithDatabaseVersion(databaseVersion *string) *VersionServiceApplyParams {
	o.SetDatabaseVersion(databaseVersion)
	return o
}

// SetDatabaseVersion adds the databaseVersion to the version service apply params.
func (o *VersionServiceApplyParams) SetDatabaseVersion(databaseVersion *string) {
	o.DatabaseVersion = databaseVersion
}

// WithDistribution adds the distribution to the version service apply params.
func (o *VersionServiceApplyParams) WithDistribution(distribution *string) *VersionServiceApplyParams {
	o.SetDistribution(distribution)
	return o
}

// SetDistribution adds the distribution to the version service apply params.
func (o *VersionServiceApplyParams) SetDistribution(distribution *string) {
	o.Distribution = distribution
}

// WithEncryptionEnabled adds the encryptionEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithEncryptionEnabled(encryptionEnabled *bool) *VersionServiceApplyParams {
	o.SetEncryptionEnabled(encryptionEnabled)
	return o
}

// SetEncryptionEnabled adds the encryptionEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetEncryptionEnabled(encryptionEnabled *bool) {
	o.EncryptionEnabled = encryptionEnabled
}

// WithExtensions adds the extensions to the version service apply params.
func (o *VersionServiceApplyParams) WithExtensions(extensions *string) *VersionServiceApplyParams {
	o.SetExtensions(extensions)
	return o
}

// SetExtensions adds the extensions to the version service apply params.
func (o *VersionServiceApplyParams) SetExtensions(extensions *string) {
	o.Extensions = extensions
}

// WithHaproxyVersion adds the haproxyVersion to the version service apply params.
func (o *VersionServiceApplyParams) WithHaproxyVersion(haproxyVersion *string) *VersionServiceApplyParams {
	o.SetHaproxyVersion(haproxyVersion)
	return o
}

// SetHaproxyVersion adds the haproxyVersion to the version service apply params.
func (o *VersionServiceApplyParams) SetHaproxyVersion(haproxyVersion *string) {
	o.HaproxyVersion = haproxyVersion
}

// WithHashicorpVaultEnabled adds the hashicorpVaultEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithHashicorpVaultEnabled(hashicorpVaultEnabled *bool) *VersionServiceApplyParams {
	o.SetHashicorpVaultEnabled(hashicorpVaultEnabled)
	return o
}

// SetHashicorpVaultEnabled adds the hashicorpVaultEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetHashicorpVaultEnabled(hashicorpVaultEnabled *bool) {
	o.HashicorpVaultEnabled = hashicorpVaultEnabled
}

// WithHelmDeployCr adds the helmDeployCr to the version service apply params.
func (o *VersionServiceApplyParams) WithHelmDeployCr(helmDeployCr *bool) *VersionServiceApplyParams {
	o.SetHelmDeployCr(helmDeployCr)
	return o
}

// SetHelmDeployCr adds the helmDeployCr to the version service apply params.
func (o *VersionServiceApplyParams) SetHelmDeployCr(helmDeployCr *bool) {
	o.HelmDeployCr = helmDeployCr
}

// WithHelmDeployOperator adds the helmDeployOperator to the version service apply params.
func (o *VersionServiceApplyParams) WithHelmDeployOperator(helmDeployOperator *bool) *VersionServiceApplyParams {
	o.SetHelmDeployOperator(helmDeployOperator)
	return o
}

// SetHelmDeployOperator adds the helmDeployOperator to the version service apply params.
func (o *VersionServiceApplyParams) SetHelmDeployOperator(helmDeployOperator *bool) {
	o.HelmDeployOperator = helmDeployOperator
}

// WithKubeVersion adds the kubeVersion to the version service apply params.
func (o *VersionServiceApplyParams) WithKubeVersion(kubeVersion *string) *VersionServiceApplyParams {
	o.SetKubeVersion(kubeVersion)
	return o
}

// SetKubeVersion adds the kubeVersion to the version service apply params.
func (o *VersionServiceApplyParams) SetKubeVersion(kubeVersion *string) {
	o.KubeVersion = kubeVersion
}

// WithLogCollectorVersion adds the logCollectorVersion to the version service apply params.
func (o *VersionServiceApplyParams) WithLogCollectorVersion(logCollectorVersion *string) *VersionServiceApplyParams {
	o.SetLogCollectorVersion(logCollectorVersion)
	return o
}

// SetLogCollectorVersion adds the logCollectorVersion to the version service apply params.
func (o *VersionServiceApplyParams) SetLogCollectorVersion(logCollectorVersion *string) {
	o.LogCollectorVersion = logCollectorVersion
}

// WithMcsEnabled adds the mcsEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithMcsEnabled(mcsEnabled *bool) *VersionServiceApplyParams {
	o.SetMcsEnabled(mcsEnabled)
	return o
}

// SetMcsEnabled adds the mcsEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetMcsEnabled(mcsEnabled *bool) {
	o.McsEnabled = mcsEnabled
}

// WithMongoTLSMode adds the mongoTLSMode to the version service apply params.
func (o *VersionServiceApplyParams) WithMongoTLSMode(mongoTLSMode *string) *VersionServiceApplyParams {
	o.SetMongoTLSMode(mongoTLSMode)
	return o
}

// SetMongoTLSMode adds the mongoTlsMode to the version service apply params.
func (o *VersionServiceApplyParams) SetMongoTLSMode(mongoTLSMode *string) {
	o.MongoTLSMode = mongoTLSMode
}

// WithMongosSize adds the mongosSize to the version service apply params.
func (o *VersionServiceApplyParams) WithMongosSize(mongosSize *int32) *VersionServiceApplyParams {
	o.SetMongosSize(mongosSize)
	return o
}

// SetMongosSize adds the mongosSize to the version service apply params.
func (o *VersionServiceApplyParams) SetMongosSize(mongosSize *int32) {
	o.MongosSize = mongosSize
}

// WithNamespaceUID adds the namespaceUID to the version service apply params.
func (o *VersionServiceApplyParams) WithNamespaceUID(namespaceUID *string) *VersionServiceApplyParams {
	o.SetNamespaceUID(namespaceUID)
	return o
}

// SetNamespaceUID adds the namespaceUid to the version service apply params.
func (o *VersionServiceApplyParams) SetNamespaceUID(namespaceUID *string) {
	o.NamespaceUID = namespaceUID
}

// WithNonVotingEnabled adds the nonVotingEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithNonVotingEnabled(nonVotingEnabled *bool) *VersionServiceApplyParams {
	o.SetNonVotingEnabled(nonVotingEnabled)
	return o
}

// SetNonVotingEnabled adds the nonVotingEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetNonVotingEnabled(nonVotingEnabled *bool) {
	o.NonVotingEnabled = nonVotingEnabled
}

// WithOciBackupEnabled adds the ociBackupEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithOciBackupEnabled(ociBackupEnabled *bool) *VersionServiceApplyParams {
	o.SetOciBackupEnabled(ociBackupEnabled)
	return o
}

// SetOciBackupEnabled adds the ociBackupEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetOciBackupEnabled(ociBackupEnabled *bool) {
	o.OciBackupEnabled = ociBackupEnabled
}

// WithOperatorVersion adds the operatorVersion to the version service apply params.
func (o *VersionServiceApplyParams) WithOperatorVersion(operatorVersion string) *VersionServiceApplyParams {
	o.SetOperatorVersion(operatorVersion)
	return o
}

// SetOperatorVersion adds the operatorVersion to the version service apply params.
func (o *VersionServiceApplyParams) SetOperatorVersion(operatorVersion string) {
	o.OperatorVersion = operatorVersion
}

// WithPhysicalBackupScheduled adds the physicalBackupScheduled to the version service apply params.
func (o *VersionServiceApplyParams) WithPhysicalBackupScheduled(physicalBackupScheduled *bool) *VersionServiceApplyParams {
	o.SetPhysicalBackupScheduled(physicalBackupScheduled)
	return o
}

// SetPhysicalBackupScheduled adds the physicalBackupScheduled to the version service apply params.
func (o *VersionServiceApplyParams) SetPhysicalBackupScheduled(physicalBackupScheduled *bool) {
	o.PhysicalBackupScheduled = physicalBackupScheduled
}

// WithPitrEnabled adds the pitrEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithPitrEnabled(pitrEnabled *bool) *VersionServiceApplyParams {
	o.SetPitrEnabled(pitrEnabled)
	return o
}

// SetPitrEnabled adds the pitrEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetPitrEnabled(pitrEnabled *bool) {
	o.PitrEnabled = pitrEnabled
}

// WithPlatform adds the platform to the version service apply params.
func (o *VersionServiceApplyParams) WithPlatform(platform *string) *VersionServiceApplyParams {
	o.SetPlatform(platform)
	return o
}

// SetPlatform adds the platform to the version service apply params.
func (o *VersionServiceApplyParams) SetPlatform(platform *string) {
	o.Platform = platform
}

// WithPmmEnabled adds the pmmEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithPmmEnabled(pmmEnabled *bool) *VersionServiceApplyParams {
	o.SetPmmEnabled(pmmEnabled)
	return o
}

// SetPmmEnabled adds the pmmEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetPmmEnabled(pmmEnabled *bool) {
	o.PmmEnabled = pmmEnabled
}

// WithPmmVersion adds the pmmVersion to the version service apply params.
func (o *VersionServiceApplyParams) WithPmmVersion(pmmVersion *string) *VersionServiceApplyParams {
	o.SetPmmVersion(pmmVersion)
	return o
}

// SetPmmVersion adds the pmmVersion to the version service apply params.
func (o *VersionServiceApplyParams) SetPmmVersion(pmmVersion *string) {
	o.PmmVersion = pmmVersion
}

// WithProduct adds the product to the version service apply params.
func (o *VersionServiceApplyParams) WithProduct(product string) *VersionServiceApplyParams {
	o.SetProduct(product)
	return o
}

// SetProduct adds the product to the version service apply params.
func (o *VersionServiceApplyParams) SetProduct(product string) {
	o.Product = product
}

// WithProxysqlVersion adds the proxysqlVersion to the version service apply params.
func (o *VersionServiceApplyParams) WithProxysqlVersion(proxysqlVersion *string) *VersionServiceApplyParams {
	o.SetProxysqlVersion(proxysqlVersion)
	return o
}

// SetProxysqlVersion adds the proxysqlVersion to the version service apply params.
func (o *VersionServiceApplyParams) SetProxysqlVersion(proxysqlVersion *string) {
	o.ProxysqlVersion = proxysqlVersion
}

// WithRoleManagementEnabled adds the roleManagementEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithRoleManagementEnabled(roleManagementEnabled *bool) *VersionServiceApplyParams {
	o.SetRoleManagementEnabled(roleManagementEnabled)
	return o
}

// SetRoleManagementEnabled adds the roleManagementEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetRoleManagementEnabled(roleManagementEnabled *bool) {
	o.RoleManagementEnabled = roleManagementEnabled
}

// WithShardingEnabled adds the shardingEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithShardingEnabled(shardingEnabled *bool) *VersionServiceApplyParams {
	o.SetShardingEnabled(shardingEnabled)
	return o
}

// SetShardingEnabled adds the shardingEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetShardingEnabled(shardingEnabled *bool) {
	o.ShardingEnabled = shardingEnabled
}

// WithSidecarsUsed adds the sidecarsUsed to the version service apply params.
func (o *VersionServiceApplyParams) WithSidecarsUsed(sidecarsUsed *bool) *VersionServiceApplyParams {
	o.SetSidecarsUsed(sidecarsUsed)
	return o
}

// SetSidecarsUsed adds the sidecarsUsed to the version service apply params.
func (o *VersionServiceApplyParams) SetSidecarsUsed(sidecarsUsed *bool) {
	o.SidecarsUsed = sidecarsUsed
}

// WithUserManagementEnabled adds the userManagementEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithUserManagementEnabled(userManagementEnabled *bool) *VersionServiceApplyParams {
	o.SetUserManagementEnabled(userManagementEnabled)
	return o
}

// SetUserManagementEnabled adds the userManagementEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetUserManagementEnabled(userManagementEnabled *bool) {
	o.UserManagementEnabled = userManagementEnabled
}

// WithVectorSearchEnabled adds the vectorSearchEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithVectorSearchEnabled(vectorSearchEnabled *bool) *VersionServiceApplyParams {
	o.SetVectorSearchEnabled(vectorSearchEnabled)
	return o
}

// SetVectorSearchEnabled adds the vectorSearchEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetVectorSearchEnabled(vectorSearchEnabled *bool) {
	o.VectorSearchEnabled = vectorSearchEnabled
}

// WithVolumeExpansionEnabled adds the volumeExpansionEnabled to the version service apply params.
func (o *VersionServiceApplyParams) WithVolumeExpansionEnabled(volumeExpansionEnabled *bool) *VersionServiceApplyParams {
	o.SetVolumeExpansionEnabled(volumeExpansionEnabled)
	return o
}

// SetVolumeExpansionEnabled adds the volumeExpansionEnabled to the version service apply params.
func (o *VersionServiceApplyParams) SetVolumeExpansionEnabled(volumeExpansionEnabled *bool) {
	o.VolumeExpansionEnabled = volumeExpansionEnabled
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *VersionServiceApplyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.AlibabaBackupEnabled != nil {

		// query param alibabaBackupEnabled
		var qrAlibabaBackupEnabled bool

		if o.AlibabaBackupEnabled != nil {
			qrAlibabaBackupEnabled = *o.AlibabaBackupEnabled
		}
		qAlibabaBackupEnabled := conv.FormatBool(qrAlibabaBackupEnabled)
		if qAlibabaBackupEnabled != "" {

			if err := r.SetQueryParam("alibabaBackupEnabled", qAlibabaBackupEnabled); err != nil {
				return err
			}
		}
	}

	// path param apply
	if err := r.SetPathParam("apply", o.Apply); err != nil {
		return err
	}

	if o.ArbiterEnabled != nil {

		// query param arbiterEnabled
		var qrArbiterEnabled bool

		if o.ArbiterEnabled != nil {
			qrArbiterEnabled = *o.ArbiterEnabled
		}
		qArbiterEnabled := conv.FormatBool(qrArbiterEnabled)
		if qArbiterEnabled != "" {

			if err := r.SetQueryParam("arbiterEnabled", qArbiterEnabled); err != nil {
				return err
			}
		}
	}

	if o.BackupVersion != nil {

		// query param backupVersion
		var qrBackupVersion string

		if o.BackupVersion != nil {
			qrBackupVersion = *o.BackupVersion
		}
		qBackupVersion := qrBackupVersion
		if qBackupVersion != "" {

			if err := r.SetQueryParam("backupVersion", qBackupVersion); err != nil {
				return err
			}
		}
	}

	if o.BackupsEnabled != nil {

		// query param backupsEnabled
		var qrBackupsEnabled bool

		if o.BackupsEnabled != nil {
			qrBackupsEnabled = *o.BackupsEnabled
		}
		qBackupsEnabled := conv.FormatBool(qrBackupsEnabled)
		if qBackupsEnabled != "" {

			if err := r.SetQueryParam("backupsEnabled", qBackupsEnabled); err != nil {
				return err
			}
		}
	}

	if o.ClusterSize != nil {

		// query param clusterSize
		var qrClusterSize int32

		if o.ClusterSize != nil {
			qrClusterSize = *o.ClusterSize
		}
		qClusterSize := conv.FormatInteger(qrClusterSize)
		if qClusterSize != "" {

			if err := r.SetQueryParam("clusterSize", qClusterSize); err != nil {
				return err
			}
		}
	}

	if o.ClusterSyncEnabled != nil {

		// query param clusterSyncEnabled
		var qrClusterSyncEnabled bool

		if o.ClusterSyncEnabled != nil {
			qrClusterSyncEnabled = *o.ClusterSyncEnabled
		}
		qClusterSyncEnabled := conv.FormatBool(qrClusterSyncEnabled)
		if qClusterSyncEnabled != "" {

			if err := r.SetQueryParam("clusterSyncEnabled", qClusterSyncEnabled); err != nil {
				return err
			}
		}
	}

	if o.ClusterWideEnabled != nil {

		// query param clusterWideEnabled
		var qrClusterWideEnabled bool

		if o.ClusterWideEnabled != nil {
			qrClusterWideEnabled = *o.ClusterWideEnabled
		}
		qClusterWideEnabled := conv.FormatBool(qrClusterWideEnabled)
		if qClusterWideEnabled != "" {

			if err := r.SetQueryParam("clusterWideEnabled", qClusterWideEnabled); err != nil {
				return err
			}
		}
	}

	if o.CustomResourceUID != nil {

		// query param customResourceUid
		var qrCustomResourceUID string

		if o.CustomResourceUID != nil {
			qrCustomResourceUID = *o.CustomResourceUID
		}
		qCustomResourceUID := qrCustomResourceUID
		if qCustomResourceUID != "" {

			if err := r.SetQueryParam("customResourceUid", qCustomResourceUID); err != nil {
				return err
			}
		}
	}

	if o.DatabaseVersion != nil {

		// query param databaseVersion
		var qrDatabaseVersion string

		if o.DatabaseVersion != nil {
			qrDatabaseVersion = *o.DatabaseVersion
		}
		qDatabaseVersion := qrDatabaseVersion
		if qDatabaseVersion != "" {

			if err := r.SetQueryParam("databaseVersion", qDatabaseVersion); err != nil {
				return err
			}
		}
	}

	if o.Distribution != nil {

		// query param distribution
		var qrDistribution string

		if o.Distribution != nil {
			qrDistribution = *o.Distribution
		}
		qDistribution := qrDistribution
		if qDistribution != "" {

			if err := r.SetQueryParam("distribution", qDistribution); err != nil {
				return err
			}
		}
	}

	if o.EncryptionEnabled != nil {

		// query param encryptionEnabled
		var qrEncryptionEnabled bool

		if o.EncryptionEnabled != nil {
			qrEncryptionEnabled = *o.EncryptionEnabled
		}
		qEncryptionEnabled := conv.FormatBool(qrEncryptionEnabled)
		if qEncryptionEnabled != "" {

			if err := r.SetQueryParam("encryptionEnabled", qEncryptionEnabled); err != nil {
				return err
			}
		}
	}

	if o.Extensions != nil {

		// query param extensions
		var qrExtensions string

		if o.Extensions != nil {
			qrExtensions = *o.Extensions
		}
		qExtensions := qrExtensions
		if qExtensions != "" {

			if err := r.SetQueryParam("extensions", qExtensions); err != nil {
				return err
			}
		}
	}

	if o.HaproxyVersion != nil {

		// query param haproxyVersion
		var qrHaproxyVersion string

		if o.HaproxyVersion != nil {
			qrHaproxyVersion = *o.HaproxyVersion
		}
		qHaproxyVersion := qrHaproxyVersion
		if qHaproxyVersion != "" {

			if err := r.SetQueryParam("haproxyVersion", qHaproxyVersion); err != nil {
				return err
			}
		}
	}

	if o.HashicorpVaultEnabled != nil {

		// query param hashicorpVaultEnabled
		var qrHashicorpVaultEnabled bool

		if o.HashicorpVaultEnabled != nil {
			qrHashicorpVaultEnabled = *o.HashicorpVaultEnabled
		}
		qHashicorpVaultEnabled := conv.FormatBool(qrHashicorpVaultEnabled)
		if qHashicorpVaultEnabled != "" {

			if err := r.SetQueryParam("hashicorpVaultEnabled", qHashicorpVaultEnabled); err != nil {
				return err
			}
		}
	}

	if o.HelmDeployCr != nil {

		// query param helmDeployCr
		var qrHelmDeployCr bool

		if o.HelmDeployCr != nil {
			qrHelmDeployCr = *o.HelmDeployCr
		}
		qHelmDeployCr := conv.FormatBool(qrHelmDeployCr)
		if qHelmDeployCr != "" {

			if err := r.SetQueryParam("helmDeployCr", qHelmDeployCr); err != nil {
				return err
			}
		}
	}

	if o.HelmDeployOperator != nil {

		// query param helmDeployOperator
		var qrHelmDeployOperator bool

		if o.HelmDeployOperator != nil {
			qrHelmDeployOperator = *o.HelmDeployOperator
		}
		qHelmDeployOperator := conv.FormatBool(qrHelmDeployOperator)
		if qHelmDeployOperator != "" {

			if err := r.SetQueryParam("helmDeployOperator", qHelmDeployOperator); err != nil {
				return err
			}
		}
	}

	if o.KubeVersion != nil {

		// query param kubeVersion
		var qrKubeVersion string

		if o.KubeVersion != nil {
			qrKubeVersion = *o.KubeVersion
		}
		qKubeVersion := qrKubeVersion
		if qKubeVersion != "" {

			if err := r.SetQueryParam("kubeVersion", qKubeVersion); err != nil {
				return err
			}
		}
	}

	if o.LogCollectorVersion != nil {

		// query param logCollectorVersion
		var qrLogCollectorVersion string

		if o.LogCollectorVersion != nil {
			qrLogCollectorVersion = *o.LogCollectorVersion
		}
		qLogCollectorVersion := qrLogCollectorVersion
		if qLogCollectorVersion != "" {

			if err := r.SetQueryParam("logCollectorVersion", qLogCollectorVersion); err != nil {
				return err
			}
		}
	}

	if o.McsEnabled != nil {

		// query param mcsEnabled
		var qrMcsEnabled bool

		if o.McsEnabled != nil {
			qrMcsEnabled = *o.McsEnabled
		}
		qMcsEnabled := conv.FormatBool(qrMcsEnabled)
		if qMcsEnabled != "" {

			if err := r.SetQueryParam("mcsEnabled", qMcsEnabled); err != nil {
				return err
			}
		}
	}

	if o.MongoTLSMode != nil {

		// query param mongoTlsMode
		var qrMongoTLSMode string

		if o.MongoTLSMode != nil {
			qrMongoTLSMode = *o.MongoTLSMode
		}
		qMongoTLSMode := qrMongoTLSMode
		if qMongoTLSMode != "" {

			if err := r.SetQueryParam("mongoTlsMode", qMongoTLSMode); err != nil {
				return err
			}
		}
	}

	if o.MongosSize != nil {

		// query param mongosSize
		var qrMongosSize int32

		if o.MongosSize != nil {
			qrMongosSize = *o.MongosSize
		}
		qMongosSize := conv.FormatInteger(qrMongosSize)
		if qMongosSize != "" {

			if err := r.SetQueryParam("mongosSize", qMongosSize); err != nil {
				return err
			}
		}
	}

	if o.NamespaceUID != nil {

		// query param namespaceUid
		var qrNamespaceUID string

		if o.NamespaceUID != nil {
			qrNamespaceUID = *o.NamespaceUID
		}
		qNamespaceUID := qrNamespaceUID
		if qNamespaceUID != "" {

			if err := r.SetQueryParam("namespaceUid", qNamespaceUID); err != nil {
				return err
			}
		}
	}

	if o.NonVotingEnabled != nil {

		// query param nonVotingEnabled
		var qrNonVotingEnabled bool

		if o.NonVotingEnabled != nil {
			qrNonVotingEnabled = *o.NonVotingEnabled
		}
		qNonVotingEnabled := conv.FormatBool(qrNonVotingEnabled)
		if qNonVotingEnabled != "" {

			if err := r.SetQueryParam("nonVotingEnabled", qNonVotingEnabled); err != nil {
				return err
			}
		}
	}

	if o.OciBackupEnabled != nil {

		// query param ociBackupEnabled
		var qrOciBackupEnabled bool

		if o.OciBackupEnabled != nil {
			qrOciBackupEnabled = *o.OciBackupEnabled
		}
		qOciBackupEnabled := conv.FormatBool(qrOciBackupEnabled)
		if qOciBackupEnabled != "" {

			if err := r.SetQueryParam("ociBackupEnabled", qOciBackupEnabled); err != nil {
				return err
			}
		}
	}

	// path param operatorVersion
	if err := r.SetPathParam("operatorVersion", o.OperatorVersion); err != nil {
		return err
	}

	if o.PhysicalBackupScheduled != nil {

		// query param physicalBackupScheduled
		var qrPhysicalBackupScheduled bool

		if o.PhysicalBackupScheduled != nil {
			qrPhysicalBackupScheduled = *o.PhysicalBackupScheduled
		}
		qPhysicalBackupScheduled := conv.FormatBool(qrPhysicalBackupScheduled)
		if qPhysicalBackupScheduled != "" {

			if err := r.SetQueryParam("physicalBackupScheduled", qPhysicalBackupScheduled); err != nil {
				return err
			}
		}
	}

	if o.PitrEnabled != nil {

		// query param pitrEnabled
		var qrPitrEnabled bool

		if o.PitrEnabled != nil {
			qrPitrEnabled = *o.PitrEnabled
		}
		qPitrEnabled := conv.FormatBool(qrPitrEnabled)
		if qPitrEnabled != "" {

			if err := r.SetQueryParam("pitrEnabled", qPitrEnabled); err != nil {
				return err
			}
		}
	}

	if o.Platform != nil {

		// query param platform
		var qrPlatform string

		if o.Platform != nil {
			qrPlatform = *o.Platform
		}
		qPlatform := qrPlatform
		if qPlatform != "" {

			if err := r.SetQueryParam("platform", qPlatform); err != nil {
				return err
			}
		}
	}

	if o.PmmEnabled != nil {

		// query param pmmEnabled
		var qrPmmEnabled bool

		if o.PmmEnabled != nil {
			qrPmmEnabled = *o.PmmEnabled
		}
		qPmmEnabled := conv.FormatBool(qrPmmEnabled)
		if qPmmEnabled != "" {

			if err := r.SetQueryParam("pmmEnabled", qPmmEnabled); err != nil {
				return err
			}
		}
	}

	if o.PmmVersion != nil {

		// query param pmmVersion
		var qrPmmVersion string

		if o.PmmVersion != nil {
			qrPmmVersion = *o.PmmVersion
		}
		qPmmVersion := qrPmmVersion
		if qPmmVersion != "" {

			if err := r.SetQueryParam("pmmVersion", qPmmVersion); err != nil {
				return err
			}
		}
	}

	// path param product
	if err := r.SetPathParam("product", o.Product); err != nil {
		return err
	}

	if o.ProxysqlVersion != nil {

		// query param proxysqlVersion
		var qrProxysqlVersion string

		if o.ProxysqlVersion != nil {
			qrProxysqlVersion = *o.ProxysqlVersion
		}
		qProxysqlVersion := qrProxysqlVersion
		if qProxysqlVersion != "" {

			if err := r.SetQueryParam("proxysqlVersion", qProxysqlVersion); err != nil {
				return err
			}
		}
	}

	if o.RoleManagementEnabled != nil {

		// query param roleManagementEnabled
		var qrRoleManagementEnabled bool

		if o.RoleManagementEnabled != nil {
			qrRoleManagementEnabled = *o.RoleManagementEnabled
		}
		qRoleManagementEnabled := conv.FormatBool(qrRoleManagementEnabled)
		if qRoleManagementEnabled != "" {

			if err := r.SetQueryParam("roleManagementEnabled", qRoleManagementEnabled); err != nil {
				return err
			}
		}
	}

	if o.ShardingEnabled != nil {

		// query param shardingEnabled
		var qrShardingEnabled bool

		if o.ShardingEnabled != nil {
			qrShardingEnabled = *o.ShardingEnabled
		}
		qShardingEnabled := conv.FormatBool(qrShardingEnabled)
		if qShardingEnabled != "" {

			if err := r.SetQueryParam("shardingEnabled", qShardingEnabled); err != nil {
				return err
			}
		}
	}

	if o.SidecarsUsed != nil {

		// query param sidecarsUsed
		var qrSidecarsUsed bool

		if o.SidecarsUsed != nil {
			qrSidecarsUsed = *o.SidecarsUsed
		}
		qSidecarsUsed := conv.FormatBool(qrSidecarsUsed)
		if qSidecarsUsed != "" {

			if err := r.SetQueryParam("sidecarsUsed", qSidecarsUsed); err != nil {
				return err
			}
		}
	}

	if o.UserManagementEnabled != nil {

		// query param userManagementEnabled
		var qrUserManagementEnabled bool

		if o.UserManagementEnabled != nil {
			qrUserManagementEnabled = *o.UserManagementEnabled
		}
		qUserManagementEnabled := conv.FormatBool(qrUserManagementEnabled)
		if qUserManagementEnabled != "" {

			if err := r.SetQueryParam("userManagementEnabled", qUserManagementEnabled); err != nil {
				return err
			}
		}
	}

	if o.VectorSearchEnabled != nil {

		// query param vectorSearchEnabled
		var qrVectorSearchEnabled bool

		if o.VectorSearchEnabled != nil {
			qrVectorSearchEnabled = *o.VectorSearchEnabled
		}
		qVectorSearchEnabled := conv.FormatBool(qrVectorSearchEnabled)
		if qVectorSearchEnabled != "" {

			if err := r.SetQueryParam("vectorSearchEnabled", qVectorSearchEnabled); err != nil {
				return err
			}
		}
	}

	if o.VolumeExpansionEnabled != nil {

		// query param volumeExpansionEnabled
		var qrVolumeExpansionEnabled bool

		if o.VolumeExpansionEnabled != nil {
			qrVolumeExpansionEnabled = *o.VolumeExpansionEnabled
		}
		qVolumeExpansionEnabled := conv.FormatBool(qrVolumeExpansionEnabled)
		if qVolumeExpansionEnabled != "" {

			if err := r.SetQueryParam("volumeExpansionEnabled", qVolumeExpansionEnabled); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
