#!/bin/bash

test_dir="$(dirname $0)"
. $(dirname $0)/functions
src_dir="$(realpath $test_dir/..)"

$test_dir/build
create_namespace run-$GIT_BRANCH
deploy_operator

desc 'create PSMDB cluster'
kubectl apply -f $src_dir/deploy/mongodb-users.yaml

platform=(kubernetes openshift)
cat $src_dir/deploy/cr.yaml \
    | $sed 's/version: .*/version: "3.6"/' \
    | $sed "s/#platform: .*/platform: ${platform[${OPENSHIFT:-0}]}/" \
    | kubectl apply -f -

wait_for_running my-cluster-name-rs0 3
