#!/bin/bash

set -o errexit
set -o xtrace

test_dir="$(dirname $0)"
. $(dirname $0)/functions
src_dir="$(realpath $test_dir/..)"

build_operator() {
    if [ "${RELEASE:-0}" = 0 ]; then
        GO_LDFLAGS="-race"
        $sed -i -e 's^"percona/percona-server-mongodb-operator:"^"perconalab/percona-server-mongodb-operator:"^' ${src_dir}/pkg/psmdb/container.go
        $sed -i -e "s/master/$GIT_BRANCH/" ${src_dir}/version/version.go
    fi
    repo=$(
        git config --get remote.origin.url \
            | sed -e 's^.*github.com[:/]^github.com/^; s/.git$//'
    )
    docker run --rm -v ${src_dir}:/go/src/${repo} golang sh -c "
        set -o errexit
        set -o xtrace
        export GO_LDFLAGS='-w -s $GO_LDFLAGS'
        export GIT_COMMIT='$GIT_COMMIT'
        export GIT_BRANCH='$GIT_BRANCH'

        cd /go/src/${repo}
        mkdir -p build/_output/bin
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build \
            -ldflags '-w -s -X main.GitCommit=${GIT_COMMIT} -X main.GitBranch=${GIT_BRANCH}' \
            -o build/_output/bin/percona-server-mongodb-operator \
            cmd/manager/main.go
    "
    if [ "${RELEASE:-0}" = 0 ]; then
        $sed -i -e 's^"perconalab/percona-server-mongodb-operator:"^"percona/percona-server-mongodb-operator:"^' ${src_dir}/pkg/psmdb/container.go
        $sed -i -e "s/$GIT_BRANCH/master/" ${src_dir}/version/version.go
    fi
    export IMAGE
    pushd ${src_dir}
        docker build \
            --squash \
            --no-cache \
            -t "${IMAGE}" -f build/Dockerfile .
    popd
    docker push ${IMAGE}
}

build_mongod36() {
    pushd ${src_dir}
        docker build --no-cache --squash -t ${IMAGE_MONGOD36} -f build/Dockerfile.mongod36 .
    popd
    docker push ${IMAGE_MONGOD36}
}

build_operator
build_mongod36
