#!/bin/bash

set -o xtrace
set -o errexit

dir=$(realpath $(dirname $0))

$dir/init-deploy/run
$dir/limits/run
$dir/scaling/run
$dir/monitoring/run
$dir/monitoring-2-0/run
$dir/one-pod/run
$dir/service-per-pod/run
$dir/arbiter/run
$dir/demand-backup/run
$dir/scheduled-backup/run
$dir/upgrade/run
$dir/upgrade-consistency/run

$dir/storage/run
$dir/self-healing/run
$dir/operator-self-healing/run
