#!/bin/bash

set -o xtrace
set -o errexit

dir=$(realpath "$(dirname "$0")")

fail() {
	local test=$1
	echo "test $test failed"
	exit 1
}

"$dir/default-cr/run" || fail "default-cr"
"$dir/arbiter/run" || fail "arbiter"
"$dir/data-sharded/run" || fail "data-sharded"
"$dir/demand-backup-sharded/run" || fail "demand-backup-sharded"
"$dir/demand-backup/run" || fail "demand-backup"
"$dir/init-deploy/run" || fail "init-deploy"
"$dir/limits/run" || fail "limits"
"$dir/liveness/run" || fail "liveness"
"$dir/monitoring-2-0/run" || fail "monitoring-2-0"
"$dir/non-voting/run" || fail "non-voting"
"$dir/one-pod/run" || fail "one-pod"
"$dir/operator-self-healing-chaos/run" || fail "operator-self-healing-chaos"
"$dir/operator-self-healing/run" || fail "operator-self-healing"
"$dir/pitr-sharded/run" || fail "pitr-sharded"
"$dir/pitr/run" || fail "pitr"
"$dir/rs-shard-migration/run" || fail "rs-shard-migration"
"$dir/scaling/run" || fail "scaling"
"$dir/scheduled-backup/run" || fail "scheduled-backup"
"$dir/security-context/run" || fail "security-context"
"$dir/self-healing-chaos/run" || fail "self-healing-chaos"
"$dir/self-healing/run" || fail "self-healing"
"$dir/service-per-pod/run" || fail "service-per-pod"
"$dir/smart-update/run" || fail "smart-update"
"$dir/storage/run" || fail "storage"
"$dir/upgrade-consistency/run" || fail "upgrade-consistency"
"$dir/upgrade-sharded/run" || fail "upgrade-sharded"
"$dir/upgrade/run" || fail "upgrade"
"$dir/users/run" || fail "users"
"$dir/version-service/run" || fail "version-service"
#"$dir/cross-site-sharded/run" || fail "cross-site-sharded"
