apiVersion: v1
kind: Service
metadata:
  annotations:
    ignoredAnnotation: "true"
    otherCrAnnotation: "true"
  labels:
    app.kubernetes.io/component: external-service
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: cfg
    ignoredLabel: "true"
    otherCrLabel: "true"
  name: some-name-cfg-0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: some-name
spec:
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: some-name-cfg-0
  sessionAffinity: None
  type: ClusterIP
