apiVersion: v1
kind: Service
metadata:
  annotations:
    ignoredAnnotation: "true"
    otherCrAnnotation: "true"
    secondCrAnnotation: "true"
  labels:
    app.kubernetes.io/component: mongos
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    ignoredLabel: "true"
    otherCrLabel: "true"
    secondCrLabel: "true"
  name: some-name-mongos-0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: some-name
spec:
  ports:
    - name: mongos
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app.kubernetes.io/component: mongos
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    statefulset.kubernetes.io/pod-name: some-name-mongos-0
  sessionAffinity: None
  type: ClusterIP
