apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: backup-schedule
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: general
  name: some-name-backup-every-min-aws-s3
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: StatefulSet
    name: some-name-backup-coordinator
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup-schedule
        app.kubernetes.io/instance: some-name
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: general
    spec:
      template:
        metadata:
        spec:
          containers:
          - args:
            - run
            - backup
            - --description=some-name-every-min-aws-s3
            - --storage=aws-s3
            - --compression-algorithm=gzip
            command:
            - pbmctl
            env:
            - name: PBMCTL_SERVER_ADDRESS
              value: some-name-backup-coordinator:10001
            imagePullPolicy: IfNotPresent
            name: backup-pmbctl
            resources: {}
            securityContext:
              runAsNonRoot: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
