apiVersion: v1
kind: Service
metadata:
  name: some-name-backup-coordinator
  ownerReferences:
  - apiVersion: psmdb.percona.com/v1alpha1
    controller: true
    kind: PerconaServerMongoDB
    name: some-name
spec:
  ports:
  - name: rpc
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: api
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app.kubernetes.io/component: backup-coordinator
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: general
  sessionAffinity: None
  type: ClusterIP
