#!/bin/bash

set -o errexit

if [ -z "$SKIP_BACKUPS_TO_AWS_GCP_AZURE" ]; then
	log "Skipping cloud backup tests"
	exit 0
fi

test_dir=$(realpath "$(dirname "$0")")
. "${test_dir}/../functions"
set_debug

create_infra "${namespace}"

apply_s3_storage_secrets

### Case 1: Backup and restore on sharded cluster
desc 'Testing on sharded cluster'

log "Creating PSMDB cluster"
cluster="some-name"
kubectl_bin apply -f "${conf_dir}/secrets.yml"
apply_cluster "${test_dir}/conf/${cluster}-sharded.yml"
kubectl_bin apply -f "${conf_dir}/client_with_tls.yml"

log "check if all pods started"
wait_for_running ${cluster}-rs0 3
wait_for_running ${cluster}-cfg 3
wait_for_running ${cluster}-mongos 3
wait_cluster_consistency ${cluster}

lbEndpoint=$(kubectl_bin get svc $cluster-mongos -o=jsonpath='{.status}' \
	| jq -r 'select(.loadBalancer != null and .loadBalancer.ingress != null and .loadBalancer.ingress != []) | .loadBalancer.ingress[0] | if .ip then .ip else .hostname end')
if [ -z "$lbEndpoint" ]; then
	log "mongos service not exported correctly"
	exit 1
fi

run_mongos \
	'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
	"userAdmin:userAdmin123456@${cluster}-mongos.${namespace}"
sleep 1
run_mongos \
	'use myApp\n db.test.insert({ x: 100501 })' \
	"myApp:myPass@${cluster}-mongos.${namespace}"
sleep 5
compare_mongos_cmd "find" "myApp:myPass@${cluster}-mongos.${namespace}" "-sharded"

# wait for stable timestamp in wiredtiger
log 'waiting 60 seconds for stable timestamp in wiredtiger'
sleep 80

log 'running backup'

backup_name_gcp_cs_s3_sharded="backup-gcp-cs-s3-sharded"
run_backup gcp-cs-s3 ${backup_name_gcp_cs_s3_sharded} incremental-base
wait_backup "${backup_name_gcp_cs_s3_sharded}"
check_backup_in_storage ${backup_name_gcp_cs_s3_sharded} gcs rs0
check_backup_in_storage ${backup_name_gcp_cs_s3_sharded} gcs cfg

log 'running restore'
run_restore "${backup_name_gcp_cs_s3_sharded}"
run_recovery_check "${backup_name_gcp_cs_s3_sharded}" "_restore_sharded" "sharded"
check_exported_mongos_service_endpoint "$lbEndpoint"

desc 'test passed'

destroy "$namespace"
