#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

CLUSTER='some-name'

main() {
	create_infra $namespace

	kubectl_bin apply -f "${conf_dir}/client.yml" \
		-f "${conf_dir}/secrets.yml"

	# test 1.11.0
	apply_cluster "$test_dir/conf/${CLUSTER}-rs0.yml"
	wait_for_running "${CLUSTER}-rs0" "1" "false"

	compare_kubectl service/${CLUSTER}-rs0 "-1110"
	compare_kubectl statefulset/${CLUSTER}-rs0 "-1110"

	# test 1.12.0
	kubectl_bin patch psmdb "${CLUSTER}" --type=merge --patch '{
        "spec": {"crVersion":"1.12.0"}
    }'
	wait_for_running "${CLUSTER}-rs0" "1" "false"

	compare_kubectl service/${CLUSTER}-rs0 "-1120"
	compare_kubectl statefulset/${CLUSTER}-rs0 "-1120"

	# test 1.13.0
	kubectl_bin patch psmdb "${CLUSTER}" --type=merge --patch '{
        "spec": {"crVersion":"1.13.0"}
    }'
	wait_for_running "${CLUSTER}-rs0" "1" "false"

	compare_kubectl service/${CLUSTER}-rs0 "-1130"
	compare_kubectl statefulset/${CLUSTER}-rs0 "-1130"

	# test 1.14.0
	kubectl_bin patch psmdb "${CLUSTER}" --type=merge --patch '{
        "spec": {"crVersion":"1.14.0"}
    }'
	wait_for_running "${CLUSTER}-rs0" "1" "false"

	compare_kubectl service/${CLUSTER}-rs0 "-1140"
	compare_kubectl statefulset/${CLUSTER}-rs0 "-1140"

	destroy $namespace
}

main
