apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  labels:
    app.kubernetes.io/component: mongod
    app.kubernetes.io/instance: my-cluster-name
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: my-cluster-name-rs0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: my-cluster-name
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongod
      app.kubernetes.io/instance: my-cluster-name
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: my-cluster-name-rs0
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: mongod
        app.kubernetes.io/instance: my-cluster-name
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      containers:
        - args:
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=rs0
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --clusterAuthMode=x509
            - --tlsMode=preferTLS
            - --shardsvr
            - --enableEncryption
            - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
            - --wiredTigerCacheSizeGB=0.25
            - --wiredTigerIndexPrefixCompression=true
            - --quiet
          command:
            - /opt/percona/ps-entry.sh
          env:
            - name: SERVICE_NAME
              value: my-cluster-name
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLSET
              value: rs0
            - name: LOGCOLLECTOR_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: internal-my-cluster-name-users
                optional: false
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /opt/percona/mongodb-healthcheck
                - k8s
                - liveness
                - --ssl
                - --sslInsecure
                - --sslCAFile
                - /etc/mongodb-ssl/ca.crt
                - --sslPEMKeyFile
                - /tmp/tls.pem
                - --startupDelaySeconds
                - "7200"
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: mongod
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /opt/percona/mongodb-healthcheck
                - k8s
                - readiness
                - --component
                - mongod
            failureThreshold: 8
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 300m
              memory: 500M
            requests:
              cpu: 300m
              memory: 500M
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /etc/mongodb-secrets
              name: my-cluster-name-mongodb-keyfile
              readOnly: true
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /etc/mongodb-ssl-internal
              name: ssl-internal
              readOnly: true
            - mountPath: /opt/percona
              name: bin
            - mountPath: /etc/mongodb-encryption
              name: my-cluster-name-mongodb-encryption-key
              readOnly: true
            - mountPath: /etc/users-secret
              name: users-secret-file
          workingDir: /data/db
        - args:
            - pbm-agent-entrypoint
          command:
            - /opt/percona/pbm-entry.sh
          env:
            - name: PBM_AGENT_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGODB_BACKUP_USER_ESCAPED
                  name: internal-my-cluster-name-users
                  optional: false
            - name: PBM_AGENT_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_BACKUP_PASSWORD_ESCAPED
                  name: internal-my-cluster-name-users
                  optional: false
            - name: PBM_MONGODB_REPLSET
              value: rs0
            - name: PBM_MONGODB_PORT
              value: "27017"
            - name: PBM_AGENT_SIDECAR
              value: "true"
            - name: PBM_AGENT_SIDECAR_SLEEP
              value: "5"
            - name: SHARDED
              value: "TRUE"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PBM_MONGODB_URI
              value: mongodb://$(PBM_AGENT_MONGODB_USERNAME):$(PBM_AGENT_MONGODB_PASSWORD)@localhost:$(PBM_MONGODB_PORT)/?tls=true&tlsCertificateKeyFile=/tmp/tls.pem&tlsCAFile=/etc/mongodb-ssl/ca.crt&tlsInsecure=true
            - name: PBM_AGENT_TLS_ENABLED
              value: "true"
          imagePullPolicy: Always
          name: backup-agent
          resources: {}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /opt/percona
              name: bin
              readOnly: true
            - mountPath: /data/db
              name: mongod-data
        - args:
            - fluent-bit
          command:
            - /opt/percona/logcollector/entrypoint.sh
          env:
            - name: LOG_DATA_DIR
              value: /data/db/logs
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          imagePullPolicy: IfNotPresent
          name: logs
          resources:
            requests:
              cpu: 200m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /opt/percona
              name: bin
        - args:
            - logrotate
          command:
            - /opt/percona/logcollector/entrypoint.sh
          env:
            - name: MONGODB_HOST
              value: localhost
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: MONGODB_CLUSTER_ADMIN_USER_ESCAPED
                  name: internal-my-cluster-name-users
                  optional: false
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_CLUSTER_ADMIN_PASSWORD_ESCAPED
                  name: internal-my-cluster-name-users
                  optional: false
          imagePullPolicy: IfNotPresent
          name: logrotate
          resources:
            requests:
              cpu: 200m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /opt/percona
              name: bin
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /init-entrypoint.sh
          imagePullPolicy: Always
          name: mongo-init
          resources:
            limits:
              cpu: 300m
              memory: 500M
            requests:
              cpu: 300m
              memory: 500M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      volumes:
        - name: my-cluster-name-mongodb-keyfile
          secret:
            defaultMode: 288
            optional: false
            secretName: my-cluster-name-mongodb-keyfile
        - emptyDir: {}
          name: bin
        - name: my-cluster-name-mongodb-encryption-key
          secret:
            defaultMode: 288
            optional: false
            secretName: my-cluster-name-mongodb-encryption-key
        - name: ssl
          secret:
            defaultMode: 288
            optional: false
            secretName: my-cluster-name-ssl
        - name: ssl-internal
          secret:
            defaultMode: 288
            optional: true
            secretName: my-cluster-name-ssl-internal
        - name: users-secret-file
          secret:
            defaultMode: 420
            secretName: internal-my-cluster-name-users
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
    - metadata:
        name: mongod-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
      status:
        phase: Pending
