apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  labels:
    app.kubernetes.io/component: cfg
    app.kubernetes.io/instance: minimal-cluster
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: cfg
  name: minimal-cluster-cfg
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: minimal-cluster
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: cfg
      app.kubernetes.io/instance: minimal-cluster
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: cfg
  serviceName: minimal-cluster-cfg
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: cfg
        app.kubernetes.io/instance: minimal-cluster
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: cfg
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: cfg
                  app.kubernetes.io/instance: minimal-cluster
                  app.kubernetes.io/managed-by: percona-server-mongodb-operator
                  app.kubernetes.io/name: percona-server-mongodb
                  app.kubernetes.io/part-of: percona-server-mongodb
                  app.kubernetes.io/replset: cfg
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=cfg
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --clusterAuthMode=keyFile
            - --keyFile=/etc/mongodb-secrets/mongodb-key
            - --configsvr
            - --enableEncryption
            - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
            - --wiredTigerIndexPrefixCompression=true
          command:
            - /data/db/ps-entry.sh
          env:
            - name: SERVICE_NAME
              value: minimal-cluster
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLSET
              value: cfg
          envFrom:
            - secretRef:
                name: internal-minimal-cluster-users
                optional: false
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /data/db/mongodb-healthcheck
                - k8s
                - liveness
                - --ssl
                - --sslInsecure
                - --sslCAFile
                - /etc/mongodb-ssl/ca.crt
                - --sslPEMKeyFile
                - /tmp/tls.pem
                - --startupDelaySeconds
                - "7200"
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: mongod
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 2
          resources: {}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /etc/mongodb-secrets
              name: minimal-cluster-mongodb-keyfile
              readOnly: true
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /etc/mongodb-ssl-internal
              name: ssl-internal
              readOnly: true
            - mountPath: /etc/mongodb-encryption
              name: minimal-cluster-mongodb-encryption-key
              readOnly: true
            - mountPath: /etc/users-secret
              name: users-secret-file
          workingDir: /data/db
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /init-entrypoint.sh
          imagePullPolicy: Always
          name: mongo-init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: minimal-cluster-mongodb-keyfile
          secret:
            defaultMode: 288
            optional: false
            secretName: minimal-cluster-mongodb-keyfile
        - emptyDir: {}
          name: bin
        - name: minimal-cluster-mongodb-encryption-key
          secret:
            defaultMode: 288
            optional: false
            secretName: minimal-cluster-mongodb-encryption-key
        - name: ssl
          secret:
            defaultMode: 288
            optional: true
            secretName: minimal-cluster-ssl
        - name: ssl-internal
          secret:
            defaultMode: 288
            optional: true
            secretName: minimal-cluster-ssl-internal
        - name: users-secret-file
          secret:
            defaultMode: 420
            secretName: internal-minimal-cluster-users
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: mongod-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
      status:
        phase: Pending
