apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  labels:
    app.kubernetes.io/component: mongod
    app.kubernetes.io/instance: liveness
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: liveness-rs0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: liveness
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongod
      app.kubernetes.io/instance: liveness
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: liveness-rs0
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: mongod
        app.kubernetes.io/instance: liveness
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      containers:
        - args:
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=rs0
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --sslMode=preferSSL
            - --clusterAuthMode=x509
            - --slowms=100
            - --profile=1
            - --rateLimit=1
            - --enableEncryption
            - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
            - --wiredTigerCacheSizeGB=0.25
            - --wiredTigerCollectionBlockCompressor=snappy
            - --wiredTigerJournalCompressor=snappy
            - --wiredTigerIndexPrefixCompression=true
            - --setParameter
            - ttlMonitorSleepSecs=60
            - --setParameter
            - wiredTigerConcurrentReadTransactions=128
            - --setParameter
            - wiredTigerConcurrentWriteTransactions=128
          command:
            - /data/db/ps-entry.sh
          env:
            - name: SERVICE_NAME
              value: liveness
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLSET
              value: rs0
          envFrom:
            - secretRef:
                name: internal-liveness-users
                optional: false
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /data/db/mongodb-healthcheck
                - k8s
                - liveness
                - --ssl
                - --sslInsecure
                - --sslCAFile
                - /etc/mongodb-ssl/ca.crt
                - --sslPEMKeyFile
                - /tmp/tls.pem
                - --startupDelaySeconds
                - "7201"
            failureThreshold: 5
            initialDelaySeconds: 61
            periodSeconds: 31
            successThreshold: 1
            timeoutSeconds: 6
          name: mongod
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          readinessProbe:
            failureThreshold: 9
            initialDelaySeconds: 11
            periodSeconds: 4
            successThreshold: 2
            tcpSocket:
              port: 27017
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 100m
              memory: 100M
          securityContext:
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /etc/mongodb-secrets
              name: liveness-mongodb-keyfile
              readOnly: true
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /etc/mongodb-ssl-internal
              name: ssl-internal
              readOnly: true
            - mountPath: /etc/mongodb-encryption
              name: liveness-mongodb-encryption-key
              readOnly: true
            - mountPath: /etc/users-secret
              name: users-secret-file
          workingDir: /data/db
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /init-entrypoint.sh
          imagePullPolicy: Always
          name: mongo-init
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 100m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: liveness-mongodb-keyfile
          secret:
            defaultMode: 288
            optional: false
            secretName: liveness-mongodb-keyfile
        - name: liveness-mongodb-encryption-key
          secret:
            defaultMode: 288
            optional: false
            secretName: liveness-mongodb-encryption-key
        - name: ssl
          secret:
            defaultMode: 288
            optional: false
            secretName: liveness-ssl
        - name: ssl-internal
          secret:
            defaultMode: 288
            optional: true
            secretName: liveness-ssl-internal
        - name: users-secret-file
          secret:
            defaultMode: 420
            secretName: internal-liveness-users
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: mongod-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status:
        phase: Pending
