apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 2
  name: liveness-rs0
  ownerReferences:
  - apiVersion: psmdb.percona.com/v1
    controller: true
    kind: PerconaServerMongoDB
    name: liveness
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongod
      app.kubernetes.io/instance: liveness
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: liveness-rs0
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/component: mongod
        app.kubernetes.io/instance: liveness
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      containers:
      - args:
        - --bind_ip_all
        - --auth
        - --dbpath=/data/db
        - --port=27017
        - --replSet=rs0
        - --storageEngine=wiredTiger
        - --relaxPermChecks
        - --sslAllowInvalidCertificates
        - --sslMode=preferSSL
        - --clusterAuthMode=x509
        - --slowms=100
        - --profile=1
        - --rateLimit=1
        - --enableEncryption
        - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
        - --wiredTigerCacheSizeGB=0.25
        - --wiredTigerCollectionBlockCompressor=snappy
        - --wiredTigerJournalCompressor=snappy
        - --wiredTigerIndexPrefixCompression=true
        - --setParameter
        - ttlMonitorSleepSecs=60
        - --setParameter
        - wiredTigerConcurrentReadTransactions=128
        - --setParameter
        - wiredTigerConcurrentWriteTransactions=128
        command:
        - /data/db/ps-entry.sh
        env:
        - name: SERVICE_NAME
          value: liveness
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_REPLSET
          value: rs0
        envFrom:
        - secretRef:
            name: some-users
            optional: false
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mongodb-healthcheck
            - k8s
            - liveness
            - --startupDelaySeconds
            - "7202"
          failureThreshold: 6
          initialDelaySeconds: 62
          periodSeconds: 32
          successThreshold: 1
          timeoutSeconds: 7
        name: mongod
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 12
          periodSeconds: 5
          successThreshold: 3
          tcpSocket:
            port: 27017
          timeoutSeconds: 4
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongod-data
        - mountPath: /etc/mongodb-secrets
          name: liveness-mongodb-keyfile
          readOnly: true
        - mountPath: /etc/mongodb-ssl
          name: ssl
          readOnly: true
        - mountPath: /etc/mongodb-ssl-internal
          name: ssl-internal
          readOnly: true
        - mountPath: /etc/mongodb-encryption
          name: liveness-mongodb-encryption-key
          readOnly: true
        workingDir: /data/db
      - env:
        - name: PBM_AGENT_MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MONGODB_BACKUP_USER
              name: some-users
              optional: false
        - name: PBM_AGENT_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGODB_BACKUP_PASSWORD
              name: some-users
              optional: false
        - name: PBM_MONGODB_REPLSET
          value: rs0
        - name: PBM_MONGODB_PORT
          value: "27017"
        imagePullPolicy: Always
        name: backup-agent
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /init-entrypoint.sh
        imagePullPolicy: Always
        name: mongo-init
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongod-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - name: liveness-mongodb-keyfile
        secret:
          defaultMode: 288
          optional: false
          secretName: liveness-mongodb-keyfile
      - name: liveness-mongodb-encryption-key
        secret:
          defaultMode: 288
          optional: false
          secretName: liveness-mongodb-encryption-key
      - name: ssl
        secret:
          defaultMode: 288
          optional: false
          secretName: liveness-ssl
      - name: ssl-internal
        secret:
          defaultMode: 288
          optional: true
          secretName: liveness-ssl-internal
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
      name: mongod-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status:
      phase: Pending
