apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always

  sharding:
    enabled: true

    configsvrReplSet:
      size: 3
      configuration: |
        net:
          tls:
            mode: requireTLS
      affinity:
        antiAffinityTopologyKey: none
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi

    mongos:
      size: 3
      configuration: |
        net:
          tls:
            mode: requireTLS
      affinity:
        antiAffinityTopologyKey: none
      expose:
        exposeType: ClusterIP

  replsets:

  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
    configuration: |
      net:
        tls:
          mode: requireTLS
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true

  - name: rs1
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi

    size: 3
    configuration: |
      net:
        tls:
          mode: requireTLS
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
  - name: rs2
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
    configuration: |
      net:
        tls:
          mode: requireTLS
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true

  secrets:
    users: some-users
