apiVersion: v1
kind: Secret
metadata:
  name: openldap
type: Opaque
stringData:
  adminpassword: adminpassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: ldap-setup
          image: osixia/openldap:latest
          command: ["/bin/bash"]
          args:
            - -c
            - |
              echo "Waiting for LDAP server to be ready..."
              sleep 60
              
              echo "Adding LDAP structure..."
              ldapadd -x -H ldap://localhost:389 -D "cn=admin,dc=ldap,dc=local" -w adminpassword <<EOF
              dn: ou=perconadba,dc=ldap,dc=local
              objectClass: organizationalUnit
              ou: perconadba

              dn: uid=percona,ou=perconadba,dc=ldap,dc=local
              objectClass: inetOrgPerson
              uid: percona
              cn: percona
              sn: percona
              userPassword: password

              dn: cn=admin,ou=perconadba,dc=ldap,dc=local
              objectClass: groupOfUniqueNames
              cn: admin
              uniqueMember: uid=percona,ou=perconadba,dc=ldap,dc=local
              EOF
              
              echo "LDAP structure added successfully"
              sleep infinity
          env:
            - name: LDAP_DOMAIN
              value: "ldap.local"
            - name: LDAP_ORGANISATION
              value: "ldap.local"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
        - name: openldap
          image: osixia/openldap:latest
          imagePullPolicy: "Always"
          args: ["--copy-service"]
          env:
            - name: LDAP_DOMAIN
              value: "ldap.local"
            - name: LDAP_ORGANISATION
              value: "ldap.local"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
            - name: LDAP_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
            - name: LDAP_READONLY_USER
              value: "true"
            - name: LDAP_READONLY_USER_USERNAME
              value: "readonly"
            - name: LDAP_READONLY_USER_PASSWORD
              value: "readonlypass"
            - name: CONTAINER_LOG_LEVEL
              value: "info"
            - name: LDAP_PORT_NUMBER
              value: "389"
          ports:
            - name: tcp-ldap
              containerPort: 389
          readinessProbe:
            tcpSocket:
              port: 389
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 389
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: openldap
