apiVersion: v1
kind: ServiceAccount
metadata:
  name: psmdb-pods
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: custom-psmdb-scc
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-custom-psmdb-scc
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - custom-psmdb-scc
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-psmdb-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-custom-psmdb-scc
subjects:
- kind: ServiceAccount
  name: psmdb-pods
