apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: monitoring
spec:
  #platform: openshift
  image:
  tls:
    mode: requireTLS
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
    configuration: |
      net:
        port: 27019
      operationProfiling:
        mode: all
        slowOpThresholdMs: 100
        rateLimit: 100
      security:
        enableEncryption: true

  sharding:
    enabled: true
    configsvrReplSet:
      size: 3
      configuration: |
        net:
          port: 27019
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi

    mongos:
      size: 3
      configuration: |
        net:
          port: 27019
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: "300m"
          memory: "0.5G"
        requests:
          cpu: "300m"
          memory: "0.5G"
      expose:
        type: ClusterIP
        labels:
          test: monitoring
        annotations:
          test: monitoring

  pmm:
    enabled: true
    image: -pmm
    serverHost: monitoring-service
    mongosParams: "--environment=dev-mongos"
    mongodParams: "--enable-all-collectors --environment=dev-mongod"
  secrets:
    users: some-users
