---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name:
  annotations:
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    support: percona/percona.com
    categories: Database
    capabilities: Deep Insights
    description: >-
      Percona Distribution for MongoDB Operator automates the creation, modification, or deletion of items in your Percona Server for MongoDB environment
    createdAt: "%Y-%m-%dT%H:%M:%S.%3Z"
    repository: 'https://github.com/percona/percona-server-mongodb-operator'
    alm-examples: >-  

spec:
  displayName: Percona Distribution for MongoDB Operator
  provider:
    name: Percona
    url: https://www.percona.com/
  keywords:
    - mongodb
    - percona
    - database
    - replicaset
    - shard
  description: |-
      ## Percona is Cloud Native
  
      The Percona Distribution for MongoDB Kubernetes Operator automates the creation, modification, or deletion of items in your Percona Server for MongoDB environment.
      The Operator contains the necessary Kubernetes settings to maintain a consistent Percona Server for MongoDB
      instance modification, or deletion of items in your Percona Server for MongoDB environment.
      The Operator contains the necessary Kubernetes settings to maintain a consistent Percona Server for MongoDB instance.
  
  
      Consult the
      [documentation](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/index.html/)
      on the Percona Kubernetes Operator for Percona Server for MongoDB for
      complete details on capabilities and options.
  
  
      ### Supported Features
  
  
      * **Scale Your Cluster** - change the `size` parameter to [add or remove
      members](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/scaling.html)
      of the replica set. Three is the minimum recommended size for a functioning
      replica set.
  
  
      * **Add Monitoring** - [Percona Monitoring and Management (PMM) can be
      easily
      deployed](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/monitoring.html)
      to monitor your Percona Server for MongoDB replica set(s). The recommended
      installation process uses Helm, the package manager for Kubernetes.
  
  
      * **Automate Your Backups** - [configure automatic
      backups](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/backups.html)
      to run on a scheduled basis or run an on-demand backup at any time. Backups
      are performed using Percona Backup for MongoDB (PBM) and can be stored on
      local PVs or in any S3-compatible cloud storage provider.
  
      * **Physical Backups - [configure physical backups](https://docs.percona.com/percona-operator-for-mongodb/backups.html#physical)
  
      * **Automated volume expansion
      Kubernetes supports the Persistent Volume expansion as a stable feature since v1.24. Using it with the Operator
      previously involved manual operations. Now this is automated, and users can resize their PVCs by just changing
      the value of the resources.requests.storage option in the PerconaServerMongoDB custom resource.
      This feature is in a technical preview stage and is not recommended for production environments.
  
  
      ### Common Configurations
  
  
      * **Set Member as Arbiter** - [Set up a replica set which contains an
      arbiter](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/arbiter.html),
      which participates in elections but does not store any data.  This reduces
      storage costs while helping maintain replica set integrity.
  
  
      * **Expose Members Outside K8S** - [by appropriately configuring the
      ServiceType](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/expose.html)
      you can expose replica set members outside of Kubernetes or provide
      statically assigned IP addresses.
  
  
      * **Utilize Local Storage Options** - [with support for Local Storage you
      can mount existing data
      directories](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/storage.html)
      into your replica set managed by Kubernetes or utilize high performance
      hardware for local storage rather than network storage for your database.
  
  
      ### Before You Start
  
  
      Add the PSMDB user `Secret` to Kubernetes. User information must be placed
      in the data section of the `secrets.yaml`
  
      file with Base64-encoded logins and passwords for the user accounts.
  
  
      Below is a sample `secrets.yaml` file for the correct formatting.
  
  
      ```
  
      apiVersion: v1
  
      kind: Secret
  
      metadata:
      name: my-cluster-name-secrets
      type: Opaque
  
      data:
        MONGODB_BACKUP_USER: YmFja3Vw
        MONGODB_BACKUP_PASSWORD: YmFja3VwMTIzNDU2
        MONGODB_DATABASE_ADMIN_USER: ZGF0YWJhc2VBZG1pbgo=
        MONGODB_DATABASE_ADMIN_PASSWORD: ZGF0YWJhc2VBZG1pbjEyMzQ1Ngo=
        MONGODB_CLUSTER_ADMIN_USER: Y2x1c3RlckFkbWlu
        MONGODB_CLUSTER_ADMIN_PASSWORD: Y2x1c3RlckFkbWluMTIzNDU2
        MONGODB_CLUSTER_MONITOR_USER: Y2x1c3Rlck1vbml0b3I=
        MONGODB_CLUSTER_MONITOR_PASSWORD: Y2x1c3Rlck1vbml0b3IxMjM0NTY=
        MONGODB_USER_ADMIN_USER: dXNlckFkbWlu
        MONGODB_USER_ADMIN_PASSWORD: dXNlckFkbWluMTIzNDU2
        PMM_SERVER_API_KEY: dXNlckFkbWluMTIzNDU2
      ```
  
      ### Release Highlights
      * General availability of Physical Backups
      Two releases ago we added experimental support for Physical Backups and Restores to significantly reduce Recovery Time Objective (RTO ),
      especially for big data sets. With this release Percona announces the general availability of physical backups and restores for
      Percona Server for MongoDB with the Operator.
  
      * Automated volume expansion
      Kubernetes supports the Persistent Volume expansion as a stable feature since v1.24. Using it with the Operator previously involved
      manual operations. Now this is automated, and users can resize their PVCs by just changing the value of the resources.requests.storage
      option in the PerconaServerMongoDB custom resource. This feature is in a technical preview stage and is not recommended
      for production environments.
  
      * Support for MongoDB 7
      Starting from this release, MongoDB 7.0 is now supported. Read our take on top-5 changes in MongoDB version 7 in this blog post .
  
      * Support for ARM architecture (technical preview)
      ARM architecture meets the intensive growth of its usage nowadays, both in a segment of highly efficient cloud computing based on systems
      like AWS Graviton, and the Internet of Things or Edge. Officially certified images for ARM are now available for the Operator,
      as well as Percona Server for MongoDB and Percona Backup for MongoDB, while database monitoring based on PMM Client is yet to follow.
  
      * Fixing the overloaded allowUnsafeConfigurations flag
      In the previous Operator versions allowUnsafeConfigurations Custom Resource option was used to allow configuring a cluster
      with unsafe parameters, such as starting it with less than 3 replica set instances. In fact, setting this option to true
      resulted in a wide range of reduced safety features without the user’s explicit intent: disabling TLS,
      allowing backups in unhealthy clusters, etc.

  version: ''
  links:
  - name: Percona
    url: 'https://www.percona.com/'
  - name: Percona Kubernetes Operators Landing Page
    url: 'https://www.percona.com/software/percona-kubernetes-operators'
  - name: Documentation
    url: 'https://percona.github.io/percona-server-mongodb-operator/'
  - name: Github
    url: 'https://github.com/percona/percona-server-mongodb-operator'
  maintainers:
    - name: Percona
      email: info@percona.com
  icon:
    - base64data: >-
        PHN2ZyB3aWR0aD0iMjI3IiBoZWlnaHQ9IjE5NCIgdmlld0JveD0iMCAwIDIyNyAxOTQiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik01OS4yODk5IDE5My40M0w0My41NDk5IDE2NS4xMkw1Ny42NDk5IDEzOS43MUw0NS4wNjk5IDExNi45NUgxNi4zMjk5TDAuNjI5ODgzIDg5LjAxTDE2LjA1OTkgNjAuNzlINDkuMDA5OUw2Mi44Mjk5IDg1LjgzSDg4LjAxOTlMMTAyLjQxIDYwLjU2SDEzNC45NkwxNTAuMzUgODguNTJMMTM2LjI3IDExNC4wM0wxNDkuMjEgMTM2Ljc2TDE3OC4yMiAxMzYuODRMMTkzLjYzIDE2NC44OEwxNzguMSAxOTMuMDhMMTQ1Ljg4IDE5My4wNEwxMzEuMTQgMTY3LjQ4SDEwNi4wOUMxMDYuMDkgMTY3LjQ4IDkzLjAwOTkgMTkwLjQ4IDkxLjMxOTkgMTkzLjQzSDU5LjI2OTlINTkuMjg5OVpNNTEuNTA5OSAxNjguMTJMNjIuNTY5OSAxODcuNTdIODQuNjg5OUw3My41Nzk5IDE2OC4wNEw1MS41MTk5IDE2OC4xMkg1MS41MDk5Wk0xODMuODYgMTY3Ljk1QzE4Mi4xOCAxNjcuOTcgMTgwLjU3IDE2Ny45OSAxNzguOTYgMTY4TDE3My4wNSAxNjguMDVDMTY5Ljk5IDE2OC4wOCAxNjYuOTIgMTY4LjEgMTYzLjg2IDE2OC4xMkgxNjMuMzlMMTYzLjE2IDE2OC41M0MxNjAuNDEgMTczLjM5IDE1Ny42NSAxNzguMjUgMTU0Ljg4IDE4My4xMUwxNTIuNDggMTg3LjMzSDE3NC42TDE3NC44MyAxODYuOTJDMTc3LjAxIDE4My4wNiAxNzkuMjIgMTc5LjE5IDE4MS40MiAxNzUuMzFMMTgxLjM0IDE3NS4zNUMxODEuNTggMTc1LjAyIDE4MS45NCAxNzQuMzggMTgyLjYzIDE3My4xOEwxODUuNjIgMTY3LjkzTDE4My44NyAxNjcuOTVIMTgzLjg2Wk03OC40OTk5IDE2NC45Nkw4OS42OTk5IDE4NC41OUwxMDAuOTcgMTY0LjgzTDg5LjkyOTkgMTQ1LjQ4TDc4LjQ5OTkgMTY0Ljk2Wk0xMzYuMzggMTY0LjkzTDE0Ny40NSAxODQuMzRMMTU4LjM3IDE2NS4xOUwxNDcuMyAxNDUuNzdMMTM2LjM4IDE2NC45M1pNNTEuNDk5OSAxNjIuMjZMNzAuMTg5OSAxNjIuMTdMNjkuNDk5OSAxNjAuOTdDNjkuNDk5OSAxNjAuOTcgNjQuMzQ5OSAxNTEuOTMgNjEuNzQ5OSAxNDcuMzdMNjAuODY5OSAxNDUuODJMNTEuNDk5OSAxNjIuMjdWMTYyLjI2Wk0xNjYuNzggMTYyLjIyTDE4NS42NCAxNjIuMDZMMTg0Ljk3IDE2MC44N0MxODIuOCAxNTYuOTkgMTc5LjIgMTUwLjY5IDE3Ni45NSAxNDYuODFMMTc2LjI0IDE0NS41OUwxNjYuNzcgMTYyLjIySDE2Ni43OFpNMTA5LjI5IDE2MS42NkgxMzEuMjdMMTQyLjMzIDE0Mi4yMUgxMjAuOThMMTA5LjMgMTYxLjY2SDEwOS4yOVpNMTYxLjcyIDE1OS4zTDE3MS4yMiAxNDIuNkgxNTIuMkwxNjEuNzEgMTU5LjNIMTYxLjcyWk02Ni4zNTk5IDE0My40MUM2Ny4wNjk5IDE0NC42NyA2Ny45Mzk5IDE0Ni4yNSA2OC44Nzk5IDE0Ny45NEM3MC43ODk5IDE1MS4zOCA3Mi45NDk5IDE1NS4yOCA3NC40Njk5IDE1Ny44OUw3NS4xNjk5IDE1OS4wOUw3NS44Njk5IDE1Ny45Qzc3LjQxOTkgMTU1LjI1IDg0LjI3OTkgMTQzLjQzIDg0LjI3OTkgMTQzLjQzTDg0Ljk4OTkgMTQyLjIxSDY1LjY3OTlMNjYuMzU5OSAxNDMuNDJWMTQzLjQxWk0xMDQuMjEgMTU4LjhMMTE0LjE1IDE0Mi4yQzExNC4xNSAxNDIuMiAxMDkuMDQgMTQyLjIgMTA3LjIxIDE0Mi4ySDk0Ljc5OTlMMTA0LjIyIDE1OC43OUwxMDQuMjEgMTU4LjhaTTY2LjY0OTkgMTM0Ljc5TDY1LjcwOTkgMTM2LjY4TDg4LjAyOTkgMTM2LjRMOTkuMTE5OSAxMTYuOTFINzUuNDc5OUM3NS40Nzk5IDExNi45MSA2OS41Mjk5IDEyOC45NyA2Ni42NDk5IDEzNC43OVpNMTIwLjk3IDEzNi4zNkgxNDIuMzJMMTQxLjYzIDEzNS4xNUMxMzguMjUgMTI5LjIxIDEzNC44NyAxMjMuMjggMTMxLjUgMTE3LjM0TDEzMS4yNyAxMTYuOTNIMTA5LjMxTDEyMC45NyAxMzYuMzZaTTEwMy41IDEyMC45NUMxMDEuMjQgMTI0Ljg2IDk3LjYyOTkgMTMxLjIzIDk1LjQ1OTkgMTM1LjE1TDk0Ljc4OTkgMTM2LjM2SDk2LjE2OTlDMTAxLjcgMTM2LjM1IDEwNy4yMiAxMzYuMzUgMTEyLjczIDEzNi4zNUgxMTQuMTZMMTA0LjE5IDExOS43N0wxMDMuNSAxMjAuOTZWMTIwLjk1Wk02MC44Mjk5IDEzMy40Mkw2OC45Njk5IDExNi45OEg1MS43NTk5TDYwLjgyOTkgMTMzLjQyWk0yMi45OTk5IDExMS4wOUw0MS43MDk5IDExMS4wNEwzMi4zNDk5IDk0LjYyTDIyLjk4OTkgMTExLjFMMjIuOTk5OSAxMTEuMDlaTTEwOS45MiAxMTEuMDVIMTMxLjI4TDE0Mi4xNCA5MS42SDEyMS4wMkwxMDkuOTIgMTExLjA1Wk03NS40NTk5IDExMS4wNUg5OS4xMjk5TDg4LjA2OTkgOTEuNkg2NS44NTk5TDc1LjQ1OTkgMTExLjA1Wk01MS44NTk5IDExMS4wMkg2OC45Mzk5TDYxLjAxOTkgOTQuOTFMNTEuODU5OSAxMTEuMDJaTTk0Ljc3OTkgOTEuNjhMMTA0LjUgMTA4Ljc3TDExNC4zIDkxLjZMOTQuNzc5OSA5MS42OFpNNi45Mzk4OCA4OC43MkwxNy45ODk5IDEwOC4xTDI5LjA1OTkgODguNjhMMTcuOTg5OSA2OS4yOEw2LjkzOTg4IDg4LjcyWk00Ni43ODk5IDEwOC4wOUw1Ni4xNDk5IDkxLjY1SDM3LjQxOTlMNDYuNzc5OSAxMDguMDlINDYuNzg5OVpNMzQuMDg5OSA4NS43OUg1Ni4xNzk5TDQ1LjExOTkgNjYuMzRIMjMuMDM5OUwzNC4wODk5IDg1Ljc5Wk0xMjAuOTkgODUuNzZIMTQyLjM0TDEzMS4yOSA2Ni4zM0gxMDkuMzRMMTIwLjk5IDg1Ljc2Wk05NC44MDk5IDg1LjczSDExNC4xOEwxMDQuMjQgNjkuMTdMOTQuODA5OSA4NS43M1oiIGZpbGw9InVybCgjcGFpbnQwX2xpbmVhcl8xMjAyXzExNDU3KSIvPgo8cGF0aCBvcGFjaXR5PSIwLjUiIGQ9Ik0xMDkuNzcgMTc1LjA5SDEyNy41OEwxMzMuNDMgMTg1LjIySDEwNC4wNEwxMDkuNzcgMTc1LjA5WiIgZmlsbD0iIzYyQUVGRiIvPgo8cGF0aCBvcGFjaXR5PSIwLjUiIGQ9Ik00OS45NDk5IDE0MC4wNkwyOS43Mjk5IDE3NS4wOUg0MS4wNjk5TDQ2Ljc1OTkgMTg1LjIySDEyLjE1OTlMNDQuMjA5OSAxMjkuNzNMNDkuOTQ5OSAxNDAuMDZaIiBmaWxsPSIjNjJBRUZGIi8+CjxwYXRoIG9wYWNpdHk9IjAuNSIgZD0iTTE5NS45NiAxNzUuMDlIMjA4LjVMMTE5LjEyIDIwLjI3TDg1LjI5OTggNzguODRMNzMuNTk5OSA3OC44M0wxMTkuMTIgMEwyMjYuMDYgMTg1LjIySDE5MC4zNEwxOTUuOTYgMTc1LjA5WiIgZmlsbD0iIzYyQUVGRiIvPgo8ZGVmcz4KPGxpbmVhckdyYWRpZW50IGlkPSJwYWludDBfbGluZWFyXzEyMDJfMTE0NTciIHgxPSIxNjMuNjIiIHkxPSI2MC40IiB4Mj0iMjAuOTE5OSIgeTI9IjIwMy4xMSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgo8c3RvcCBvZmZzZXQ9IjAuMDMiIHN0b3AtY29sb3I9IiM0MzlFRkYiLz4KPHN0b3Agb2Zmc2V0PSIwLjE2IiBzdG9wLWNvbG9yPSIjM0I5NEY0Ii8+CjxzdG9wIG9mZnNldD0iMC4zOSIgc3RvcC1jb2xvcj0iIzI2N0NENyIvPgo8c3RvcCBvZmZzZXQ9IjAuNjIiIHN0b3AtY29sb3I9IiMwRTVGQjUiLz4KPC9saW5lYXJHcmFkaWVudD4KPC9kZWZzPgo8L3N2Zz4=
      mediatype: image/svg+xml

  customresourcedefinitions:
    owned:
      - description: Instance of a Percona Server for MongoDB replica set
        displayName: PerconaServerMongoDB
        kind: PerconaServerMongoDB
        name: perconaservermongodbs.psmdb.percona.com
        version: v1
        specDescriptors: [ ]
        statusDescriptors: [ ]
        resources:
          - version: v1
            kind: Deployment
            name: ''
          - version: v1
            kind: Service
            name: ''
          - version: v1
            kind: ReplicaSet
            name: ''
          - version: v1
            kind: Pod
            name: ''
          - version: v1
            kind: Secret
            name: ''
          - version: v1
            kind: ConfigMap
            name: ''
      - description: Instance of a Percona Server for MongoDB Backup
        displayName: PerconaServerMongoDBBackup
        kind: PerconaServerMongoDBBackup
        name: perconaservermongodbbackups.psmdb.percona.com
        version: v1
        specDescriptors: [ ]
        statusDescriptors: [ ]
        resources:
          - version: v1
            kind: Deployment
            name: ''
          - version: v1
            kind: Service
            name: ''
          - version: v1
            kind: ReplicaSet
            name: ''
          - version: v1
            kind: Pod
            name: ''
          - version: v1
            kind: Secret
            name: ''
          - version: v1
            kind: ConfigMap
            name: ''
      - description: Instance of a Percona Server for MongoDB Restore
        displayName: PerconaServerMongoDBRestore
        kind: PerconaServerMongoDBRestore
        name: perconaservermongodbrestores.psmdb.percona.com
        version: v1
        specDescriptors: [ ]
        statusDescriptors: [ ]
        resources:
          - version: v1
            kind: Deployment
            name: ''
          - version: v1
            kind: Service
            name: ''
          - version: v1
            kind: ReplicaSet
            name: ''
          - version: v1
            kind: Pod
            name: ''
          - version: v1
            kind: Secret
            name: ''
          - version: v1
            kind: ConfigMap
            name: ''
    required: [ ]
    install:
      strategy: deployment
  minKubeVersion: 1.28.0
  maturity: stable
  replaces: ''
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: true
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  install:
    strategy: deployment
    spec:
      permissions:
      deployments: