#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
set_debug

max_conn=17

create_infra $namespace

desc 'create secrets and start client'
kubectl_bin apply \
	-f "$test_dir/conf/secrets_with_tls.yml" \
	-f "$conf_dir/client.yml"

desc 'create custom RuntimeClass'
if version_gt "1.19" && [ $EKS -ne 1 ]; then
	cat "$conf_dir/container-rc.yaml" | $sed 's/docker/runc/g' | kubectl_bin apply -f -
elif version_gt "1.24" && [ $EKS -eq 1 ]; then
	cat "$conf_dir/container-rc.yaml" | $sed 's/docker/runc/g' | kubectl_bin apply -f -
else
	kubectl_bin apply -f "$conf_dir/container-rc.yaml"
fi

cluster="some-name-rs0"
desc "create first PSMDB cluster $cluster"
apply_cluster $conf_dir/$cluster.yml

desc 'check if all 3 Pods started'
wait_for_running $cluster 3

desc 'check if service and statefulset created with expected config'
compare_kubectl statefulset/$cluster
compare_kubectl service/$cluster

desc 'check if users created'

secret_name="some-users"

user=$(getUserData "$secret_name" "MONGODB_USER_ADMIN_USER")
pass=$(getUserData "$secret_name" "MONGODB_USER_ADMIN_PASSWORD")
compare_mongo_user "$user:$pass@$cluster.$namespace" "userAdmin"

user=$(getUserData "$secret_name" "MONGODB_BACKUP_USER")
pass=$(getUserData "$secret_name" "MONGODB_BACKUP_PASSWORD")
compare_mongo_user "$user:$pass@$cluster.$namespace" "backup"

user=$(getUserData "$secret_name" "MONGODB_CLUSTER_ADMIN_USER")
pass=$(getUserData "$secret_name" "MONGODB_CLUSTER_ADMIN_PASSWORD")
compare_mongo_user "$user:$pass@$cluster.$namespace" "clusterAdmin"

user=$(getUserData "$secret_name" "MONGODB_CLUSTER_MONITOR_USER")
pass=$(getUserData "$secret_name" "MONGODB_CLUSTER_MONITOR_PASSWORD")
compare_mongo_user "$user:$pass@$cluster.$namespace" "clusterMonitor"

# check that test user don't have access
(run_mongo 'db.runCommand({connectionStatus:1,showPrivileges:true})' "test:test@$cluster.$namespace" || :) 2>&1 \
	| grep 'Authentication failed'

desc 'create user'
run_mongo \
	'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
	"userAdmin:userAdmin123456@$cluster.$namespace"
sleep 2

desc 'write data, read from all'
run_mongo \
	'use myApp\n db.test.insert({ x: 100500 })' \
	"myApp:myPass@$cluster.$namespace"
compare_mongo_cmd "find" "myApp:myPass@$cluster-0.$cluster.$namespace"
compare_mongo_cmd "find" "myApp:myPass@$cluster-1.$cluster.$namespace"
compare_mongo_cmd "find" "myApp:myPass@$cluster-2.$cluster.$namespace"

desc 'check number of connections'
conn_count=$(run_mongo 'db.serverStatus().connections.current' "clusterAdmin:clusterAdmin123456@$cluster.$namespace" | egrep -v 'I NETWORK|W NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match|bye')
if [ ${conn_count} -gt ${max_conn} ]; then
	exit 1
fi

desc 'kill Primary Pod, check reelection, check data'
initial_primary=$(get_mongo_primary "clusterAdmin:clusterAdmin123456@$cluster.$namespace" "$cluster")
kubectl_bin delete pods --grace-period=0 --force $initial_primary
wait_for_running $cluster 3
changed_primary=$(get_mongo_primary "clusterAdmin:clusterAdmin123456@$cluster.$namespace" "$cluster")
[ "$initial_primary" != "$changed_primary" ]
run_mongo \
	'use myApp\n db.test.insert({ x: 100501 })' \
	"myApp:myPass@$cluster.$namespace"
compare_mongo_cmd "find" "myApp:myPass@$cluster-0.$cluster.$namespace" "-2nd"
compare_mongo_cmd "find" "myApp:myPass@$cluster-1.$cluster.$namespace" "-2nd"
compare_mongo_cmd "find" "myApp:myPass@$cluster-2.$cluster.$namespace" "-2nd"

desc 'check if possible to create second cluster'
cluster2="another-name-rs0"
apply_cluster $test_dir/conf/$cluster2.yml
desc 'check if all 3 Pods started'
wait_for_running $cluster2 3
desc 'check if service and statefulset created with expected config'
compare_kubectl statefulset/$cluster2
compare_kubectl service/$cluster2

desc 'write data, read from all'
run_mongo \
	'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
	"userAdmin:userAdmin123456@$cluster2.$namespace"
run_mongo \
	'use myApp\n db.test.insert({ x: 100502 })' \
	"myApp:myPass@$cluster2.$namespace"
compare_mongo_cmd "find" "myApp:myPass@$cluster2-0.$cluster2.$namespace" "-3rd"
compare_mongo_cmd "find" "myApp:myPass@$cluster2-1.$cluster2.$namespace" "-3rd"
compare_mongo_cmd "find" "myApp:myPass@$cluster2-2.$cluster2.$namespace" "-3rd"

desc 'check if mongod log files exist in pod'
log_files=$(kubectl exec "${cluster2}-0" -c "mongod" -- ls "/data/db/logs" 2>/dev/null)
if ! echo "$log_files" | grep -q 'mongod.log' || ! echo "$log_files" | grep -q 'mongod.full.log'; then
	echo "error, files found:"
	echo "$log_files"
	return 1
fi
echo "found mongod.log and mongod.full.log in /data/db/logs"

desc 'check for passwords leak'
check_passwords_leak

desc 'delete custom RuntimeClass'
kubectl_bin delete -f "$conf_dir/container-rc.yaml"
destroy $namespace

desc 'test passed'
