apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBRestore
metadata:
  name:
spec:
  clusterName: some-name
  backupName:
  storageName: minio
  pitr:
    pitrType:
    date:
  backupSource:
    destination: s3://BACKUP-NAME
