// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VersionMetadataVersion MetadataVersion represents metadata for a given version.
//
// swagger:model versionMetadataVersion
type VersionMetadataVersion struct {

	// ImageInfo holds information about the docker image for this version.
	ImageInfo *VersionVersion `json:"imageInfo,omitempty"`

	// Recommended is the recommended version for a given component.
	Recommended map[string]string `json:"recommended,omitempty"`

	// Supported holds semver constraint per component, such as ">= 1.0, < 1.4".
	Supported map[string]string `json:"supported,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this version metadata version
func (m *VersionMetadataVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImageInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VersionMetadataVersion) validateImageInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.ImageInfo) { // not required
		return nil
	}

	if m.ImageInfo != nil {
		if err := m.ImageInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("imageInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VersionMetadataVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionMetadataVersion) UnmarshalBinary(b []byte) error {
	var res VersionMetadataVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
