#!/bin/bash

set -o errexit

test_dir="$(realpath "$(dirname "$0")")"
. "${test_dir}/../functions"
set_debug

main() {
	create_infra "$namespace"

	desc 'create secrets and start client'
	kubectl_bin apply -f "$conf_dir/secrets.yml"
	kubectl_bin apply -f "$conf_dir/client_with_tls.yml"

	cluster="some-name"
	desc "create first PSMDB cluster $cluster"
	apply_cluster "$test_dir/conf/$cluster.yml"

	desc 'check if all Pods started'
	wait_for_running $cluster-rs0 3
	wait_for_running $cluster-cfg 3 "false"
	wait_for_running $cluster-mongos 3

	desc 'save certificate created by operator'
	kubectl_bin get secret $cluster-ssl -o yaml | yq 'del(.metadata)' | yq ".metadata.name=\"$cluster-ssl\"" >"$tmp_dir/custom_tls_secret.yaml"

	kubectl_bin delete psmdb $cluster

	desc "Wait for delete cluster $cluster"
	wait_for_delete psmdb/$cluster 180

	desc "create custom certificate"
	kubectl_bin apply -f "$tmp_dir/custom_tls_secret.yaml"

	desc "recreate PSMDB cluster $cluster with custom certificate"
	apply_cluster "$test_dir/conf/$cluster.yml"

	wait_for_running $cluster-rs0 3
	wait_for_running $cluster-cfg 3 "false"
	wait_for_running $cluster-mongos 3

	compare_kubectl statefulset/${cluster}-rs0
	compare_kubectl statefulset/${cluster}-cfg
	compare_kubectl statefulset/${cluster}-mongos

	destroy "$namespace"

	desc 'test passed'
}

main
