apiVersion: v1
kind: Secret
metadata:
  name: openldap
type: Opaque
stringData:
  adminpassword: adminpassword
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ldap-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-ca
spec:
  isCA: true
  commonName: openldap
  secretName: ldap-ca
  issuerRef:
    name: ldap-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: ldap-setup
          image: osixia/openldap:latest
          command: ["/bin/bash"]
          args:
            - -c
            - |
              echo "Waiting for LDAP server to be ready..."
              sleep 60
              
              echo "Adding LDAP structure..."
              ldapadd -x -H ldap://localhost:389 -D "cn=admin,dc=ldap,dc=local" -w adminpassword <<EOF
              dn: ou=perconadba,dc=ldap,dc=local
              objectClass: organizationalUnit
              ou: perconadba

              dn: uid=percona,ou=perconadba,dc=ldap,dc=local
              objectClass: inetOrgPerson
              uid: percona
              cn: percona
              sn: percona
              userPassword: password

              dn: cn=admin,ou=perconadba,dc=ldap,dc=local
              objectClass: groupOfUniqueNames
              cn: admin
              uniqueMember: uid=percona,ou=perconadba,dc=ldap,dc=local
              EOF
              
              echo "LDAP structure added successfully"
              sleep infinity
          env:
            - name: LDAP_DOMAIN
              value: "ldap.local"
            - name: LDAP_ORGANISATION
              value: "ldap.local"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
        - name: openldap
          image: osixia/openldap:latest
          imagePullPolicy: "Always"
          args: ["--copy-service"]
          env:
            - name: LDAP_DOMAIN
              value: "ldap.local"
            - name: LDAP_ORGANISATION
              value: "ldap.local"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
            - name: LDAP_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
            - name: LDAP_READONLY_USER
              value: "true"
            - name: LDAP_READONLY_USER_USERNAME
              value: "readonly"
            - name: LDAP_READONLY_USER_PASSWORD
              value: "readonlypass"
            - name: CONTAINER_LOG_LEVEL
              value: "info"
            - name: LDAP_LDAP_PORT_NUMBER
              value: "389"
            - name: LDAP_LDAPS_PORT_NUMBER
              value: "636"
            - name: LDAP_TLS
              value: "true"
            - name: LDAP_TLS_VERIFY_CLIENT
              value: "never"
            - name: LDAP_TLS_CRT_FILENAME
              value: "tls.crt"
            - name: LDAP_TLS_KEY_FILENAME
              value: "tls.key"
            - name: LDAP_TLS_CA_CRT_FILENAME
              value: "ca.crt"
          ports:
            - name: tls-ldap
              containerPort: 636
            - name: tcp-ldap
              containerPort: 389
          readinessProbe:
            tcpSocket:
              port: 636
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 636
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: ldap-ca
              mountPath: /container/service/slapd/assets/certs
      volumes:
        - name: ldap-ca
          secret:
            secretName: ldap-ca
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tls-ldap
      port: 636
      targetPort: tls-ldap
    - name: tcp-ldap
      port: 389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: openldap