#!/bin/bash

set -o errexit

test_dir=$(realpath "$(dirname "$0")")
. "${test_dir}/../functions"
set_debug

if [ -z "$GKE" ]; then
	desc 'Skip test. Set GKE=1 to run on GKE cluster.'
	exit 0
fi

if [ -n "$SKIP_BACKUPS_TO_AWS_GCP_AZURE" ]; then
	desc 'Skip tests related to GCP Cloud Storage'
	exit 0
fi

if [ -z "$GCP_PROJECT" ] || [ -z "$GCS_WI_SERVICE_ACCOUNT" ]; then
	desc 'Skip test. Set GCP_PROJECT and GCS_WI_SERVICE_ACCOUNT for GCS Workload Identity test.'
	exit 0
fi

create_infra "${namespace}"

desc 'create GCP workload identity binding'
kubectl_bin annotate serviceaccount \
	--namespace "${namespace}" \
	"${namespace}-psmdb-db" \
	"iam.gke.io/gcp-service-account=${GCS_WI_SERVICE_ACCOUNT}"

desc 'create PSMDB cluster without GCS credentialsSecret'
cluster="some-name"
kubectl_bin apply -f "${test_dir}/conf/${cluster}.yml"
kubectl_bin apply -f "${conf_dir}/client_with_tls.yml"

desc 'check if all pods started'
wait_for_running "${cluster}-rs0" 3
wait_cluster_consistency "${cluster}"

sleep 60
wait_for_pbm_operations "${cluster}"

desc 'write test data'
run_mongo \
	'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
	"userAdmin:userAdmin123456@${cluster}-rs0.${namespace}"
sleep 1
run_mongo \
	'use myApp\n db.test.insert({ x: 100500 })' \
	"myApp:myPass@${cluster}-rs0.${namespace}"
sleep 5
compare_mongo_cmd "find" "myApp:myPass@${cluster}-rs0-0.${cluster}-rs0.${namespace}"
compare_mongo_cmd "find" "myApp:myPass@${cluster}-rs0-1.${cluster}-rs0.${namespace}"
compare_mongo_cmd "find" "myApp:myPass@${cluster}-rs0-2.${cluster}-rs0.${namespace}"

desc 'run GCS backup with workload identity'
backup_name="backup-gcs-wi"
run_backup gcs-wi "${backup_name}" 'physical'
wait_backup "${backup_name}"
check_backup_in_storage "${backup_name}" gcs rs0

desc 'drop and restore'
run_mongo 'use myApp\n db.test.drop()' "myApp:myPass@${cluster}-rs0.${namespace}"
run_restore "${backup_name}"
run_recovery_check "${backup_name}" "${cluster}"

destroy "$namespace"

desc 'test passed'
