apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: cross-site-sharded-main
spec:
  #platform: openshift
  unmanaged: false
  image:
  imagePullPolicy: Always
  sharding:
    enabled: true
    configsvrReplSet:
      expose:
        enabled: true
        exposeType: LoadBalancer
      size: 3
      affinity:
        antiAffinityTopologyKey: none
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi

    mongos:
      size: 3
      affinity:
        antiAffinityTopologyKey: none
      expose:
        enabled: true
        exposeType: LoadBalancer
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
        rateLimit: 100
  mongod:
    net:
      hostPort: 0
      port: 27017
    operationProfiling:
      mode: slowOp
      rateLimit: 1
      slowOpThresholdMs: 100
    security:
      enableEncryption: true
      redactClientLogData: false
    setParameter:
      ttlMonitorSleepSecs: 128
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        collectionConfig:
          blockCompressor: snappy
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        indexConfig:
          prefixCompression: true

  replsets:
  - name: rs0
    expose:
      enabled: true
      exposeType: LoadBalancer
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  - name: rs1
    expose:
      enabled: true
      exposeType: LoadBalancer
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  - name: rs2
    expose:
      enabled: true
      exposeType: LoadBalancer
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  secrets:
    key: some-key
    users: some-users
    ssl: some-name-ssl