apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  sharding:
    enabled: true
    configsvrReplSet:
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
      expose:
        enabled: false
        exposeType: ClusterIP
    mongos:
      size: 3
      expose:
        exposeType: ClusterIP
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    expose:
      enabled: false
      exposeType: ClusterIP
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  - name: rs1
    affinity:
      antiAffinityTopologyKey: none
    expose:
      enabled: false
      exposeType: ClusterIP
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  secrets:
    users: some-users
