apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - percona.com/delete-psmdb-pvc
  name: some-name
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  backup:
    enabled: true
    image:
    storages:
      gcp-cs-native:
        type: gcs
        gcs:
          credentialsSecret: gcp-cs-sa-key-secret
          bucket: operator-testing
          prefix: psmdb-demand-backup-incremental-gcp-native
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi
    expose:
      enabled: false
      type: ClusterIP
    size: 3
    configuration: |
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
  secrets:
    users: some-users
