apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: <namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: percona-server-mongodb-operator
    namespace: <namespace>
