apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBBackup
metadata:
  finalizers:
    - percona.com/delete-backup
  name: backup-gcp-cs-s3
spec:
  clusterName: some-name
  storageName: gcp-cs-s3
