apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBRestore
metadata:
  name:
spec:
  clusterName: some-name
  storageName:
  backupSource:
    destination: s3://BACKUP-NAME
    s3:
      credentialsSecret: s3-secret
      region: us-east-1
      bucket: operator-testing
      endpointUrl: http://s3-storage-all-in-one:8333/
      insecureSkipTLSVerify: false
