apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  allowUnsafeConfigurations: true
  backup:
    enabled: false
    image: perconalab/percona-server-mongodb-operator:main-backup
  replsets:
  - name: rs0
    size: 3
    expose:
      enabled: true
      exposeType: ClusterIP
    splitHorizons:
      some-name-rs0-0:
        external: some-name-rs0-0.clouddemo.xyz
      some-name-rs0-1:
        external: some-name-rs0-1.clouddemo.xyz
      some-name-rs0-2:
        external: some-name-rs0-2.clouddemo.xyz
      some-name-rs0-3:
        external: some-name-rs0-3.clouddemo.xyz
      some-name-rs0-4:
        external: some-name-rs0-4.clouddemo.xyz
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 0.5G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
  secrets:
    users: some-users
