apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  backup:
    enabled: false
    image: perconalab/percona-server-mongodb-operator:main-backup
  replsets:
  - name: rs0
    size: 3
    expose:
      enabled: true
      type: ClusterIP
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 0.5G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
  secrets:
    users: some-users