#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
set_debug

check_cr_config() {
	local cluster="$1"

	desc "create PSMDB cluster $cluster"
	apply_cluster $test_dir/conf/$cluster.yml

	desc 'check if at least 1 Pod started'
	wait_for_running $cluster 1 "false"

	desc 'check if statefulset created with expected config'
	compare_kubectl statefulset/$cluster

	desc 'change resources'
	cat_config $test_dir/conf/$cluster.yml \
		| sed -e 's/300m/600m/' \
		| sed -e 's/500M/1G/' \
		| sed -e 's/0.5G/1G/' \
		| kubectl_bin apply -f-
	sleep 20

	desc 'check if statefulset created with expected config'
	compare_kubectl statefulset/$cluster "-increased"

	desc "delete PSMDB cluster $cluster"
	kubectl_bin delete \
		-f $test_dir/conf/$cluster.yml
}

no_storage() {
	local cluster="no-storage-rs0"

	desc "create PSMDB cluster $cluster"
	# volumeSpec is a required field, so the API server must reject a CR without it
	local apply_out
	apply_out=$(cat_config $test_dir/conf/$cluster.yml | kubectl apply -f - 2>&1 || :)
	echo "$apply_out"
	echo "$apply_out" | grep "volumeSpec: Required value"
}

main() {
	create_infra $namespace

	desc 'create secrets'
	kubectl_bin apply -f $conf_dir/secrets.yml

	desc 'check if possible to create cluster without CPU/Memory limits'
	check_cr_config "no-limits-rs0"

	desc 'check if possible to create cluster without CPU/Memory requests'
	check_cr_config "no-requests-rs0"

	desc 'check if possible to create cluster without CPU/Memory requests and limits'
	check_cr_config "no-requests-no-limits-rs0"

	desc 'check that creating a cluster without storage size is rejected'
	no_storage

	destroy $namespace

	desc 'test passed'
}

main
