#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
set_debug

check_cr_config() {
	local cluster="$1"

	desc "create PSMDB cluster $cluster"
	apply_cluster $test_dir/conf/$cluster.yml

	desc 'check if all 3 Pods started'
	wait_for_running $cluster 3 "false"

	desc 'check if service and statefulset created with expected config'
	compare_kubectl statefulset/$cluster
	compare_kubectl service/$cluster-0

	local URI="$(get_service_ip $cluster-0),$(get_service_ip $cluster-1),$(get_service_ip $cluster-2)"
	# Wait a bit longer for ELB availability on Openshift
	sleep 30

	desc 'create user myApp'
	run_mongo \
		'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
		"userAdmin:userAdmin123456@$URI" \
		"mongodb" ":27017"
	sleep 10

	desc 'write data, read from all'
	run_mongo \
		'use myApp\n db.test.insert({ x: 100500 })' \
		"myApp:myPass@$URI" \
		"mongodb" ":27017"
	sleep 30
	compare_mongo_cmd "find" "myApp:myPass@$(get_service_ip $cluster-0)" "" ":27017"
	compare_mongo_cmd "find" "myApp:myPass@$(get_service_ip $cluster-1)" "" ":27017"
	compare_mongo_cmd "find" "myApp:myPass@$(get_service_ip $cluster-2)" "" ":27017"

	if [[ $cluster == "node-port-rs0" ]]; then
		desc 'add service-per-pod label and annotation'
		old_node_port=$(kubectl_bin get svc node-port-rs0-0 -o 'jsonpath={.spec.ports[0].nodePort}')
		kubectl_bin patch psmdb node-port --type=json --patch '[
		{
			"op": "add",
			"path": "/spec/replsets/0/expose/annotations",
			"value": {
				"test": "service-per-pod",
			}
		},
		{
			"op": "add",
			"path": "/spec/replsets/0/expose/labels",
			"value": {
				"test": "service-per-pod",
			}
		}]'
		sleep 5 # waiting for reconcile

		desc 'check if service created with expected config'
		compare_kubectl service/node-port-rs0-0 "-updated"
		current_node_port=$(kubectl_bin get svc node-port-rs0-0 -o 'jsonpath={.spec.ports[0].nodePort}')
		if [[ $current_node_port != "$old_node_port" ]]; then
			echo "Node port changed from ${old_node_port} to ${current_node_port}"
			exit 1
		fi
	fi

	desc "delete PSMDB cluster $cluster"
	kubectl_bin delete \
		-f $test_dir/conf/$cluster.yml
}

check_service() {
	state=$1
	svc_name=$2
	if [ $state = "present" ]; then
		echo -n "check that $svc_name was created"
		local timeout=0
		until kubectl_bin get service/$svc_name -o 'jsonpath={.spec.type}' 2>&1 | grep -vq NotFound; do
			sleep 1
			timeout=$((timeout + 1))
			echo -n '.'
			if [[ ${timeout} -gt 900 ]]; then
				echo "Waiting timeout has been reached. Service $svc_name is not present. Exiting..."
				exit 1
			fi
		done
		echo ".OK"
	elif [ $state = "removed" ]; then
		echo -n "check that $svc_name was removed"
		if [[ -z $(kubectl_bin get service/$svc_name -o 'jsonpath={.spec.type}' 2>&1 | grep NotFound) ]]; then
			echo "$svc_name was not removed."
			exit 1
		else
			echo ".OK"
		fi
	else
		echo "unknown state $state"
	fi
}


main() {
	create_infra $namespace
	deploy_cert_manager

	desc 'create secrets and start client'
	kubectl_bin apply -f $conf_dir/secrets.yml
	apply_client $conf_dir/client.yml

	desc 'check ClusterIP'
	check_cr_config "cluster-ip-rs0"

	desc 'check LoadBalancer'
	check_cr_config "local-balancer-rs0"

	desc 'check NodePort'
	check_cr_config "node-port-rs0"

	desc 'check Mongos in sharded cluster'
	local cluster=some-name
	apply_cluster "$test_dir/conf/sharded.yml"
	wait_for_running $cluster-rs0 3
	wait_for_running $cluster-cfg 3 "false"
	wait_for_running $cluster-mongos 3

	desc 'enabling servicePerPod for mongos'
	kubectl patch psmdb some-name --type=merge -p '{"spec":{"sharding":{"mongos":{"expose":{"servicePerPod":true}}}}}'
	wait_for_running $cluster-mongos 3
	check_service present $cluster-mongos-0
	check_service present $cluster-mongos-1
	check_service present $cluster-mongos-2
	check_service removed $cluster-mongos

	destroy $namespace

	desc 'test passed'
}

main
