apiVersion: v1
kind: Service
metadata:
  annotations:
    test: one-pod
  labels:
    app.kubernetes.io/instance: one-pod
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
    test: one-pod
  name: one-pod-rs0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: one-pod
spec:
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app.kubernetes.io/instance: one-pod
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  sessionAffinity: None
  type: ClusterIP
