apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app.kubernetes.io/component: mongod
    app.kubernetes.io/instance: one-pod
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    app.kubernetes.io/replset: rs0
  name: one-pod-rs0
  ownerReferences:
    - controller: true
      kind: PerconaServerMongoDB
      name: one-pod
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongod
      app.kubernetes.io/instance: one-pod
      app.kubernetes.io/managed-by: percona-server-mongodb-operator
      app.kubernetes.io/name: percona-server-mongodb
      app.kubernetes.io/part-of: percona-server-mongodb
      app.kubernetes.io/replset: rs0
  serviceName: one-pod-rs0
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: mongod
        app.kubernetes.io/instance: one-pod
        app.kubernetes.io/managed-by: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb
        app.kubernetes.io/part-of: percona-server-mongodb
        app.kubernetes.io/replset: rs0
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: mongod
                  app.kubernetes.io/instance: one-pod
                  app.kubernetes.io/managed-by: percona-server-mongodb-operator
                  app.kubernetes.io/name: percona-server-mongodb
                  app.kubernetes.io/part-of: percona-server-mongodb
                  app.kubernetes.io/replset: rs0
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=rs0
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --clusterAuthMode=keyFile
            - --keyFile=/etc/mongodb-secrets/mongodb-key
            - --slowms=100
            - --profile=1
            - --rateLimit=100
            - --wiredTigerCacheSizeGB=0.25
            - --wiredTigerCollectionBlockCompressor=snappy
            - --wiredTigerJournalCompressor=snappy
            - --wiredTigerIndexPrefixCompression=true
            - --setParameter
            - ttlMonitorSleepSecs=60
            - --setParameter
            - wiredTigerConcurrentReadTransactions=128
            - --setParameter
            - wiredTigerConcurrentWriteTransactions=128
          command:
            - /data/db/ps-entry.sh
          env:
            - name: SERVICE_NAME
              value: one-pod
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLSET
              value: rs0
          envFrom:
            - secretRef:
                name: internal-one-pod-users
                optional: false
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - mongodb-healthcheck
                - k8s
                - liveness
                - --startupDelaySeconds
                - "7200"
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: mongod
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          readinessProbe:
            failureThreshold: 8
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 300m
              memory: 500M
            requests:
              cpu: 300m
              memory: 500M
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
            - mountPath: /etc/mongodb-secrets
              name: one-pod-mongodb-keyfile
              readOnly: true
            - mountPath: /etc/mongodb-ssl
              name: ssl
              readOnly: true
            - mountPath: /etc/mongodb-ssl-internal
              name: ssl-internal
              readOnly: true
          workingDir: /data/db
        - env:
            - name: PBM_AGENT_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGODB_BACKUP_USER
                  name: internal-one-pod-users
                  optional: false
            - name: PBM_AGENT_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_BACKUP_PASSWORD
                  name: internal-one-pod-users
                  optional: false
            - name: PBM_MONGODB_REPLSET
              value: rs0
            - name: PBM_MONGODB_PORT
              value: "27017"
          imagePullPolicy: Always
          name: backup-agent
          resources: {}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /init-entrypoint.sh
          imagePullPolicy: Always
          name: mongo-init
          resources:
            limits:
              cpu: 300m
              memory: 500M
            requests:
              cpu: 300m
              memory: 500M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongod-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - name: one-pod-mongodb-keyfile
          secret:
            defaultMode: 288
            optional: false
            secretName: one-pod-mongodb-keyfile
        - name: ssl
          secret:
            defaultMode: 288
            optional: true
            secretName: one-pod-ssl
        - name: ssl-internal
          secret:
            defaultMode: 288
            optional: true
            secretName: one-pod-ssl-internal
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: mongod-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
      status:
        phase: Pending
