#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
set_debug

write_document() {
	local cmp_postfix=$1
	local cluster_name="${2:-$cluster}"

	desc 'write initial data, read from all'
	run_mongo \
		'use myApp\n db.test.insert({ x: 100500 })' \
		"myApp:myPass@$cluster_name.$namespace"
	minikube_sleep
	compare_mongo_cmd "find" "myApp:myPass@$cluster_name-0.$cluster_name.$namespace" "$cmp_postfix"
	compare_mongo_cmd "find" "myApp:myPass@$cluster_name-1.$cluster_name.$namespace" "$cmp_postfix"
	compare_mongo_cmd "find" "myApp:myPass@$cluster_name-2.$cluster_name.$namespace" "$cmp_postfix"
}

write_initial_data() {
	desc 'create user myApp'
	run_mongo \
		'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
		"userAdmin:userAdmin123456@$cluster.$namespace"
	sleep 2
	write_document
}

reset_collection() {
	desc 'reset data'
	run_mongo \
		'use myApp\n db.test.remove({})' \
		"myApp:myPass@$cluster.$namespace"
	sleep 2
	write_document
}

run_backup() {
	local name=$1
	local idx=$2

	desc "run backup $name-$idx"
	cat $test_dir/conf/$name.yml \
		| $sed -e "s/name:/name: $name-$idx/" \
		| kubectl_bin apply -f -
	wait_backup "$name-$idx"
}

check_recovery() {
	local backup_name=$1
	local restore_type=$2
	local restore_date=$3
	local cmp_postfix=$4
	local backupSource=$5
	local cluster_name=${6-"$cluster"}
	local selective_collection=$7
	local restore_name="restore-${8:-"$backup_name"}"
	local restore_file="${9:-"restore.yml"}"

	local cluster
	cluster="$cluster_name-rs0"

	desc "write more data before restore by $restore_type"
	sleep 60
	run_mongo \
		"use myApp\n db.test.insert({ x: 100501 })" \
		"myApp:myPass@$cluster.$namespace"

	if [ -n "$selective_collection" ]; then
		run_mongo \
			"use myApp\n db.$selective_collection.drop()" \
			"myApp:myPass@$cluster.$namespace"
	fi
	desc 'waiting for chunks to be uploaded'
	sleep 120

	desc "check restore by $restore_type"
	if [ -z "$backupSource" ]; then
		cat "$test_dir/conf/$restore_file" \
			| $sed -e "s/name:/name: $restore_name/" \
			| $sed -e "s/backupName:/backupName: $backup_name/" \
			| $sed -e "s/clusterName:/clusterName: $cluster_name/" \
			| $sed -e "s/pitrType:/type: $restore_type/" \
			| if [ -z "$restore_date" ]; then $sed -e "/date:/d"; else $sed -e "s/date:/date: $restore_date/"; fi \
			| $sed -e "/backupSource/,+2d" \
			| if [ -n "$selective_collection" ]; then yq eval '.spec.selective = {"namespaces": ["myApp.test"], "withUsersAndRoles": true}'; else yq; fi \
			| kubectl_bin apply -f -
	else
		backup_dest=$(get_backup_dest "$backup_name")
		cat "$test_dir/conf/$restore_file" \
			| $sed -e "s/name:/name: $restore_name/" \
			| $sed -e "/backupName/d" \
			| $sed -e "s/clusterName:/clusterName: $cluster_name/" \
			| $sed -e "s/pitrType:/type: $restore_type/" \
			| if [ -z "$restore_date" ]; then $sed -e "/date:/d"; else $sed -e "s/date:/date: $restore_date/"; fi \
			| $sed -e "s|BACKUP-NAME|$backup_dest|" \
			| if [ -n "$selective_collection" ]; then yq eval '.spec.selective = {"namespaces": ["myApp.test"], "withUsersAndRoles": true}'; else yq; fi \
			| kubectl_bin apply -f -
	fi
	wait_restore "${restore_name/restore-/}" "$cluster_name"
	echo
	set -o xtrace

	if [ -n "$selective_collection" ]; then
		if [[ $(collection_exists "$selective_collection") == "true" ]]; then
			echo "Collection $selective_collection exists"
			exit 1
		fi
	fi
	compare_mongo_cmd "find" "myApp:myPass@$cluster-0.$cluster.$namespace" "$cmp_postfix"
	compare_mongo_cmd "find" "myApp:myPass@$cluster-1.$cluster.$namespace" "$cmp_postfix"
	compare_mongo_cmd "find" "myApp:myPass@$cluster-2.$cluster.$namespace" "$cmp_postfix"
}

collection_exists() {
	local collection=$1
	run_mongo \
		"use myApp\n JSON.stringify(db.getCollectionNames())" \
		"myApp:myPass@$cluster.$namespace" "" "" "--quiet" \
		| grep -v "switched to" \
		| jq "index(\"$collection\") != null"
}

run_recovery_check_namespace_remap() {
	local backup_name=$1
	local restore_date=$2
	local cluster_name=$3
	local database=$4
	local src_collection=$5
	local dst_collection=$6

	local cluster="$cluster_name-rs0"

	local restore_name="restore-$backup_name-remapped"

	desc "write more data before namespace remap restore by date"
	sleep 60
	run_mongo \
		"use $database\n db.$src_collection.insert({ x: 100501 })" \
		"myApp:myPass@$cluster.$namespace"

	desc 'waiting for chunks to be uploaded'
	sleep 120

	run_mongo \
		"use $database\n db.$dst_collection.drop()" \
		"myApp:myPass@$cluster.$namespace"

	if [[ $(collection_exists "$dst_collection") == "true" ]]; then
		echo "Collection $dst_collection exists before restore"
		exit 1
	fi

	desc 'check namespace remap restore by date'
	yq "$test_dir/conf/restore-namespace-remap.yml" \
		| yq ".metadata.name=\"$restore_name\"" \
		| yq ".spec.clusterName=\"$cluster_name\"" \
		| yq ".spec.backupName=\"$backup_name\"" \
		| yq ".spec.pitr.type=\"date\"" \
		| yq ".spec.pitr.date=\"$restore_date\"" \
		| yq ".spec.selective.nsFrom=\"$database.$src_collection\"" \
		| yq ".spec.selective.nsTo=\"$database.$dst_collection\"" \
		| kubectl_bin apply -f -

	wait_restore "$backup_name-remapped" "$cluster_name"
	echo
	set -o xtrace

	if [[ $(collection_exists "$dst_collection") == "false" ]]; then
		echo "Collection $dst_collection doesn't exist after restore"
		exit 1
	fi

	if [[ $(collection_exists "$src_collection") == "false" ]]; then
		echo "Collection $src_collection missing after remap restore"
		exit 1
	fi

	compare_mongo_cmd "find" "myApp:myPass@$cluster.$namespace" "-remapped" ".svc.cluster.local" "$database" "$dst_collection"
}

function get_time_now() {
	run_mongo 'new Date().toISOString()' \
		"myApp:myPass@$cluster.$namespace" \
		"mongodb" "" "--quiet" \
		| grep -E -v 'I NETWORK|W NETWORK|Error saving history file|Percona Server for MongoDB|connecting to:|Unable to reach primary for set|Implicit session:|versions do not match' \
		| cut -c1-19 | tr T " "
}

main() {
	create_infra $namespace
	deploy_minio

	desc 'create secrets and start client'
	kubectl_bin apply \
		-f "$conf_dir/secrets.yml" \
		-f "$conf_dir/client.yml" \
		-f $conf_dir/minio-secret.yml

	cluster="some-name-rs0"
	desc "create first PSMDB cluster $cluster"
	apply_cluster $test_dir/conf/$cluster.yml

	desc 'check if all 3 Pods started'
	wait_for_running $cluster 3

	desc 'check if statefulset created with expected config'
	compare_kubectl statefulset/$cluster

	write_initial_data

	wait_backup_agent $cluster-0
	wait_backup_agent $cluster-1
	wait_backup_agent $cluster-2

	backup_name_minio="backup-minio"

	run_mongo \
		'use myApp\n db.test2.insert({ x: 100501 })' \
		"myApp:myPass@$cluster.$namespace"

	desc 'restore pitr date'
	run_backup $backup_name_minio 0
	write_document "-2nd"
	sleep 2
	time_now=$(get_time_now)
	check_recovery $backup_name_minio-0 date "$time_now" "-2nd" "" "${cluster/-rs0/}" "test2"

	desc 'restore pitr latest'
	run_backup $backup_name_minio 1
	compare_latest_restorable_time "${cluster}" "${backup_name_minio}-1"
	check_recovery $backup_name_minio-1 latest "" "-3rd" "" "${cluster/-rs0/}"

	desc 'pitr restore with namespace remap'
	run_backup $backup_name_minio 2
	compare_latest_restorable_time "${cluster}" "${backup_name_minio}-2"
	time_now=$(get_time_now)
	run_recovery_check_namespace_remap "$backup_name_minio-2" "${time_now}" "${cluster/-rs0/}" "myApp" "test" "testRemapped"

	desc 'restore pitr date using backupSource'
	reset_collection
	run_backup $backup_name_minio 3
	compare_latest_restorable_time "${cluster}" "${backup_name_minio}-3"
	time_now=$(get_time_now)
	check_recovery "${backup_name_minio}-3" date "$time_now" "" backupSource "${cluster/-rs0/}"

	desc 'restore pitr latest using backupSource'
	run_backup $backup_name_minio 4
	compare_latest_restorable_time "${cluster}" "${backup_name_minio}-4"
	check_recovery "${backup_name_minio}-4" latest "" "-4th" backupSource "${cluster/-rs0/}"

	desc 'restore pitr using backupSource on second cluster with another prefix in storage'

	second_cluster="cluster2-rs0"
	apply_cluster "$test_dir/conf/$second_cluster.yml"
	wait_for_running $second_cluster 3
	wait_backup_agent $second_cluster-0
	wait_backup_agent $second_cluster-1
	wait_backup_agent $second_cluster-2
	run_mongo \
		'db.createUser({user:"myApp",pwd:"myPass",roles:[{db:"myApp",role:"readWrite"}]})' \
		"userAdmin:userAdmin123456@$second_cluster.$namespace"
	sleep 2
	check_recovery "${backup_name_minio}-4" latest "" "-4th" backupSource "${second_cluster/-rs0/}" "" "${backup_name_minio}-4-second-cluster" "restore2.yml"

	backup_name_minio_2="backup-minio2"
	run_backup $backup_name_minio_2 0
	time_now=$(get_time_now)
	write_document "-5th" "$second_cluster"
	sleep 2
	check_recovery $backup_name_minio_2-0 date "$time_now" "-4th" "" "${second_cluster/-rs0/}"

	kubectl patch psmdb "some-name" --type='merge' --patch '{"spec": {"backup": {"pitr": {"enabled": false}}}}'
	kubectl patch psmdb "${second_cluster/-rs0/}" --type='merge' --patch '{"spec": {"backup": {"pitr": {"enabled": false}}}}'
	sleep 20

	kubectl_bin delete psmdb-backup --all

	destroy $namespace

	desc 'test passed'
}

main
