apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always

  roles:
    - role: role-one
      db: admin
      privileges:
        - resource:
            cluster: true
          actions:
            - addShard
        - resource:
            db: config
            collection: ''
          actions:
            - find
            - update
            - insert
            - remove
      roles:
        - role: read
          db: admin
      authenticationRestrictions:
        - clientSource:
            - 127.0.0.1
          serverAddress:
            - 127.0.0.1

  users:
  - name: user-one
    db: admin
    passwordSecretRef: 
      name: user-one
      key: userOnePassKey
    roles:
      - name: clusterAdmin
        db: admin
      - name: userAdminAnyDatabase
        db: admin
  - name: user-gen
    db: admin
    roles:
      - name: clusterAdmin
        db: admin
      - name: userAdminAnyDatabase
        db: admin
  - name: user-external
    db: $external
    roles:
      - name: clusterAdmin
        db: admin
      - name: userAdminAnyDatabase
        db: admin

  backup:
    enabled: true
    image: perconalab/percona-server-mongodb-operator:1.1.0-backup
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    configuration: |
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  secrets:
    users: some-users
