apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: sec-context
spec:
  image:
  imagePullPolicy: Always
  allowUnsafeConfigurations: false
  replsets:
  - name: rs0
    serviceAccountName: percona-server-mongodb-operator-workload
    annotations:
      openshift.io/scc: privileged
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 0.5G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
    configuration: |
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
    containerSecurityContext:
      privileged: false
    podSecurityContext:
      fsGroup: 1001
      supplementalGroups: [1001, 1003]
  secrets:
    key: some-key
    users: some-users
  backup:
    containerSecurityContext:
      privileged: false
      runAsNonRoot: true
      runAsUser: 1001
    podSecurityContext:
      fsGroup: 1001
      supplementalGroups: [1001, 1002, 1003]
    enabled: true
    debug: true
    restartOnFailure: true
    image: perconalab/percona-server-mongodb-operator:1.2.0-backup
    storages:
      minio:
        type: s3
        s3:
          credentialsSecret: minio-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: http://minio-service:9000/
    tasks:
      - name: each-hour
        enabled: true
        schedule: "0 */1 * * *"
        storageName: minio
        compressionType: gzip
